- ethereum/.openzeppelin/goerli.json
- ethereum/.openzeppelin/ropsten.json
- ethereum/.openzeppelin/unknown-1337.json
- ethereum/.openzeppelin/unknown-4002.json
- ethereum/.openzeppelin/unknown-43113.json
- ethereum/.openzeppelin/unknown-80001.json
- ethereum/.openzeppelin/unknown-97.json
- ethereum/Deploying.md
- ethereum/networks/3.json
- ethereum/networks/4002.json
- ethereum/networks/43113.json
- ethereum/networks/5.json
- ethereum/networks/80001.json
- ethereum/networks/97.json
- ethereum/package.json
- ethereum/truffle-config.js
Deploys to:
- Goerli and Ropsten (eth testnet)
- Fuji (Avalanche testnet)
- Fantom Testnet
- Mumbai (Polygon testnet)
- BNB Testnet
Also I did one successful relay in each of them and checked their values.
> Deploy Pyth to testnet networks

- third_party/pyth/price-service/src/__tests__/rest.test.ts
- third_party/pyth/price-service/src/listen.ts
- third_party/pyth/price-service/src/rest.ts
SeqNum is not suitable for multiple sources, attestationTime is good
but we should be careful of solana clock falling behind
Also use this time for freshness metric because it's more useful.
> Price Service Multisource: Use attestationTime instead of seqnum

- solana/pyth2wormhole/client/src/cli.rs
- solana/pyth2wormhole/client/src/lib.rs
- solana/pyth2wormhole/client/src/main.rs
- solana/pyth2wormhole/client/tests/test_attest.rs
- solana/pyth2wormhole/program/src/attest.rs
- solana/pyth2wormhole/program/src/config.rs
- solana/pyth2wormhole/program/src/lib.rs
- solana/pyth2wormhole/program/src/migrate.rs
- solana/pyth2wormhole/program/src/set_config.rs
This new flag will help enable/disable attester contracts between deployments. Accompanied by the flag, we start properly maintaining config schema using a `migrate` instruction. The client-side implementation will be completed in a following changeset.
> pyth2wormhole: Add an is_active flag to on-chain config

- ethereum/contracts/pyth/PythState.sol
The Wormhole address is not designed to receive payment and we do not need to pay it.
> Remove unnecessary payable marker from wormhole address

- ethereum/contracts/pyth/Pyth.sol
This is to make it explicit that this contract should not be deployed: `PythUpgradable` should be instead.
> Make Pyth contract abstract

- Dockerfile.guardian
- devnet/node.yaml
Before this change, a fresh build from scratch would cause a guardian
software compilation error ("Failure: empty digest") that would
normally be hidden by caching in CI.
> guardiand: Bump wormhole sources

- solana/pyth2wormhole/client/src/cli.rs
- solana/pyth2wormhole/client/src/lib.rs
- solana/pyth2wormhole/client/src/main.rs
- solana/pyth2wormhole/client/tests/test_migrate.rs
The test hangs inexplicably even if I try to run only it. It is very hard to test without implementing dedicated logic to populate the obsolete config account, which makes unit testing fit really well here.
> [WIP] p2w-client: Implement a migrate command and instruction generator

- ethereum/.openzeppelin/goerli.json
- ethereum/.openzeppelin/ropsten.json
- ethereum/.openzeppelin/unknown-1313161555.json
- ethereum/.openzeppelin/unknown-4002.json
- ethereum/.openzeppelin/unknown-43113.json
- ethereum/.openzeppelin/unknown-80001.json
- ethereum/.openzeppelin/unknown-97.json
- ethereum/Deploying.md
- ethereum/migrations/prod-receiver/4_pyth_multiple_emitters.js
- ethereum/migrations/prod-receiver/5_pyth_add_events_and_update_fee.js
- ethereum/migrations/prod/3_pyth_multiple_emitters.js
- ethereum/migrations/prod/4_pyth_add_events_and_update_fee.js
- ethereum/migrations/test/4_pyth_multiple_emitters.js
- ethereum/migrations/test/5_pyth_add_events_and_update_fee.js
- ethereum/truffle-config.js
And fixes some issues for it. Specially it uses
unsafeSkipStorage to skip OZ collision check
as they are very conservative and doesn't
cover our valid memory changes.
We should be very careful in memory
changes now that we cannot use
OZ collision check.
> Upgrade testnet contracts

- solana/pyth2wormhole/client/src/lib.rs
- solana/pyth2wormhole/program/src/config.rs
- solana/pyth2wormhole/program/src/migrate.rs
This commit resolves a runtime problem in migrate() which occurred on devnet, as
well as invalid mutability for the old config and misuse of the
checked_sub() method.
The runtime problem came from a non-zero balance existing on
not-yet-used PDA. Effectively, this means permissionless
initialization of PDAs on Solana. Anyone can send lamports to any
account on Solana (existing or not), and it doesn't take much funds to
keep an empty account exempt. While it is possible to recover from it,
this case is relatively rare and takes a lot of code to
automate. Instead, we settle for a dumb bump of the config PDA
seed (see config.rs).
This measure is best used sparingly, as it imposes the same static
seed on all SOL networks. This will cause headaches if the attester
tooling grows a third-party …
> pyth2wormhole: Fix a cfg migration bug, fix cfg lockout (see below)

- ethereum/Deploying.md
- ethereum/contracts/pyth/Pyth.sol
- ethereum/migrations/prod-receiver/8_pyth_update_interface_add_update_if_necessary.js
- ethereum/migrations/prod/7_pyth_update_interface_add_update_if_necessary.js
- ethereum/migrations/test/8_pyth_update_interface_add_update_if_necessary.js
- ethereum/package-lock.json
- ethereum/package.json
- ethereum/test/pyth.js
- Change some memory modifiers to improve gas efficiency
- Implement getValidTimePeriod() and remove old staleness logic
- Update the tests
> Eth contract fix memory + new sdk + refactor

- Dockerfile.client
- solana/pyth2wormhole/client/src/attestation_cfg.rs
- solana/pyth2wormhole/client/src/cli.rs
- solana/pyth2wormhole/client/src/lib.rs
- solana/pyth2wormhole/client/src/main.rs
- solana/pyth2wormhole/client/src/message.rs
- solana/pyth2wormhole/client/tests/test_attest.rs
- solana/pyth2wormhole/client/tests/test_migrate.rs
- solana/pyth2wormhole/program/src/attest.rs
- solana/pyth2wormhole/program/src/lib.rs
- solana/pyth2wormhole/program/src/message.rs
- solana/pyth2wormhole/program/src/migrate.rs
- third_party/pyth/Dockerfile.p2w-attest
this changeset switches us to a PDA scheme for wormhole messages, accounts for reusing those accounts and conditionally switches between post_message/post_message_unreliable depending on whether a given message account was already initialized.
> Wormhole message reuse via post_message_unreliable

- devnet/pyth-evm-watcher.yaml
- devnet/pyth-price-service.yaml
remove resource memory limit that was causing pyth-price-service to crash on a fresh VM install
> remove resource memory limit

- solana/pyth2wormhole/client/src/cli.rs
- solana/pyth2wormhole/client/src/main.rs
This unblocks speculative target chain contract deployments. Assuming no solana-deployment-level problem occurs, we can add the emitter address to each contract and expect an attester program's messages to be accepted rightaway
> p2w-client: add get-emitter for printing emitter address

- solana/pyth2wormhole/client/src/lib.rs
- solana/pyth2wormhole/client/tests/test_attest.rs
- solana/pyth2wormhole/program/src/attest.rs
- solana/pyth2wormhole/program/src/message.rs
Solitaire checks ownership passed down accounts to a program with program id (usually). This causes us to consider a `P2WMessage` that is a PDA from us and owned by wormhole an invalid account and throw an error.
This PR will bypasses ownership check of P2WMessage by using `Mut<Info>` instead. Our seed generation to sign + wormhole contract check (that it is owned by wormhole) are sufficient for this.
As wormhole owns that account it is not possible to resize it. Instead added a `batch_len` to the seeds (as u64 instead of usize to be more specific about size). Also changed `p2w-message` literal in seeds to `p2w-message-v1` to indicate that we need to update it when message size per price attestation changes. It can make our message queue a bit inefficient as there might be 2 accounts per …
> Fix bugs related to P2WMessage being owned by wormhole

- solana/pyth2wormhole/program/src/attest.rs
This PR will solves a bug within wormhole that might not create the accounts with correct balance to be rent exempt. 
It will check the account balances in the end of attestation (to avoid breaking wormhole behavior) and transfers money to them if needed.
This PR will also solve a problem on balance transfer when a message account is resized to a larger size. Since the message account is owned by wormhole it is not possible to move funds back in case of resizing to a smaller size.
In order to make sure it works I used the double rent exempt amount in local testing and the transfers succeeded.
> Hack the rent exempt bug

- third_party/pyth/price-service/src/__tests__/rest.test.ts
- third_party/pyth/price-service/src/listen.ts
- third_party/pyth/price-service/src/rest.ts
add new `api/latest_price_info?ids[]=<price_feed_id>&ids[]=<price_feed_id_2>&..` endpoint that augments `latest_price_feeds` with `emitter_chain`, `attestation_time`, and `sequence_number` so that we can store these data in our historical db
sample price info:
```
[
{
"price_feed": {
"conf": "4",
"ema_conf": "3",
"ema_price": "1491",
"expo": -5,
"id": "af11a9b5e5e14838c1ecab3a0cdec6769c3d6a477da04412bd7d21bfe451ce3d",
"max_num_publishers": 1,
"num_publishers": 1,
"prev_conf": "3",
"prev_price": "1925",
"prev_publish_time": 1662140402,
"price": "1441",
"product_id": "af11a9b5e5e14838c1ecab3a0cdec6769c3d6a477da04412bd7d21bfe451ce3d",
"publish_time": 1662140407,
"status": "Trading"
},
"emitter_chain": 1,
"attestation_time": 1662140410,
"sequence_number": 14239
}
]
```
> add new latest_price_info endpoint

- solana/pyth2wormhole/client/src/main.rs
- third_party/pyth/p2w_autoattest.py
This changeset adjusts p2w_autoattest.py commitment to confirmed and
fixes a get_transaction() failure that happened due to the upstream
default finalized commitment setting (RpcClient's set value is not
used). This is fixed by using the chosen commitment explicitly via
get_transaction_with_config()
> p2w: Make commitment usage consistent

- devnet/pyth-price-service.yaml
- third_party/pyth/price-service/.env.sample
- third_party/pyth/price-service/docker-compose.yaml
- third_party/pyth/price-service/package-lock.json
- third_party/pyth/price-service/package.json
- third_party/pyth/price-service/src/index.ts
- third_party/pyth/price-service/src/listen.ts
- third_party/pyth/price-service/src/rest.ts
I made the staleness parameter an argument to the endpoint also, so we can configure it directly via the alert in datadog without redeploying the service.
I can't figure out how to build / run this code, so would love some help with that.
> Move staleness check to new endpoint

- third_party/pyth/price-service/src/ws.ts
The per-update per-client message is making a lot of noise in datadog. Collapse all the client ids into a single log message for better readability.
> Make this log message less noisy

- solana/pyth2wormhole/client/src/cli.rs
- solana/pyth2wormhole/client/src/main.rs
Apparently clap expects the id in `conflicts_with` to be a case-converted value of the field. 
I also realized that our logic was not correct for handling that parameter, so I fixed it.
> Fixing some bugs on clap and processing logic

- solana/pyth2wormhole/client/src/lib.rs
- solana/pyth2wormhole/program/src/set_config.rs
This fixes a problem I observed together with Ali in devnet. Options in borsh result in byte count changes which means the underlying account size for contract state must grow/shrink together with the serialized byte length. This change implements such a scheme.
> p2w: Monitor and realloc() + rent adjuist on cfg account size change

- solana/pyth2wormhole/client/src/attestation_cfg.rs
I realized that the Option<Pubkey> is not enough to make the mapping_addr value optional. This one-liner asks serde to do it explicitly
> pyth2wormhole-client: fix mapping_addr default for attestation config

- pythnet/remote-executor/cli/src/main.rs
- pythnet/remote-executor/programs/remote-executor/src/tests/executor_simulator.rs
I forgot to pass each subinstruction's program_id to the CPI. Tests were passing because I was CPIing into the system program, which is being passed always to the remote-executor.
> Fix program account not being passed to CPI

- third_party/pyth/multisig-wh-message-builder/src/index.ts
this is a megahack to put the instruction into this CLI, but i think it's fine to validate the authority for the moment. We need to rethink all of this contract administration stuff anyway.
tested by creating this tx
https://mesh-devnet.squads.so/transactions/6baWtW1zTUVMSJHJQVxDUXWzqrQeYBr6mu31j3bTKwY3/tx/CMaECC12bKo6vLFTT5uC5HLwFpVWt7qqWPsDMV4x1Xaz
I haven't tested set-is-active yet because i will need to get stan to set the attester ops-owner.
> Add set-is-active instruction and some minor tweaks

- third_party/pyth/price-service/src/rest.ts
The API endpoint was using the `publishTime` of the price on pythnet and not the time that the last price attestation was received. The former check catches cases where a price feed isn't updating on pythnet, which is not good for this alert because we have some feeds that shouldn't update on pythnet (e.g., equities outside of trading hours). However, the feeds are continuously attested, so checking `attestationTimestamp` should be sufficient.
> Update staleness check

- solana/pyth2wormhole/program/src/migrate.rs
This change adds the pythnet-compatible rent adjustment to the migrate instruction
> pyth2wormhole/migrate: add pythnet rent adjustment

- .gitignore
- aptos/contracts/Makefile
- aptos/contracts/Move.toml
- aptos/contracts/sources/batch_price_attestation.move
- aptos/contracts/sources/data_source.move
- aptos/contracts/sources/deserialize.move
- aptos/contracts/sources/error.move
- aptos/contracts/sources/event.move
- aptos/contracts/sources/governance/contract_upgrade.move
- aptos/contracts/sources/governance/governance.move
- aptos/contracts/sources/governance/governance_action.move
- aptos/contracts/sources/governance/governance_instruction.move
- aptos/contracts/sources/governance/set_data_sources.move
- aptos/contracts/sources/governance/set_governance_data_source.move
- aptos/contracts/sources/governance/set_stale_price_threshold.move
- aptos/contracts/sources/governance/set_update_fee.move
- aptos/contracts/sources/i64.move
- aptos/contracts/sources/price.move
- aptos/contracts/sources/price_feed.move
- aptos/contracts/sources/price_identifier.move
- aptos/contracts/sources/price_info.move
- aptos/contracts/sources/price_status.move
- aptos/contracts/sources/pyth.move
- aptos/contracts/sources/set.move
- aptos/contracts/sources/state.move
- aptos/start_node.sh
This PR implements the Pyth target chain contract on Aptos. Please see `aptos/contracts/sources/pyth.move` for documented details of how to interact with this contract.
Will add Aptos to Tilt integration tests in a follow-up PR.
> Pyth Aptos Target Chain Contract

- solana/pyth2wormhole/client/src/cli.rs
- third_party/pyth/p2w_autoattest.py
Turns out --log-level does not work because it is ignored. I think I tried to get rid of it at a different occasion but I likely missed this loose end.
> p2w-client: Remove --log-level, rely on RUST_LOG, provide default

- aptos/contracts/sources/error.move
- aptos/contracts/sources/pyth.move
Since we pass these separately (because entry functions must take primitive arguments), we should check that we have an equal number of emitter addresses and chain IDs.
> Ensure initialization data source emitter address and chain ids are equal length

- aptos/contracts/sources/pyth.move
Since anyone can register an account to receive coins, contract initialisation could potentially fail if the account has already been registered. We therefore only register the `pyth` account if it is not already registered. Note that it does not matter who registers the account.
> Only register account to receive coins if already unregistered

- solana/pyth2wormhole/client/src/attestation_cfg.rs
- solana/pyth2wormhole/client/src/batch_state.rs
Most attestation conditions in prod are interval-only. This change ensures that interval-only batches don't waste time on the on-chain state lookup request and data comparisons.
> pyth2wormhole-client:should_resend(): optimize interval-only batches

- third_party/pyth/pyth_publisher.py
- third_party/pyth/pyth_utils.py
This change will help us verify the correctness of the mapping crawling logic in p2w-attest.
> pyth_publisher.py: Add a new symbol every 2 minutes

- Tiltfile
This removes the need to pass in `--pyth` to `tilt up`.
> Start all pyth tilt pods by default

- aptos/contracts/sources/batch_price_attestation.move
- aptos/contracts/sources/deserialize.move
- aptos/contracts/sources/governance/governance.move
- aptos/contracts/sources/pyth.move
- aptos/contracts/sources/state.move
This PR moves the larger test suites into their own `#[test_only]` modules, which eliminates unnecessary "unused import" errors and reduces the bytecode size.
> Make imports used for tests `#[test_only]`

- aptos/contracts/Move.toml
This was causing some confusion, so adding a comment to clarify.
> Add comment clarifying deployed addresses

- aptos/example/sources/example.move
We now require users to pass in the update data when calculating the fee.
> Fix example to reflect breaking api change

- third_party/pyth/multisig-wh-message-builder/src/index.ts
We are logging signed VAAs after multisig execution both in base64 and hex. This PR solves the hex output. Apparently Buffer cannot always understand the type of base64 input. This change explicitly tells Buffer that the input is base64.
> Fix logging of vaa as hex

- .github/workflows/remote-executor.yml
To save more GH actions time + have faster CI checks (sometimes it takes longer than tilt!)
Afaik this code does not depend on any other codebase here, so running it only when anything within its directory has changed will work as expected.
> Run remote exec CI only if it's changed

- ethereum/contracts/pyth/PythGetters.sol
- ethereum/contracts/pyth/PythGovernance.sol
- ethereum/contracts/pyth/PythGovernanceInstructions.sol
- ethereum/contracts/pyth/PythSetters.sol
- ethereum/contracts/pyth/PythState.sol
- ethereum/test/pyth.js
- third_party/pyth/xc-governance-sdk-js/src/index.ts
- third_party/pyth/xc-governance-sdk-js/src/instructions.ts
This PR changes the way we transfer the governance data source. It introduced a new state value `governanceDataSourceIndex` that should be increased each time we transfer the governance to a newer one (extra sanity check).
Consider that we have an `oldGovenrance` and a `newGovernance`. The data wire is that the `newGovernance` creates a `TransferGovernanceDataSourceClaim` and sends to wormhole to create `claimVaa`. Then the `oldGovernance` creates a `TransferGovernanceDataSource` instruction that wraps the `claimVaa` and sends it to wormhole to create the transfer VAA. 
Tom suggested wrapping instead of taking them separately because the result would be one VAA and it fits the `executeGovernanceInstruction` signature to also execute it.
> [eth] Make governance transfer less error-prone

- ethereum/contracts/pyth/Pyth.sol
- ethereum/package-lock.json
- ethereum/package.json
- ethereum/test/pyth.js
- third_party/pyth/p2w-relay/src/relay/evm.ts
This PR:
- Updates contract to use the latest solidity sdk and updates `getUpdateFee` method to get the data instead of size (+ addressing tests + relayer). Keeps the old one for backward compatibility.
- Removes part of the code to transfer back extra paid fee amount (to be consistent with other chains that do not support it. e.g., aptos)
> [eth] Some contract improvements

- Dockerfile.client
- Dockerfile.solana
This change attempts to add useful items to the docker caching which should save time downloading crates and by adding path=<full path> and dropping id=<name> ensure that no Dockerfile cache mismatches occur. I think the id= param is meant to help group builds that benefit from common cache, but in case of pyth2wormhole-client/SOL contract builds it became a competition between the two replacing the other's caches
> Dockerfile.client, Dockerfile.solana: harden caching to cut CI time

- third_party/pyth/p2w-sdk/js/package-lock.json
- third_party/pyth/p2w-sdk/js/package.json
- third_party/pyth/price-service/package-lock.json
- third_party/pyth/price-service/package.json
- third_party/pyth/price-service/src/__tests__/rest.test.ts
- third_party/pyth/price-service/src/__tests__/ws.test.ts
- third_party/pyth/price-service/src/listen.ts
- third_party/pyth/price-service/src/rest.ts
- third_party/pyth/price-service/src/ws.ts
This PR adds receive time to the price service API metadata (exposed via verbose flag) on the rest and ws api. 
The purpose of this change is to capture the time that a price becomes available cross-chain.
> Add receive time to the price service

- aptos/examples/mint_nft/Move.toml
- aptos/examples/mint_nft/README.md
- aptos/examples/mint_nft/app/src/App.tsx
- aptos/examples/mint_nft/sources/minting.move
Update example to use APT instead of ETH now that the price feed is live.
> Update example to use APT pricefeed

- aptos/contracts/sources/pyth.move
This to enabling DeFi developers to easily mock the price when writing the integration tests between the protocol and oracle.
> [FEAT] Allow any contract to update the cache in test

- ethereum/README.md
- ethereum/forge-test/GasBenchmark.t.sol
This PR changes the benchmark test to generate gas usages that are expected and useful for our usage.
Apparently, Foundry runs all the code of a test in an imaginary transaction which is different than using hardhat/truffle. Because in hardhat/truffle, as their tests are written in JS, each contract call is a transaction. But in Foundry it's different. 
This caused problem in our benchmark because re-writing to a storage slot (other than the first write) in the same transaction costs very little (it is considered a warm access,`G_warmaccess = 100`) compared to a normal write (to a non-zero value, `G_sreset` = 2900). In addition to this, in the first write we are consuming a lot of gas as it is writing to a zero storage slot. This was the reason that fresh and non-fresh calls were not much …
> [eth]: Fix gas benchmark to generate useful gas snapshot

- third_party/pyth/pyth_publisher.py
Currently the test publisher creates a new symbol every two minutes without any cap and running tilt for a long time will eventually drain all the resources.
This change sets a cap of `PYTH_TEST_SYMBOL_COUNT` on the dynamically added symbols. It means that the test publisher starts with `PYTH_TEST_SYMBOL_COUNT` and will add `PYTH_TEST_SYMBOL_COUNT` new symbols after that over time.
> [test-publisher]: Set cap on dyn added symbols

- ethereum/contracts/pyth/Pyth.sol
- ethereum/contracts/pyth/PythDeprecatedStructs.sol
- ethereum/contracts/pyth/PythInternalStructs.sol
- ethereum/contracts/pyth/PythState.sol
This PR removes unneeded `PriceInfo` fields and rearranges the struct in a way that it takes less storage (only two slots) and be optimized for reads (only one slot). However all the benefits from this change might not be visible now and will come in the next PRs, for example, changing `getPrice` to only read the second half of the price info and accessing timestamp directly. Current change resulted in ~15-25% gas improvement over total transaction gas usage.
The surface logic of the contract has not changed much. The only change is that for the existence of a price feed, instead of ID we are using the `publishTime`.
```
testBenchmarkUpdatePriceFeedsNotFresh() (gas: -66595 (-14.660%)) 
testBenchmarkUpdatePriceFeedsIfNecessaryFresh() (gas: -104087 (-19.175%)) …
```
> Modify PriceInfo struct for gas optimization

- ethereum/contracts/pyth/Pyth.sol
- ethereum/contracts/pyth/PythInternalStructs.sol
- ethereum/forge-test/utils/PythTestUtils.t.sol
- ethereum/test/pyth.js
Before converting VAA payloads to PriceInfo we convert them to PriceAttestation which is the equivalent of the payload wire format. However, this middle conversion has some costs, because (1) we copy stuff twice, and (2) we have some unused fields. 
This PR removes the middle structs and creates PriceInfo directly from the VAA payload. 
The gas improvement is not substantial, but still good (~14k gas save)
The gas snapshot difference:
```
testBenchmarkGetUpdateFee() (gas: -22 (-0.016%)) 
testBenchmarkUpdatePriceFeedsIfNecessaryNotFresh() (gas: 110 (0.054%)) 
testBenchmarkUpdatePriceFeedsIfNecessaryFresh() (gas: -22212 (-5.063%)) 
testBenchmarkUpdatePriceFeedsFresh() (gas: -22272 (-5.374%)) 
testBenchmarkUpdatePriceFeedsNotFresh() (gas: -22236 (-5.736%)) 
```
> Remove middle structs

- ethereum/contracts/pyth/Pyth.sol
- ethereum/contracts/pyth/PythGetters.sol
When updating the price we only need to know the publish time of the cached price and don't need to read the whole memory. This change adds a method to get the publish time directly and uses it all the places that is possible within the code base here. We can use it in `updatePriceFeedsIfNecessary` too, but since it's in the sdk right now we cannot change it. Will do that later when we move the sdk inside this repo.
```
testBenchmarkGetUpdateFee() (gas: 22 (0.016%)) 
testBenchmarkUpdatePriceFeedsFresh() (gas: -6822 (-1.740%)) 
testBenchmarkUpdatePriceFeedsIfNecessaryFresh() (gas: -7878 (-1.891%)) 
testBenchmarkUpdatePriceFeedsIfNecessaryNotFresh() (gas: -4834 (-2.388%)) 
testBenchmarkUpdatePriceFeedsNotFresh() (gas: -14822 (-4.056%)) 
```
> [eth] Use latestPriceInfoPublishTime when possible

- ethereum/contracts/pyth/Pyth.sol
Thanks @njkumr for suggesting this!
There is no overflow possible in the parsing method and we can wrap every line in unchecked which won't be clean. So the whole method is now wrapped in an unchecked scope.
> Most of the math operations below are simple additions. In the places that there is more complex operation there is a comment explaining why it is safe. Also, byteslib operations have proper require checks.
Gas snapshot change is very high:
```
testBenchmarkUpdatePriceFeedsIfNecessaryNotFresh() (gas: 0 (0.000%)) 
testBenchmarkUpdatePriceFeedsIfNecessaryFresh() (gas: -8001 (-1.958%)) 
testBenchmarkUpdatePriceFeedsFresh() (gas: -8001 (-2.076%)) 
testBenchmarkUpdatePriceFeedsNotFresh() (gas: -7737 (-2.207%)) 
```
> [eth] Wrap parsing method with unchecked

- ethereum/contracts/pyth/Pyth.sol
- ethereum/contracts/pyth/PythGetters.sol
- ethereum/contracts/pyth/PythInternalStructs.sol
Again suggested by @njkumr. Removing the struct and emaExpo and emaPublishTime has impact on gas usage. Also moving publishTime to be the first item saves ~200 gas (due to how solidity packs/unpacks slots to memory)
```
testBenchmarkUpdatePriceFeedsNotFresh() (gas: -1239 (-0.361%)) 
testBenchmarkUpdatePriceFeedsFresh() (gas: -1787 (-0.474%)) 
testBenchmarkUpdatePriceFeedsIfNecessaryFresh() (gas: -2179 (-0.544%)) 
testBenchmarkUpdatePriceFeedsIfNecessaryNotFresh() (gas: -1938 (-0.981%)) 
testBenchmarkGetPrice() (gas: -365 (-1.347%)) 
```
> [eth] Change internal storage layout and order

- ethereum/contracts/pyth/Pyth.sol
- ethereum/forge-test/utils/PythTestUtils.t.sol
- ethereum/package-lock.json
- ethereum/package.json
- ethereum/test/pyth.js
This PR omits unnecessary fields in the events and also removes the `UpdatePriceFeeds` events (as its information could be retrieved somehow). Also because of the new event structure it won't emit any `PriceFeedUpdate` for non-fresh updates.
snapshot difference:
```
testBenchmarkGetPrice() (gas: -13 (-0.049%)) 
testBenchmarkUpdatePriceFeedsIfNecessaryFresh() (gas: -10675 (-2.731%)) 
testBenchmarkUpdatePriceFeedsFresh() (gas: -10675 (-2.901%)) 
testBenchmarkUpdatePriceFeedsNotFresh() (gas: -18899 (-5.658%)) 
```
p.s: As the sdk is updated, `parsePriceFeedUpdates` is added to the interface. I added it with a ToDo to be addressed in a separate PR.
> [eth] Gas improvement: Optimize events

- ethereum/contracts/pyth/Pyth.sol
- ethereum/forge-test/GasBenchmark.t.sol
AbstractPyth constructs price and emaPrice by creating a complete PriceFeed but it has some gas overhead as not everything in PriceFeed is used. This will reduce our `getPrice` and `getEmaPrice` gas usage significantly.
```
testBenchmarkGetEmaPrice() (gas: -1202 (-4.488%)) 
testBenchmarkGetPrice() (gas: -3297 (-12.341%)) 
```
p.s: above numbers have decreased a bit due to addition of `expo` field that I missed before. (for `testBenchmarkGetPrice` it is -3226)
> [eth] Gas improvement: Optimize getPrice and getEmaPrice

- ethereum/foundry.toml
- ethereum/truffle-config.js
Increasing optimizer runs will optimize the gas usage of methods more and will increase the contract size, hence the deployment cost.
After this change the standard JSON compiler output size changes from 432K to 456K.
```
testBenchmarkGetUpdateFee() (gas: -101 (-0.076%)) 
testBenchmarkUpdatePriceFeedsIfNecessaryNotFresh() (gas: -325 (-0.184%)) 
testBenchmarkUpdatePriceFeedsNotFresh() (gas: -1291 (-0.410%)) 
testBenchmarkUpdatePriceFeedsIfNecessaryFresh() (gas: -1605 (-0.424%)) 
testBenchmarkUpdatePriceFeedsFresh() (gas: -1555 (-0.435%)) 
testBenchmarkGetPrice() (gas: -259 (-0.969%)) 
```
p.s: I read one place that `runs` is an estimate of how many times the contract is expected to be called as opposed to number of optimization passes through the code!
Update:
tests …
> [eth] Gas improvement: Increase optimizer runs to 10000

- .github/workflows/ethereum-contract.yml
Add Foundry tests for the ethereum contract to the CI. They will be executed once a file within related directories change. Please see [this](https://github.com/pyth-network/pyth-crosschain/actions/runs/3539336678) as a successful output.
> [eth] Add CI for Foundry tests

- ethereum/contracts/pyth/Pyth.sol
- ethereum/contracts/pyth/PythGovernance.sol
- ethereum/contracts/pyth/PythGovernanceInstructions.sol
- ethereum/contracts/pyth/PythUpgradable.sol
- ethereum/forge-test/GasBenchmark.t.sol
- ethereum/forge-test/Pyth.t.sol
- ethereum/package-lock.json
- ethereum/package.json
- ethereum/test/pyth.js
This PR uses PythErrors structs instead of error strings everywhere and updates the tests (both truffle and foundry). This change reduces contract size from 23.69KB to 20.94KB.
Notes:
- Error structs are only possible with `revert`. So I changed all `require` statements to `revert`.
- Truffle does not support error structs and I adopted a solution from [here](https://github.com/OpenZeppelin/openzeppelin-test-helpers/issues/180) and created `expectRevertCustomError`.
> [eth] Use PythErrors everywhere

- ethereum/contracts/pyth/PythState.sol
- ethereum/foundry.toml
- ethereum/truffle-config.js
Now that the contract size is smaller we can increase the optimization runs again. This PR changes it to 10000. It changes contract size from 19.22KB to 21.16KB but saves more gas. Below is the snapshot difference:
```
testBenchmarkUpdatePriceFeedsIfNecessaryNotFresh() (gas: -24 (-0.014%)) 
testBenchmarkGetUpdateFee() (gas: -21 (-0.016%)) 
testBenchmarkGetEmaPrice() (gas: -18 (-0.071%)) 
testBenchmarkGetPrice() (gas: -30 (-0.128%)) 
testBenchmarkUpdatePriceFeedsIfNecessaryFresh() (gas: -801 (-0.212%)) 
testBenchmarkUpdatePriceFeedsFresh() (gas: -801 (-0.224%)) 
testBenchmarkParsePriceFeedUpdatesForTwoPriceFeed() (gas: -741 (-0.233%)) 
testBenchmarkUpdatePriceFeedsNotFresh() (gas: -741 (-0.235%)) 
testBenchmarkParsePriceFeedUpdatesForOnePriceFeed() (gas: -741 (-0.238%)) …
```
> [eth]: Improve optimization runs to 10000

- prometheus_config.yaml
- third_party/pyth/price-service/package-lock.json
- third_party/pyth/price-service/package.json
- third_party/pyth/price-service/src/__tests__/rest.test.ts
- third_party/pyth/price-service/src/__tests__/ws.test.ts
- third_party/pyth/price-service/src/listen.ts
- third_party/pyth/price-service/src/promClient.ts
- third_party/pyth/price-service/src/rest.ts
- Remove nodejs default metrics. We don't use them.
- Remove response time metric.
- Remove freshness metric and add gap metric for attestationTime and publishTime.
They are similar; however, freshness was measured upon user request but gap is
measured upon receiving the next update.
- Change receivedVaa to actually represent distinct vaa received. Prior
to this, the older vaas, or vaas with same attestation time were
not counted in this metric. This will also improve the performance.
- Refactors the code a little. `vaaBytes` type was not string and was
Buffer. It is fixed now.
> [price-service] Fine-tune metrics

- solana/pyth2wormhole/Cargo.lock
- solana/pyth2wormhole/client/Cargo.toml
- third_party/pyth/p2w_autoattest.py
In the last change that I removed additional logs this loop became empty and I forgot to replace it with a better command. This empty while true was causing a high cpu usage for our attester and I verified it locally. Thanks @drozdziak1 for catching it.
> [attester] Remove while true and wait instead

- Tiltfile
- devnet/check-attestations.yaml
- third_party/pyth/Dockerfile.check-attestations
- third_party/pyth/Dockerfile.p2w-attest
- third_party/pyth/check_attestations.py
- third_party/pyth/p2w_autoattest.py
- third_party/pyth/pyth_publisher.py
- third_party/pyth/pyth_utils.py
This PR adds a new job to tilt that checks that all symbols being published are also being attested. I tweaked some things on the publisher http endpoint to ensure that the check only succeeds once all of the dynamically-added symbols are generated. I also tweaked the configuration there to make tilt complete a little faster.
> Integration test for attestations

- third_party/pyth/p2w_autoattest.py
With the default attestations config we no longer need to specify config for the mapping group.
> [attester] Remove mapping from testing config

- third_party/pyth/price-service/package-lock.json
- third_party/pyth/price-service/package.json
- third_party/pyth/price-service/src/listen.ts
Prior to this PR, we cached the VAAs and skipped them based on the entire VAA hash; Also we have a metric for counting distinct received VAAs. However, it seems that a VAA can have different signature sets and that will results in different hashes. 
This PR changes the hash to the hash of the VAA payload which is always unique.
> Update the VAA hash to use payload hash

- third_party/pyth/price-service/package-lock.json
- third_party/pyth/price-service/package.json
- third_party/pyth/price-service/src/listen.ts
In #422 I used the payload as the key for VAA hash and metric count. However, there might be possible cases that this metric is not unique. This PR changes that to the tuple of `(emitter_chain_id, emitter_address, sequence)` which is guaranteed to be unique per VAA.
> [price-service] Update Vaa key for cache/metrics

- third_party/pyth/price-service/package-lock.json
- third_party/pyth/price-service/package.json
- third_party/pyth/price-service/src/listen.ts
This PR aims to make the gap metric more accurate. It might slightly improve the latency of prices as described below.
The problem is that multiple attesters might attest the same price that results in the same batch information but on different VAAs. This PR will use sequence number to store the most recent one. As in one second there are multiple slots, doing so will allow price service to pick a slightly more recent price to serve (if such a thing happens).
Why is it important for metrics? Because we often compare the trens of the attestation gap metric with the vaa received metrics. After doing this change, the trend difference of these two will show how many out of order VAAs we do have and is a useful information. 
Why sequence number alone is not used? Because we might have …
> [price-service] Make gap metrics more accurate

- cosmwasm/Cargo.lock
- cosmwasm/README.md
- cosmwasm/contracts/pyth/Cargo.toml
- cosmwasm/contracts/pyth/src/contract.rs
- cosmwasm/contracts/pyth/src/error.rs
- cosmwasm/contracts/pyth/src/governance.rs
- cosmwasm/contracts/pyth/src/lib.rs
- cosmwasm/contracts/pyth/src/msg.rs
- cosmwasm/contracts/pyth/src/state.rs
- cosmwasm/tools/deploy.js
- third_party/pyth/p2w-relay/src/relay/terra.ts
Add the set fee governance instruction to the cosmos contract. I thought this would be a good warmup but the change sprawled a bit because I needed to add governance instructions, serialization, etc. I'll leave some comments inline on anything nonobvious.
> [cosmos] Implement set fee governance instruction

- third_party/pyth/multisig-wh-message-builder/src/index.ts
We need `create` and `verify` to be compatible with program-admin generated json.
This PR adds the `--file` to `create` and `verify`. Only one of `--payload` or `--file` can be provided. 
When `--file` is provided the tool will parse the path provided and try to create a proposal with the instruction in that file.
Welcome to ideas to make it more understandable. I find payload/file somehow confusing.
> [multisig-cli] Add support for json

- devnet/p2w-attest.yaml
- solana/pyth2wormhole/Cargo.lock
- solana/pyth2wormhole/client/Cargo.toml
- solana/pyth2wormhole/client/src/attestation_cfg.rs
- solana/pyth2wormhole/client/src/healthcheck.rs
- solana/pyth2wormhole/client/src/lib.rs
- solana/pyth2wormhole/client/src/main.rs
- solana/pyth2wormhole/client/src/util.rs
As a last resort, it makes sense to restart the attester service in production if it consistently fails to produce successful attestations.
A new attestation config yaml value `healthcheck_window_size` is introduced. This number decides how many last attestations must all fail before the service reports as unhealthy. The default is 100 consecutive failures.
A new endpoint is served alongside the metrics under `/healthcheck` (socket binds to 0.0.0.0:3000 by default).
A well-commented usage example is available in the k8s YAML in `devnet/p2w-attest.yaml`
1. the k8s tilt service has a new liveness probe for the attester
2. Tilt did not mark the service as green until it saw a 200 OK status code 
3. The ambiguous state before the healthcheck window is filled is represented with the 307 Moved …
> [wormhole-attester] Add a healthcheck on the metrics port

- third_party/pyth/multisig-wh-message-builder/src/index.ts
Fixes the check that checks if a vault already exists at the address when trying to create a new vault.
> [multisig-cli] Refactor check that multisig vault already exists

- cosmwasm/contracts/pyth/src/contract.rs
- cosmwasm/contracts/pyth/src/governance.rs
- cosmwasm/contracts/pyth/src/msg.rs
- cosmwasm/contracts/pyth/src/state.rs
- cosmwasm/tools/deploy.js
- third_party/pyth/p2w-relay/src/relay/terra.ts
Clean up a few miscellaneous issues from earlier PRs. Main changes are:
* Use PythDataSource consistently across initialization messages and configs
* Use Coin in the config and initialization message instead of separate fee/denom parameters
I suggest reading `msg.rs` and `state.rs` first to get the main changes before looking at `contract.rs` (which is mostly mechanical)..
> [cosmos] Misc code cleanup

- cosmwasm/contracts/pyth/src/governance.rs
- cosmwasm/contracts/pyth/src/lib.rs
This check prevents us from accidentally missing a part of a governance message if we upgrade the format.
> [cosmos] Require governance instruction bytes to be completely consumed

- cosmwasm/README.md
- cosmwasm/contracts/pyth/src/contract.rs
- cosmwasm/contracts/pyth/src/governance.rs
- cosmwasm/tools/deploy-pyth-bridge.js
- cosmwasm/tools/package.json
Add the code for upgrading the contract and patch up the deployment script so it works on the new Terra network.
I haven't tested the upgrade process yet, as it's hard to do with the current deployment tools. I'll do some more work on the deployment process and then circle back to testing upgrades.
> Upgrade contract & fix deployment script

- ethereum/.env.prod.zksync_goerli
- ethereum/.gitignore
- ethereum/Deploying.md
- ethereum/deploy.sh
- ethereum/deploy/zkSyncDeploy.ts
- ethereum/deploy/zkSyncDeployNewPythImpl.ts
- ethereum/hardhat.config.ts
- ethereum/networks/280.json
- ethereum/package-lock.json
- ethereum/package.json
- ethereum/scripts/syncPythState.js
- ethereum/truffle-config.js
This PR adds the requied files and configurations for deploying Pyth to zkSync networks (currently only testnet).
Unfortunately they only support hardhat and I needed to rewrite deployment scripts. The zksync plugin expects deployment scripts to be on `deploy` directory and I couldn't get away from it.
Also as our deployment/sync script is based in truffle contract upgrades won't work automatically and I added a script for the part that needs to be done in hardhat with proper documentation. It is not very clean and I might change it in the future (or the deployment automation might improve it).
Please read Deploying.md for more information on how this works.
> [eth] Add zksync deployment files

- third_party/pyth/p2w_autoattest.py
- tilt-devnet/docker-images/Dockerfile.client
- wormhole-attester/client/src/healthcheck.rs
- wormhole-attester/client/src/main.rs
This PR fixes a missing assignment to HealthCheckState's enable
flag. This would cause the attester to ignore all settings (including
defaults) and keep the enable flag set to false because we would never
bother setting it from attestation_cfg that came at runtime.
The bug is fixed and the healthcheck behavior is hardened. Currently,
the lazy_static block will explicitly initialize the global with
default values from attestation_cfg (enable is true, window size is
100). This prevents a similar human error from disabling the
healthcheck. Secondly, main.rs overwrites the default values using the
HealthCheckState::new() constructor, instead of individual struct
member assignments. This ensures that all necessary values or their
defaults are passed as the desired healthcheck state.
> wormhole-attester: port the v1.3.0 healthcheck hotfix

- xc-admin/.gitignore
- xc-admin/lerna.json
- xc-admin/package.json
- xc-admin/packages/xc-admin-common/package.json
- xc-admin/packages/xc-admin-common/tsconfig.json
Some scaffolding. I see the project as a lerna folder. With:
- a xc-admin-common package that the other packages will share
- a website package
- a cli package
- packages for relayers
> Scaffolding for xc-admin (new crosschain admin tool)

- .github/workflows/xc-admin.yaml
- xc-admin/package.json
- xc-admin/packages/xc-admin-common/src/__tests__/GovernancePayload.test.ts
- xc-admin/packages/xc-admin-common/src/governance_payload/ExecutePostedVaa.ts
- xc-admin/packages/xc-admin-common/src/governance_payload/index.ts
Add encoder for governance header and ExecutePostedVaa
> [xc-admin] Add encoder for governance messages

- xc-admin/packages/xc-admin-common/src/__tests__/GovernancePayload.test.ts
- xc-admin/packages/xc-admin-common/src/governance_payload/ExecutePostedVaa.ts
- xc-admin/packages/xc-admin-common/src/governance_payload/index.ts
export function `decodeHeader(data: Buffer)` was returning `GovernanceHeader | undefined`.
This made things complicated because when you called this function there were 3 outcomes :
- a) throws error
- b) returns undefined
- c) returns something
So I decided to switch to throwing errors instead of undefined.
> Xc admin/change error handling

- xc-admin/packages/xc-admin-common/src/__tests__/GovernancePayload.test.ts
- xc-admin/packages/xc-admin-common/src/__tests__/WormholeMultisigInstruction.test.ts
- xc-admin/packages/xc-admin-common/src/governance_payload/ExecutePostedVaa.ts
- xc-admin/packages/xc-admin-common/src/governance_payload/index.ts
- xc-admin/packages/xc-admin-common/src/multisig_transaction/WormholeMultisigInstruction.ts
- xc-admin/packages/xc-admin-common/src/propose.ts
Because it enables using instanceof like with `MultisigInstruction`
Each type of governanceAction will have it's own class with :
`encode() : Buffer`
`decode(data : Buffer) : Self | undefined`
> [xc-admin] Refactor wormhole messages as classes

- xc-admin/packages/xc-admin-common/src/__tests__/GovernancePayload.test.ts
- xc-admin/packages/xc-admin-common/src/__tests__/WormholeMultisigInstruction.test.ts
- xc-admin/packages/xc-admin-common/src/governance_payload/ExecutePostedVaa.ts
- xc-admin/packages/xc-admin-common/src/governance_payload/index.ts
- Governance Header becomes a class
- Governance Header encoding doesn't require to pass a buffer
- Buffer Layouts become static members of the classes
- Some comments
> [xc-admin] Header becomes class

- xc-admin/packages/xc-admin-common/src/__tests__/GovernancePayload.test.ts
- xc-admin/packages/xc-admin-common/src/__tests__/WormholeMultisigInstruction.test.ts
- xc-admin/packages/xc-admin-common/src/governance_payload/ExecutePostedVaa.ts
- xc-admin/packages/xc-admin-common/src/governance_payload/index.ts
- xc-admin/packages/xc-admin-common/src/multisig_transaction/PythMultisigInstruction.ts
- xc-admin/packages/xc-admin-common/src/multisig_transaction/WormholeMultisigInstruction.ts
- xc-admin/packages/xc-admin-common/src/multisig_transaction/anchor.ts
- xc-admin/packages/xc-admin-common/src/multisig_transaction/index.ts
Try to switch to a world where nothing can throw errors.
- Update `decode` to not throw and instead return undefined
- resolveAccountName can't throw
How `undefined` are handled :
- 1. If we don't recognize the program of the instruction, it becomes `UnrecognizedProgram implements MultisigInstruction` which stores the instruction (useful to print the instruction)
- 2. If we don't recognize an instruction in `PythMultisigInstruction` or `WormholeMultisigInstruction` the name of the instruction is set to `unrecognizedInstruction` instead of for example `postMessage` or `addPrice`.
- 3. If we recognize a `postMessage` in `WormholeMultisigInstruction` but we can't deserialize the wormhole payload `wormholeMultisigInstruction.governanceAction` will be `undefined`, but the payload is stored in …
> [xc-admin] Decoders can't throw

- price-service/package-lock.json
- price-service/package.json
- price-service/src/helpers.ts
- price-service/src/index.ts
- price-service/src/listen.ts
- price-service/src/rest.ts
This PR refactors `get_vaa` endpoint and adds another CCIP-compatible endpoint with the same functionality.
> [price-service] Add get_vaa_ccip endpoint

- governance/xc-admin/package-lock.json
- governance/xc-admin/packages/crank-executor/package.json
- governance/xc-admin/packages/crank-executor/src/index.ts
- governance/xc-admin/packages/xc-admin-cli/src/index.ts
- governance/xc-admin/packages/xc-admin-common/src/multisig_transaction/index.ts
- governance/xc-admin/packages/xc-admin-common/src/propose.ts
The crank that executes the proposals will be aware of wormhole transactions and pay the transfer fee
> [xc-admin] Add wormhole logic to the crank-executor

- price-service/package-lock.json
- price-service/package.json
- price-service/src/__tests__/rest.test.ts
- price-service/src/listen.ts
- price-service/src/rest.ts
The problem is that when `verbose` is enabled in the price service the sequence number is converted to JSON. In #495 I updated wormhole package and this got converted to bigint and apparently JSON cannot handle the conversion.
Why it was not caught? because we did not have proper testing in place. I will add proper tests for this and other untested parts in subsequent PRs.
> [price-service] Hotfix a serde problem

- price-service/package-lock.json
- price-service/package.json
- price-service/src/rest.ts
`get_vaa` method says a price feed does not exist if it has leading 0x. This PR fixes that and also cleans up some other 0x usages.
> [price-service] Hotfix leading 0x problem

- governance/xc-admin/packages/xc-admin-cli/src/index.ts
> [xc-admin] CLI command to upgrade solana programs

- price-service/src/__tests__/listen.test.ts
- price-service/src/__tests__/rest.test.ts
- price-service/src/__tests__/ws.test.ts
- price-service/src/listen.ts
- tilt-devnet/k8s/pyth-price-service.yaml
This PR improves the existing tests and adds test for the newly added `get_vaa` endpoint. Also adds tests to the tilt so we never miss them.
`listen.ts` is changed slightly to make testing easier.
> [price-service] Improve and update tests

- governance/xc-admin/packages/xc-admin-frontend/components/tabs/UpdatePermissions.tsx
- fix bug where setting new pubkey and reverting the change doesnt reflect properly
- fix bug where switching to cluster with permissionAccount and switching back doesnt show default value
> [xc-admin] frontend update permissions bugfix

- target_chains/cosmwasm/contracts/README.md
- target_chains/cosmwasm/examples/cw-contract/Cargo.lock
- target_chains/cosmwasm/examples/cw-contract/Cargo.toml
https://github.com/pyth-network/pyth-crosschain/releases/tag/pyth-cosmwasm-v0.1.0
> [cosmwasm] Update to use cosmwasm release

- governance/remote_executor/programs/remote-executor/Cargo.toml
Pythtest feature needed because the address of wormhole is different on Pythtest and Pythnet
> [remote-executor] Pythtest feature

- governance/xc-admin/packages/xc-admin-cli/src/index.ts
As said on Slack. I don't like that needing to encode instructions in a JSON and then proposing so this is the equivalent of init-price from program-admin but direct to multisig.
Program-admin should definitely have it though for the non-multisig networks.
BTW this seems like something that doesn't happen very often so I think I CLI works well.
> [Xc admin] init price

- governance/xc-admin/packages/xc-admin-frontend/components/ClusterSwitch.tsx
- governance/xc-admin/packages/xc-admin-frontend/components/tabs/MinPublishers.tsx
- governance/xc-admin/packages/xc-admin-frontend/components/tabs/UpdatePermissions.tsx
This enables upd_permission for pythtest
TODO: Move multisigAuthority, isRemote, WORMHOLE_ADDRESS[getMultisigCluster(cluster)] and UPGRADE_MULTISIG[getMultisigCluster(cluster)] to the multisig hook? The remote, not-remote logic will be used in all tabs.
WDYT @cctdaniel
> [Xc admin] upd permissions remote

- tilt_devnet/docker_images/Dockerfile.solana
Any reason not to do this? Useful because soon we will have a recent version of wormhole on pythnet.
> Wormhole bump to check if anything breaks

- .github/workflows/price-server-image-push.yml
- price_service/server/README.md
Ok so I found some Dockerfile.wasm mentions in the repo. @ali-bahjati you're probably already aware, since I think these command will need to be updated to build lerna.
> [price-service] Remove wasm from readme and workflow

- .github/workflows/lerna.yaml
- governance/multisig_wh_message_builder/.eslintrc.js
- governance/multisig_wh_message_builder/src/index.ts
- governance/multisig_wh_message_builder/src/multisig.ts
- governance/multisig_wh_message_builder/src/util.ts
- governance/multisig_wh_message_builder/tsconfig.json
- governance/xc_admin/packages/crank_executor/tsconfig.json
- governance/xc_admin/packages/crank_pythnet_relayer/tsconfig.json
- governance/xc_admin/packages/xc_admin_cli/tsconfig.json
- governance/xc_admin/packages/xc_admin_common/tsconfig.json
- governance/xc_governance_sdk_js/src/instructions.ts
- governance/xc_governance_sdk_js/tsconfig.json
- price_service/sdk/js/tsconfig.json
- price_service/server/tsconfig.json
- third_party/pyth/p2w-relay/tsconfig.json
- tilt_devnet/docker_images/Dockerfile.lerna
- tsconfig.base.json
- wormhole_attester/sdk/js/src/index.ts
- wormhole_attester/sdk/js/tsconfig.json
This PR:
- Adds a base tsconfig to avoid redundancy
- Fixes lint errors and add lint check to the CI
I created this based on Guillermo suggestion on the PR that added lerna for all the packages.
Notes:
- I did not add `skipLibCheck` to the base as it can have unwanted side-effects for us. We can consider adding it later.
- The paths in TS config file are relative to the config file that defines them and not the project. So I needed to define them everywhere.
> [refactor] Improve typescript codebase

- price_service/server/src/listen.ts
We seem to be getting a very stale price update for a feed that no longer exists in a wormhole VAA from the spy (somehow). This is causing our stale feeds alert to trigger. The seems to get sent every time the service & spy are restarted, so that doesn't resolve the problem.
This PR adds logic to filter out very stale prices before storing them locally, which should resolve the false positive alert.
> [price-service] Ignore old price updates from wormhole

- governance/xc_admin/packages/xc_admin_frontend/components/tabs/UpdateProductMetadata.tsx
This code doesn't do anything because JSON.parse already deletes duplicates and keeps the last appearance of the key.
> [xc-admin-frontend] Remove code that checks duplicated

- price_service/server/README.md
- price_service/server/docker-compose.mainnet.yaml
- price_service/server/docker-compose.testnet.yaml
- third_party/pyth/p2w-relay/src/listen.ts
I tried running the price-service by myself and these things would have helped me.
> [price-service] Make the README better

- governance/xc_admin/packages/crank_executor/src/index.ts
- governance/xc_admin/packages/xc_admin_cli/package.json
- governance/xc_admin/packages/xc_admin_cli/src/index.ts
- governance/xc_admin/packages/xc_admin_cli/src/ledger.ts
- package-lock.json
Ok this PR became a little big :
- Add more logging to the crank executor
- Add ledger support to `xc_admin_cli`. Thanks @cctdaniel 
- Add command to approve transactions to `xc_admin_cli `
- Fix some bugs around remote instructions in` xc_admin_cli`
> [Xc-admin] ledger

- Tiltfile
- price_service/client/js/Dockerfile
- price_service/client/js/package.json
- price_service/client/js/src/__tests__/connection.e2e.test.ts
- price_service/client/js/src/index.ts
- third_party/pyth/p2w_autoattest.py
- tilt_devnet/k8s/pyth-price-client-js.yaml
The tests are very basic to ensure the api is correct and works as expected. Will improve it when we need to touch the clients.
> [price-service/client] Add e2 test

- package-lock.json
- price_service/server/package.json
- price_service/server/src/listen.ts
Currently our vaa counter metric seems to be showing more vaas than what we actually receive. This PR will try to address that issue by increase observedVaaCache and moving some checks around to ensure no VAA is counted twice.
> [price_service/server] Improve vaa counter metric

- price_service/server/package.json
- price_service/server/src/__tests__/rest.test.ts
- price_service/server/src/rest.ts
SNX wants to be able to pass the result payload directly to the `parseAndVerify` function. I think that's a simpler interface for our users, and we don't really need the publishTime here (I think?) so do it.
> [price service] Return VAA without prepending publish time

- governance/xc_admin/packages/xc_admin_frontend/components/tabs/Proposals.tsx
- governance/xc_admin/packages/xc_admin_frontend/hooks/useMultisig.ts
- governance/xc_admin/packages/xc_admin_frontend/styles/globals.css
- add approve/reject/execute/cancel buttons
- fix useMultisig hook not returning correct isLoading value
> [xc-admin] add approve/reject/execute/cancel buttons

- target_chains/cosmwasm/pyth-sdk-cw/src/lib.rs
- target_chains/cosmwasm/pyth-sdk-cw/src/testing.rs
> [cosmwasm] add testing module

- target_chains/cosmwasm/pyth-sdk-cw/src/lib.rs
> [cosmwasm] add query helper functions

- .github/workflows/publish-pyth-sdk-cw.yml
- target_chains/cosmwasm/contracts/README.md
- target_chains/cosmwasm/examples/cw-contract/Cargo.toml
- target_chains/cosmwasm/pyth-sdk-cw/README.md
- target_chains/cosmwasm/pyth-sdk-cw/src/testing.rs
> [cosmwasm] Release setup

- governance/xc_admin/packages/crank_executor/src/index.ts
- governance/xc_admin/packages/crank_pythnet_relayer/src/index.ts
Add logic for the relayer to create price and product accounts.
> [xc-admin] crank relayer needs to create price and product accounts

- governance/xc_admin/packages/xc_admin_common/src/propose.ts
- Restore autoapprove for ops key convinience
- Make ops key wormhole payer so that the multisig doesn't need to hold any balance
> [xc-admin] Restore approve

- governance/xc_admin/packages/xc_admin_frontend/components/tabs/Proposals.tsx
Fix targetChain to be pythtest when on the pythtest tab.
> [xc-admin] Fix bug with targetChain

- governance/xc_admin/packages/crank_executor/src/index.ts
- governance/xc_admin/packages/crank_pythnet_relayer/src/index.ts
- governance/xc_admin/packages/xc_admin_common/src/cranks.ts
- governance/xc_admin/packages/xc_admin_common/src/deterministic_oracle_accounts.ts
- governance/xc_admin/packages/xc_admin_common/src/index.ts
- governance/xc_admin/packages/xc_admin_common/src/remote_executor.ts
- governance/xc_admin/packages/xc_admin_frontend/components/tabs/General.tsx
- Move all deterministic accounts functions to `determistic_oracle_accounts.ts`
- Move envOrErr to `cranks.ts`
> [xc-admin] Refactor deterministic addresses 

- target_chains/cosmwasm/Cargo.lock
- target_chains/cosmwasm/Cargo.toml
- target_chains/cosmwasm/contracts/pyth/Cargo.toml
- tilt_devnet/docker_images/Dockerfile.solana
- wormhole_attester/Cargo.lock
- wormhole_attester/client/Cargo.toml
- wormhole_attester/program/Cargo.toml
- wormhole_attester/program/src/attest.rs
- wormhole_attester/program/src/initialize.rs
- wormhole_attester/program/src/migrate.rs
- wormhole_attester/sdk/rust/Cargo.toml
This change upgrades our wormhole cargo dependency to the current latest release. It introduces a fix in rent calculation logic, making Solitaire compatible with PythNet. This lets us get rid of dedicated rent adjustment logic, which we also remove in this change. Additionally, the Dockerfile.client Wormhole CLI's are bumped to match on top of Guillermo's recent version bump
> Bump wormhole rust crates to v2.14.8, remove rent adjustment

- governance/xc_admin/packages/xc_admin_common/src/__tests__/TransactionSize.test.ts
- governance/xc_admin/packages/xc_admin_common/src/propose.ts
This should reduce by x2 the number of proposals to make a pythnet/pythtest proposal.
> [xc-admin] batch wormhole messages

- governance/xc_admin/packages/xc_admin_common/src/propose.ts
Send transactions to phantom in batches of 30
> [xc-admin] Batch transactions

- governance/xc_admin/packages/xc_admin_common/src/propose.ts
If there are more than 255 multisig instructions. More than 1 proposal will be created.
> [xc-admin] Create multiple proposals if too many instructions

- third_party/pyth/p2w_autoattest.py
- wormhole_attester/client/src/attestation_cfg.rs
- wormhole_attester/client/src/lib.rs
- wormhole_attester/client/src/main.rs
- wormhole_attester/client/tests/test_attest.rs
- wormhole_attester/program/src/attest.rs
- wormhole_attester/program/src/attestation_state.rs
- wormhole_attester/program/src/error.rs
- wormhole_attester/program/src/lib.rs
This new value is bumped on chain with each new attestation, on a per-symbol basis. The timestamp is common for  all cranks. This enables attester cranks to rate limit their attestations of a symbol together with all other attesters. Ultimately, our tx expenses  should drop while still fulfilling our preferred attestation rates.
The rate-limiting works by letting clients specify a desired rate limiting interval in instruction args. If all of the batch's symbols were already attested up to that amount of time ago, the TX fails and no SOL is spent. Note: this rate limit may be reached because of a different attester working in parallel with the client that sees this soft error. The rate limiting error does not contribute to metrics nor healthcheck.
* Comments and naming - This feature is …
> attester: Add an on-chain last attestation timestamp and rate limit arg

- wormhole_attester/Cargo.lock
- wormhole_attester/client/Cargo.toml
- wormhole_attester/client/src/util.rs
Previously, we used 307 Internal Redirect to tell k8s that we're still waiting for the healthcheck window to fill up. Unfortunately, k8s assumes 3XX as a success, which wrongly tells it that the service is ready. Changing to 503 causes the expected probe failure to appear when the healthcheck state is not yet determined.
This change is a hotfix for attester client 4.0.0 and bumps the version to 4.1.0
> wormhole_attester client: Change "not enough data" HTTP code to 503

- README.md
writing down some common errors for future reference
> Add lerna documentation to readme

- target_chains/ethereum/sdk/js/package.json
- target_chains/ethereum/sdk/js/src/examples/EvmBenchmark.ts
This example uses the get_vaa endpoint and passes the result to parsePriceFeedUpdates. I validated that this works locally.
> Add an example script for benchmarks

- package-lock.json
- price_pusher/package.json
- price_pusher/src/controller.ts
- price_pusher/src/evm/evm.ts
This PR tries to solve a bug that was reported by one of the consumers. The bug was that the code was crashing on revert and the service didn't handle it well (it was a different message). Because of this bug there was another bug that the service was sending a transaction again and again because of the restart.
This PR updates the error handling to capture all messages containing "revert" and also waits for cooldown seconds before starting to push.
Also, some peoples reported that due to bad RPC they got error on the step that gets the `updateFee` and for some reason the error message was not caught (as this was not handled). This PR solves that too.
> [price-pusher] Bug fix on revert and crash

- Tiltfile
- third_party/pyth/p2w_autoattest.py
- wormhole_attester/Cargo.lock
- wormhole_attester/client/Cargo.toml
- wormhole_attester/client/src/attestation_cfg.rs
- wormhole_attester/client/src/batch_state.rs
- wormhole_attester/client/src/main.rs
- wormhole_attester/client/src/util.rs
- Tiltfile: TILT_DOCKER_REGISTRY def behavior, re-add namespace_create
This helped me with k8s setup details that caused me issues locally:
* The unspecified registry would make tilt fail to start by default
* In minikube/k3s/<your development cluster> use cases, recreating the cluster may confuse Tilt because it doesn't create the desired namespace by default. It looks like tilt is starting but short after all services show that it cannot find the namespace.
-  wormhole_attester/client v5.0.0: accuracy and logging opimisations
* [BREAKING CHANGE] min_interval_secs switches to milliseconds under
min_interval_ms
* attestation jobs no longer use preflight checks - this includes a
custom variant of send_and_confirm_transaction(), see util.rs for details
* attestation error logging no longer …
> [wormhole-attester] Increase accuracy and improve logging

- governance/xc_admin/packages/crank_pythnet_relayer/src/index.ts
Right now it fails when all the VAAs have already been relayed, I want it to succeed instead
> [crank-pythnet-relayer] Don't throw error if all VAAs were relayed

- governance/xc_admin/packages/xc_admin_frontend/hooks/useMultisig.ts
Proposals would get refreshed when u connect disconnect your wallet. I refactored squads into `readonlySquads` and `squads` so that this behavior doesn't happen.
> [xc-admin-frontend] Stop reloading proposals when you connect a wallet

- .gitignore
- package-lock.json
- price_pusher/README.md
- price_pusher/config.evm.testnet.sample.json
- price_pusher/docker-compose.testnet.sample.yaml
- price_pusher/package.json
- price_pusher/src/controller.ts
- price_pusher/src/evm/command.ts
- price_pusher/src/evm/custom-gas-station.ts
- price_pusher/src/evm/evm.ts
- price_pusher/src/injective/command.ts
- price_pusher/src/options.ts
This PR changes the EVM pusher to rely on the account nonce to increase reliability and cost-efficiency of the pusher.
On EVM networks nonce is the transaction index of the user transaction. it increments 1 by 1 and you cannot send two transactions with the same nonce; if there are multiple transactions with the same nonce only one gets chosen on-chain.
Sometimes our transactions do not land on chain because the gas is lower than the necessary amount to be included on-chain. By setting nonce manually we can replace the older transaction with a higher gas to increase  likelihood of the price landing on-chain without paying any extra cost. The `override-gas-price-multiplier` option with the default of 1.1 is added to handle this situation. Also we can try updating the prices on a faster …
> [price-pusher] Add nonce for evm + refactor

- price_pusher/package.json
- price_pusher/src/injective/injective.ts
Prev we were passing hardcoded gas due to which transactions were failing as it was not enough
Simulating transaction to calculate it.
> [price-pusher] Simulate injective tx

- .github/workflows/publish-js.yml
this is failing because it's trying to publish private packages. chatGPT says this option fixes it, so let's find out.
> [js] Fix JS publish workflow harder

- governance/xc_admin/packages/xc_admin_common/src/deterministic_oracle_accounts.ts
- governance/xc_admin/packages/xc_admin_common/src/multisig.ts
- governance/xc_admin/packages/xc_admin_common/src/propose.ts
- governance/xc_admin/packages/xc_admin_frontend/components/PermissionDepermissionKey.tsx
- governance/xc_admin/packages/xc_admin_frontend/components/tabs/General.tsx
- governance/xc_admin/packages/xc_admin_frontend/components/tabs/Proposals.tsx
- governance/xc_admin/packages/xc_admin_frontend/components/tabs/UpdatePermissions.tsx
- governance/xc_admin/packages/xc_admin_frontend/hooks/useMultisig.ts
- package-lock.json
I need this PR because the logic in `propose.ts` was wrong since it was hardcoded to use the price feeds ops key.
Now that the upgrade multisig has a different ops key we need to fix that.
- `OPS_KEY` becomes `PRICE_FEED_OPS_KEY` 
- `UPGRADE_OPS_KEY` introduced
- `UPGRADE_MULTISIG` and `PRICE_FEED_MULTISIG` moved to `xc-admin-common`
- `getOpsKey` gives you the right ops key for each multisig
> [xc-admin] Introduce the new UPGRADE_OPS_KEY

- price_pusher/Dockerfile
The package name was changed in a recent change and broke the dockerfile. This PR fixes it.
> [price-pusher] Update Dockerfile

- wormhole_attester/Cargo.lock
- wormhole_attester/program/Cargo.toml
- wormhole_attester/program/src/attest.rs
With the current logic, we attest every second and have different attestation times. However, users use price publish time and we need to perform the logic on the publish time. This PR fixes this issue. 
We need to deploy our contracts after this change. Since only the internal logic has changes, we don't need to touch attesters.
> [wormhole-attester] Fix rate_limit logic

- README.md
- price_pusher/package.json
- price_service/client/js/package.json
- price_service/sdk/js/package.json
- target_chains/aptos/sdk/js/package.json
- target_chains/cosmwasm/sdk/js/package.json
- target_chains/ethereum/sdk/js/package.json
I'm still trying to get the publish workflow to work. apparently if you don't set this option, lerna defaults to publishing the packages as non-public (which fails because we don't pay for it)
> [js] Fix JS workflow

- .pre-commit-config.yaml
- target_chains/solana/cli/src/cli.rs
- target_chains/solana/cli/src/main.rs
- target_chains/solana/programs/solana-receiver/src/lib.rs
- target_chains/solana/programs/solana-receiver/src/state.rs
- target_chains/solana/programs/solana-receiver/src/tests/simulator.rs
- target_chains/solana/programs/solana-receiver/src/tests/test_update_price.rs
And run it to format the files. Formatting changes only aside from `pre-commit-config`
> [solana] Add pre-commit for solana target chain contract

- target_chains/ethereum/contracts/forge-test/GasUsageExperiments.t.sol
- target_chains/ethereum/contracts/forge-test/VerificationExperiments.t.sol
We wanted to benchmark the gas usage of different ways of verifying prices in the ethereum contract. I tried out a bunch of different things and here's what I get:
| Update Type                                   | Gas Cost |
| --------------------------------------------- | ------- |
| Native update (use tx signature of 1 price update)   | 48k     |
| Threshold update (sign 1 price update directly)                              | 54.5k   |
| Threshold update for 1 price w/ 8-deep merkle tree         | 58k     |
| WH update for 1 price w/ 8-deep merkle tree                | 201k    |
| WH batch update w/ 5 prices                    | 222k    |
The two things that I think are worth pointing out are:
1. The merkle tree doesn't add that much overhead over the native update, which represents …
> Gas usage experiments

- governance/multisig_wh_message_builder/src/index.ts
- governance/xc_admin/packages/xc_admin_cli/src/index.ts
- governance/xc_admin/packages/xc_admin_common/src/propose.ts
Add support for arbitrary wormhole payloads to `xc_admin_cli`
Remove feature from `multisig_wh_message_builder` since we're deprecating it.
> [xc-admin] Add support for arbitrary wormhole payloads

- price_service/client/js/src/PriceServiceConnection.ts
- price_service/server/src/listen.ts
- price_service/server/src/rest.ts
- tilt_devnet/docker_images/Dockerfile.lerna
This PR adds an endpoint that's the equivalent of get_vaa (so price id & publish time), but that returns the parsed price feed data. All of the other methods have both vaa & price feed options except this one, so this makes the API uniform.
> Get price feed endpoint

- price_service/server/package.json
- price_service/server/src/__tests__/rest.test.ts
- price_service/server/src/encoding.ts
- price_service/server/src/helpers.ts
- price_service/server/src/rest.ts
We get a lot of questions about how to convert the base64 VAAs into hex and whatnot. This PR adds an "encoding" parameter to all of the endpoints that return a VAA which lets you pick the thing you want. 
Note that I added a "0x" option which is hex, but with a 0x prepended. The EVM APIs seem to need this in various places.
**UPDATE**
I changed my mind about how this should work. The encoding parameter is itself hard for people to figure out, so I replaced it with a `target_chain` argument which is self-explanatory. The server will map the target chains to the desired encoding.
> [price_service] Let callers specify VAA encoding

- governance/xc_admin/packages/xc_admin_frontend/components/tabs/General.tsx
Deleting a product doesn't display the symbol in the modal. This fixes it.
> [xc-admin] Fix modal for delete product

- hermes/Cargo.lock
- hermes/Cargo.toml
- hermes/src/macros.rs
- hermes/src/main.rs
- hermes/src/network/rpc.rs
- hermes/src/network/rpc/rest.rs
Add many of the price service apis. Per David suggestion, we do validation in parsing instead of doing it later. I didn't find any suitable library to deserialize our hex format so I created a macro to implement it because we use it in a couple of places. I tried making a generic HexInput but couldn't make it working (and I need other crates like generic_array for it which makes the code more complex)
> [hermes] Add more rest api methods

- hermes/src/network/rpc.rs
- hermes/src/network/rpc/rest.rs
- hermes/src/store.rs
- hermes/src/store/proof/batch_vaa.rs
- hermes/src/store/storage.rs
- hermes/src/store/storage/local_cache.rs
This change touches many of our abstractions and I like to know your opinion on how we can do it better. Essentially we won't have a single way (across accumulation ways) to say what are the price ids and the solution seems to be taking the union of all accumulation states. The reason is that the prices are derived from the accumulations not the other way. 
This PR also adds a CcipUpdateNotFound error to handle the special status code situation.
> [hermes] add get price feed ids + refactor

- hermes/src/network/rpc.rs
- hermes/src/network/rpc/rest.rs
- hermes/src/network/rpc/rpc_price_feed.rs
- hermes/src/store.rs
- hermes/src/store/proof/batch_vaa.rs
- hermes/src/store/storage.rs
This change adds verbose and binary option to latest_price_feeds endpoint. Unfortunately it exposes many internal information which required touching different components to expose batch_vaa specific information. The code is now coupled to batch_vaa and we need to refactor it when we add other proof types (and eventually remove it when it get deprecated).
> [hermes] Improve latest feeds rest api

- accumulator_updater/programs/accumulator_updater/Cargo.toml
- accumulator_updater/programs/accumulator_updater/src/instructions/put_all.rs
- accumulator_updater/programs/accumulator_updater/src/lib.rs
- accumulator_updater/programs/accumulator_updater/src/macros.rs
- accumulator_updater/programs/accumulator_updater/src/state/accumulator_input.rs
- accumulator_updater/programs/mock-cpi-caller/src/instructions/add_price.rs
- accumulator_updater/programs/mock-cpi-caller/src/instructions/update_price.rs
- accumulator_updater/programs/mock-cpi-caller/src/lib.rs
- accumulator_updater/programs/mock-cpi-caller/src/message/price.rs
- accumulator_updater/tests/accumulator_updater.ts
Write all schemas/messages for an account into one PDA
- update `AccumulatorInput` and related structs to `zero_copy`
- add `InputIndex` for indexing into `AccumulatorInput.data`
- funding account
- realloc (need wrapper struct in increments of 10240 bytes?)
> [accumulator-updater 5/x] Single PDA

- accumulator_updater/programs/accumulator_updater/src/instructions/put_all.rs
- accumulator_updater/programs/accumulator_updater/src/lib.rs
- accumulator_updater/programs/accumulator_updater/src/state/accumulator_input.rs
- accumulator_updater/programs/mock-cpi-caller/src/instructions/add_price.rs
- accumulator_updater/programs/mock-cpi-caller/src/instructions/update_price.rs
- accumulator_updater/tests/accumulator_updater.ts
Add a `SystemAccount` that will be used as the payer for all `AccumulatorInput` account creation
- add `fund` account to `put_all` ix and list of accounts passed from `mock_cpi_caller`
> [accumulator-updater 6/x] Funding account

- hermes/src/config.rs
- hermes/src/main.rs
- hermes/src/network/p2p.go
- hermes/src/network/p2p.rs
Change the p2p module to accept values for the Wormhole parameters.
First commit is just running gofmt (no changes to code).
> [hermes] Pass Wormhole arguments from command line or env. vars

- price_pusher/README.md
Some people on telegram were running npm install from the price_pusher folder and it was failing.
> Improve README

- .pre-commit-config.yaml
- message_buffer/programs/message_buffer/src/instructions/create_buffer.rs
- message_buffer/programs/message_buffer/src/instructions/delete_buffer.rs
- message_buffer/programs/message_buffer/src/instructions/mod.rs
- message_buffer/programs/message_buffer/src/instructions/put_all.rs
- message_buffer/programs/message_buffer/src/instructions/resize_buffer.rs
- message_buffer/programs/message_buffer/src/lib.rs
- message_buffer/programs/message_buffer/src/macros.rs
- message_buffer/programs/message_buffer/src/state/message_buffer.rs
- message_buffer/programs/message_buffer/src/state/whitelist.rs
- message_buffer/programs/mock-cpi-caller/src/instructions/add_price.rs
- message_buffer/programs/mock-cpi-caller/src/instructions/update_price.rs
- message_buffer/tests/message_buffer.ts
Add `create/resize/delete_buffer` ixs, allow for `MessageBuffer` to be variable length
- Remove `fund`
- Rename `whitelist.authority` to `whitelist.admin` and check that admin is signer & payer for all admin ixs.
- `MessageBuffer` struct now only defines the header fields and allows for variable length for the actual messages (see `MessageBuffer::put_all_in_buffer`)
> [message-buffer 10/X] - Message Buffer Admin IXs & variable length

- price_pusher/config.evm.testnet.sample.json
- price_pusher/docker-compose.testnet.sample.yaml
This docker compose was crashing. The bug was really hard to find.
Basically the pusher fails if the argument `--config` doesn't end in `.json`
In this docker compose it was running with `--config /command_config`.
I'm reverting this docker compose to look like the one for mainnet.
> [xc-pusher] Fix docker compose (testnet)

- message_buffer/Cargo.lock
- message_buffer/programs/message_buffer/Cargo.toml
- message_buffer/programs/message_buffer/src/instructions/create_buffer.rs
- message_buffer/programs/message_buffer/src/instructions/delete_buffer.rs
- message_buffer/programs/message_buffer/src/instructions/mod.rs
- message_buffer/programs/message_buffer/src/instructions/put_all.rs
- message_buffer/programs/message_buffer/src/instructions/resize_buffer.rs
- message_buffer/programs/message_buffer/src/state/message_buffer.rs
Add new unit test for reading with cursor, update test setup
Addresses feedback from #779
> fix(message-buffer): address PR feedback from 779, update tests

- package-lock.json
- price_pusher/package.json
- price_service/client/js/package.json
- target_chains/aptos/sdk/js/package.json
- target_chains/cosmwasm/sdk/js/package.json
- target_chains/ethereum/sdk/js/package.json
This bug was found by Brett from telegram. Basically EvmConnection wasn't working in a React app because of some axios weirdness.
Minimal example here : 
https://github.com/guibescos/test-connection
I want to make this change and make a release ASAP.
> [Price pusher client] Fix axios bug by downgrading, bump all dependents

- package-lock.json
- price_service/client/js/package.json
Turns out `"axios": "^1.1.0"` is not enough since it ends up resolving to `1.3.4`....
I needed to pin to 1.1.0  (`"axios": "=1.1.0"`) to solve the problem. I also had to downgrade `axios-retry` to be compatible.
reference : https://github.com/axios/axios/issues/5082
> [price-service-client] Pin axios

- .github/workflows/publish-js.yml
This PR aims to resolve the following problem. 
The way the script currently works is it only builds the packages it aims to publish. However if your package depends on another package that's not being published, the whole thing will fail because that other package hasn't been built. 
https://github.com/pyth-network/pyth-crosschain/actions/runs/4852553452/jobs/8647678135
in this job after a bugfix to `price-service-client` publish `price-service-client` failed because we're not publishing `price-service-sdk`.
There are two solutions :
- Build all the packages at the beginning of the workflow (this PR)
- Make sure to bump all packages every time we make a new release.
> [js-packages] Build all packages before publishing

- price_pusher/config.injective.testnet.sample.json
- price_pusher/package.json
- price_pusher/src/injective/command.ts
Transactions are signed with different chainId on testnet and mainnet. 
It was using the the same for both which caused this bug. 
This PR fixes that.
> Fix Bug - price pusher was not pushing to mainnet

- price_service/server/docker-compose.mainnet.yaml
- price_service/server/docker-compose.testnet.yaml
Added restart `on-failure` to docker-compose mainnet/testnet of price feed server. Price feed server will automatically recover in case of unexpected error.
> docker: add restart `on-failure`

- target_chains/ethereum/sdk/solidity/MockPyth.sol
- target_chains/sui/contracts/sources/pyth.move
The function alluded in this comment, that can be used to create mock pyth payloads was erroneously mentioned.
> [evm] Make comment match the function below

- pythnet/message_buffer/programs/message_buffer/src/instructions/create_buffer.rs
- pythnet/message_buffer/programs/message_buffer/src/instructions/delete_buffer.rs
- pythnet/message_buffer/programs/message_buffer/src/instructions/resize_buffer.rs
- pythnet/message_buffer/programs/message_buffer/src/lib.rs
- pythnet/message_buffer/programs/mock-cpi-caller/tests/cases/test_create_buffer.rs
- pythnet/message_buffer/programs/mock-cpi-caller/tests/cases/test_initialize.rs
- pythnet/message_buffer/programs/mock-cpi-caller/tests/cases/test_resize_buffer.rs
- pythnet/message_buffer/programs/mock-cpi-caller/tests/cases/test_set_allowed_programs.rs
- pythnet/message_buffer/programs/mock-cpi-caller/tests/program_test/mod.rs
- pythnet/message_buffer/scripts/setup_message_buffer.ts
- pythnet/message_buffer/tests/message_buffer.ts
add payer to all contexts requiring lamports for rent separate from admin
Note - this should still work in the case that `admin` & `payer` are the same
> [message-buffer 17/x] separate payer from admin

- .github/workflows/publish-pyth-sdk-cw.yml
we moved this and never fixed the publish workflow
> Fix path to CW sdk

- .pre-commit-config.yaml
- pythnet/pythnet_sdk/examples/generate_pyth_data.rs
- pythnet/pythnet_sdk/src/accumulators/merkle.rs
This PR is to help Hermes, it changes the message format serialized by the validator to include the slot and ring size instead of the ring index. This is because hermes ideally would be able to associate accumulators with a slot, the current ring index can simply be calculated as `slot % ring_size` when needed. This adds a small amount of overhead to messages of 64 gas. The serialize function added to MerklePath is also for Hermes.
This PR also fixes clippy/rustfmt pre-commit hooks so there's a little noise.
> [pythnet] Update serialization for MerkelPath/MerkleAccumulator

- governance/xc_admin/packages/xc_admin_frontend/components/PermissionDepermissionKey.tsx
- governance/xc_admin/packages/xc_admin_frontend/components/tabs/General.tsx
- governance/xc_admin/packages/xc_admin_frontend/package.json
- governance/xc_admin/packages/xc_admin_frontend/pages/index.tsx
Make xc-admin-frontend send the proposal instructions to the proposer server, that will submit them to the multisig.
You can test it locally by setting `NEXT_PUBLIC_PROPOSER_SERVER_URL` to the right value.
I tried to keep this one small, might be able to cleanup further once it gets approved and we make sure it works.
> [Xc admin] frontend to use server

- pythnet/message_buffer/Anchor.toml
- pythnet/message_buffer/package.json
- pythnet/message_buffer/programs/message_buffer/src/lib.rs
- pythnet/message_buffer/scripts/.env.integration
- pythnet/message_buffer/scripts/.env.local
- pythnet/message_buffer/scripts/.env.pythtest
- pythnet/message_buffer/scripts/.env.template
- pythnet/message_buffer/scripts/setup_message_buffer.ts
- pythnet/message_buffer/yarn.lock
- pythnet/pythnet_sdk/src/lib.rs
-  add init msg buffer pda to script
- add `.env` files 
-  fix msg buffer programId
> [message-buffer & pythnet_sdk] - init msg buffer pda script, fix msg buffer programId

- governance/xc_admin/packages/xc_admin_frontend/components/tabs/General.tsx
Loled at this
Switching to proposer server has unearthed this old bug that had been here all along
> [xc-admin-frontend] Fix race condition once and for all

- .github/workflows/pre-commit.yml
- .pre-commit-config.yaml
Use a fixed nightly version to avoid random surprises!
> [ci] Fix pre-commit

- governance/xc_admin/packages/xc_admin_cli/src/index.ts
- pythnet/pythnet_sdk/src/accumulators/merkle.rs
Adds an extra struct MerkleRoot that is just a tuple struct that wraps the actual root as a hash.
This struct is exported and is useful to check proofs when you don't have access to the element set of the tree.
> [pythnet-sdk] Add merkleRoot

- pythnet/pythnet_sdk/src/accumulators/merkle.rs
- pythnet/pythnet_sdk/src/wire.rs
The Merkle implementation in PythNet SDK has been tied heavily to the Accumulator interface, this generalizes the interface out a bit into all the functionality required to work with just a MerkleTree (which happens to implement the Accumulator interface) in such a way it can be used for other PythNet tasks.
> [pythnet-sdk] Expose MerkleTree

- pythnet/pythnet_sdk/src/accumulators/merkle.rs
- pythnet/pythnet_sdk/src/hashers.rs
This allows getting the byte representation of a MerkleRoot/MerklePath. The MerkleRoot is a transparent as_bytes(), for MerklePath we don't have a byte slice representation so we provide to_bytes() - note that this implies a serialization format but It's a reasonable one, where it simply returns `Component_1 || Component_2 || ... || Component_n`. A `Serialize` trait exists on the type for other serialization choices, the byte methods are merely meant to be the easiest reasonable compact representations for the merkle components. Additionally, this applies BorshSerialize/Deserialize to the remaining types for full coverage for Anchor usage.
> [pythnet-sdk] Allow as_bytes()/to_bytes() for MerkleRoot/MerklePath

- hermes/src/network/p2p.go
- hermes/src/store/proof/wormhole_merkle.rs
Adding this to provide performance profiling to the Go portion of hermes. This exposes pprof on port 6060.
> [hermes] Add go profiling

- price_service/server/package.json
- price_service/server/src/rest.ts
Although we have added the staleness check, there is a case that spy never connects to price service and it causes the liveness to return OK whereas it has no price feeds. This PR adds a check for a min price feed number in the liveness. 
This is not ideal that we are adding constants in the liveness and ideally they should be configurable, but as this service is going to sunset in favor of hermes it's fine. We should have a better liveness and readiness metric on hermes.
> [price-service] Add minSymbols check to liveness

- target_chains/ethereum/contracts/contracts/pyth/Pyth.sol
- target_chains/ethereum/contracts/contracts/pyth/PythAccumulator.sol
- target_chains/ethereum/contracts/forge-test/GasBenchmark.t.sol
- target_chains/ethereum/contracts/forge-test/Pyth.WormholeMerkleAccumulator.t.sol
- target_chains/ethereum/contracts/forge-test/utils/PythTestUtils.t.sol
- target_chains/ethereum/contracts/foundry.toml
- change `getUpdateFee` to calculate the total fee based on the numUpdates for accumulator updates. Still uses same logic for batch price
- lowers optimizer_runs to 2000 in order to get the bytesize down
- optimizer_runs = 5000 had deployment size of 25046
diff between optimizer_runs = 2000 + this branch and main
- `getUpdateFeeWhMerkleX` is high b/c the original implementation returned singleUpdateFee * updateData.length
- Will make separate PR for optimizing bytesize further and increasing optimizer_runs to get as close to original 5000 runs
> [ethereum] - charge updateFee per number of updates

- hermes/Cargo.lock
- hermes/Cargo.toml
- hermes/src/network/p2p.go
- hermes/src/network/p2p.rs
@thmzlt identified a memory leak in our edge deployment. @Reisen and I worked on investigating it. We had an initial suspicion about libp2p because price service also apparently has a memory leak. Because of that in #876 we added go profiler to hermes. However, after more investigations, we realized that in price-service the node part has a leak and then  it is probably not the libp2p and it's our code.
@Reisen suggested using [heaptrack](https://github.com/KDE/heaptrack) to profile the heap and I created a separate image with heaptrack and deployed it in the cluster. Using `heaptrack_print` (the cli tool) we can get the peak memory usages and after analyzing the logs over time I realized that the memory usages of this part of the code is increasing:
```
PEAK MEMORY CONSUMERS
86.58MB peak …
```
> [hermes] Fix memory leak

- target_chains/ethereum/contracts/forge-test/Pyth.WormholeMerkleAccumulator.t.sol
- target_chains/ethereum/contracts/forge-test/utils/PythTestUtils.t.sol
- add tests for checking forward compatibility in `parsePriceFeedUpdates` & `updatePriceFeeds`
> [eth]: add forward compatibility test for accumulator updateData

- target_chains/ethereum/contracts/contracts/libraries/MerkleTree.sol
- target_chains/ethereum/contracts/contracts/libraries/external/UnsafeCalldataBytesLib.sol
- target_chains/ethereum/contracts/contracts/pyth/Pyth.sol
- target_chains/ethereum/contracts/contracts/pyth/PythAccumulator.sol
- changed parameter type from `bytes calldata` to `bytes memory` for some functions
- changed `parsePriceFeedMessage` to use offset instead of making a slice/copy
Before
After
After @ali-bahjati change in #888
> [eth] more update/parsePriceFeed optimizations

- governance/xc_admin/packages/xc_admin_cli/package.json
- governance/xc_admin/packages/xc_admin_cli/src/cli.ts
- governance/xc_admin/packages/xc_admin_common/package.json
- governance/xc_admin/packages/xc_admin_common/src/contracts/Contract.ts
- governance/xc_admin/packages/xc_admin_common/src/contracts/EvmPythUpgradable.ts
- governance/xc_admin/packages/xc_admin_common/src/contracts/EvmWormholeReceiver.ts
- governance/xc_admin/packages/xc_admin_common/src/contracts/cli.ts
- governance/xc_admin/packages/xc_admin_common/src/contracts/config.ts
- governance/xc_admin/packages/xc_admin_common/src/contracts/index.ts
- governance/xc_admin/packages/xc_admin_common/src/index.ts
- governance/xc_admin/packages/xc_admin_frontend/next.config.js
- target_chains/cosmwasm/tools/src/deployer/injective.ts
- target_chains/cosmwasm/tools/src/deployer/terra.ts
I've been experimenting with different ways to read / write the state of contracts, and I have an approach that seems reasonable. The idea is to make a collection of Contract objects, each of which represents a single deployed on-chain contract. There can be separate types of Contracts to represent different types of programs (target chain vs. oracle program vs. ...). Each contract exposes its state as a json object which can be both read & written. You can then update contract state by manipulating the JSON object and calling the write method. The JSON interface makes this approach very flexible, as we can change its schema to fit whatever kind of contract we have.
Writing the state back to the chain is a little complicated because we need to run operations that pause and wait for …
> [xc-admin] Contract management tool

- price_service/server/package.json
- price_service/server/src/listen.ts
- price_service/server/src/rest.ts
I have made some changes to the liveness that should also be in readiness too. This also refactors and explains the rationale behind those. Liveness is stricter than readiness but some people might use readiness as health check in other infrastructures so it's good to update it.
> [price-service] Update readiness probe

- price_pusher/README.md
- price_pusher/price-config.mainnet.sample.yaml
- price_pusher/price-config.testnet.sample.yaml
- price_pusher/src/controller.ts
- price_pusher/src/evm/command.ts
- price_pusher/src/evm/evm.ts
- price_pusher/src/price-config.ts
I was looking at the sui pusher's txs and I noticed that it currently only updates a subset of the price feeds in the pushed VAA. This behavior is an interaction between the structure of the sui contract (with the hot potato etc) and the price pusher.
I'm fixing this problem by adding a feature we'll want anyway, which is to piggyback additional price updates on to a push. With accumulators, it's very cheap to add an additional update to an existing price push, so we'll want to take advantage of this by pushing more feeds than just the ones that met the triggering conditions.
This PR adds an extra set of triggering conditions for an early update. If at least one feed meets the normal triggering conditions, we'll push a batch of updates that includes the original update + all feeds meeting …
> Update price feeds early if part of a batch

- target_chains/cosmwasm/README.md
- target_chains/cosmwasm/contracts/pyth/src/contract.rs
- target_chains/cosmwasm/sdk/rust/src/lib.rs
- target_chains/cosmwasm/tools/src/build-contract.ts
This PR separates the parsing logic for applying updates logic so that the former can be used independently for parse_price_feed messages.
Parsing functions do not need `DepsMut` and they have been changed to use a `Deps` dependency instead.
> Cosmwasm refactor and preparation for parse price feeds

- target_chains/ethereum/contracts/forge-test/Pyth.WormholeMerkleAccumulator.t.sol
The structure of the fake payload was not as expected. Some tests were failing for the wrong reason but with the right error code.
> Add slot variable in constructing fake wormhole payloads

- hermes/Cargo.lock
- hermes/Cargo.toml
- hermes/src/api/types.rs
- hermes/src/api/ws.rs
- hermes/src/store.rs
- hermes/src/store/storage.rs
- hermes/src/store/storage/local_storage.rs
- pythnet/pythnet_sdk/Cargo.toml
- pythnet/pythnet_sdk/src/messages.rs
- target_chains/cosmwasm/Cargo.lock
- target_chains/cosmwasm/contracts/pyth/src/contract.rs
This PR adds some tests to the local storage to make sure it works fine. During the testing I realized that moka's Cache is not working as we expect it to work (it doesn't evict items as we want to) so we removed it and instead adopted a simple queue (or BTreeMap). We might replace it with a more efficient implementation in the future but will do in separate PRs (if needed). 
Also, I added a new type alias of `FeedId` in the Message struct and renamed `id` to `feed_id` in pythnet_sdk to make the id more clear.  I bumped version to 2.0.0 to get away from solana versioning and have proper version control on this crate. Lastly, updated the cosmwasm contract with this breaking change.
> [hermes] Add storage tests + refactor

- hermes/src/network/pythnet.rs
- hermes/src/store.rs
- hermes/src/store/proof/wormhole_merkle.rs
- hermes/src/store/storage.rs
- hermes/src/store/storage/local_storage.rs
- hermes/src/store/types.rs
In hermes we used to deserialize raw_messages and store only the messages. In the old approach we serialized the messages again once we wanted to construct the proofs and that was not future compatible. This PR changes the codebase to store raw_messages instead of messages (and in some places it stores both).
> [hermes] Use raw_message for future-compatibility

- governance/xc_governance_sdk_js/src/index.ts
- governance/xc_governance_sdk_js/src/instructions.ts
- target_chains/ethereum/contracts/contracts/pyth/PythGovernance.sol
- target_chains/ethereum/contracts/contracts/pyth/PythGovernanceInstructions.sol
- target_chains/ethereum/contracts/hardhat.config.ts
- target_chains/ethereum/contracts/test/pyth.js
- target_chains/ethereum/contracts/truffle-config.js
- target_chains/ethereum/sdk/solidity/PythErrors.sol
- target_chains/ethereum/sdk/solidity/abis/PythErrors.json
This PR adds a new governance message to update wormhole address that is used in Pyth. This will allow us to change the Wormhole that Pyth uses to a gas optimized version of it developed in the PR #901. Per @jayantk suggestion, I added some sanity checks to make sure that the new Wormhole contract works properly and reject otherwise.  
I added the tests to the js test suite because the rest of governance messages are tested there. To test you can either use tilt to do that automatically or manually run ganache-cli as a blockchain instance and test it. To do the latter, do the following:
1. Run `npx ganache-cli -e 10000 --deterministic --time="1970-01-02T00:00:00+00:00" --host=0.0.0.0` on a separate terminal to spawn a new network.
2. Run `cp .env.test .env && npx truffle compile --all && …
> [eth] Add setWormholeAddress governance message

- target_chains/cosmwasm/contracts/pyth/src/contract.rs
SDK now allows minor version updates, so the test was not failing anymore as expected
> Fix test by increasing major version instead of minor version

- price_pusher/README.md
- price_pusher/package.json
- price_pusher/src/sui/command.ts
- price_pusher/src/sui/sui.ts
This PR is a version of https://github.com/pyth-network/pyth-crosschain/pull/918 that fixes a couple minor issues and CI. The  jist of the change is to split the SUI coins owned by the wallet into multiple roughly-equal-size coins, then maintain a queue of those coins in the pusher. Each transaction uses the gas coin from the head of the queue, returning it once the tx is done. This approach allows the blockchain to properly parallelize the execution of multiple concurrent transactions.
> [price_pusher] Create gas pool for Sui

- price_pusher/package.json
- price_pusher/src/aptos/aptos.ts
- price_pusher/src/aptos/command.ts
The aptos pusher can't submit more than 1 transaction per 3 seconds. The problem seems to be that the submitted transactions don't land on chain, so the pusher tries to reuse an old sequence number, or simulation fails.
This change updates the pusher to fix this problem. It does three main things:
1. add local sequence number tracking and send each transaction with an incremented sequence number
2. remove the simulation / transaction replacement logic. The simulation RPC call fails often when you're submitting many transaction sequentially, presumably because the transaction is using the wrong blockchain state.
3. Stop using the update_if_necessary contract method, because we don't have a good way to track the "current" on-chain state as of when the tx is submitted.
> Update aptos pusher to support high TPS

- target_chains/cosmwasm/Cargo.lock
- target_chains/cosmwasm/sdk/rust/Cargo.toml
- target_chains/cosmwasm/sdk/rust/src/error.rs
The cosmwasm-std `StdError` struct has a feature-gated field `backtraces` that you forgot to fill. This breaks compilation for anyone who depends on the Pyth SDK and tries to enable the backtraces feature. This PR simply uses the `StdError::generic_err` instead of creating the struct literal so that you don't have create the backtrace yourself.
See this issue for more info: https://github.com/CosmWasm/cosmwasm/issues/1760
> fix: Use generic_err constructor instead of literal

- target_chains/sui/scripts/package.json
- target_chains/sui/scripts/pyth/create_all_price_feeds.ts
- target_chains/sui/scripts/pyth/create_price_feed.ts
- target_chains/sui/scripts/pyth/deploy.ts
- target_chains/sui/scripts/pyth/init_state.ts
- target_chains/sui/scripts/pyth/pyth_create_all_price_feeds.ts
- target_chains/sui/scripts/pyth/pyth_create_price_feed.ts
- target_chains/sui/scripts/pyth/pyth_deploy.ts
- target_chains/sui/scripts/pyth/pyth_init_state.ts
- target_chains/sui/scripts/pyth/pyth_update_price_feeds.ts
- target_chains/sui/scripts/pyth/update_price_feeds.ts
- target_chains/sui/scripts/utils/transfer_tokens.ts
- use official Mysten [sui.js](https://www.npmjs.com/package/@mysten/sui.js) lib in various Pyth TS scripts, including ones for deployment and contract initialization (previously there was a bug in the official package, so we had to fix it and use our own package)
> [sui 16/x] - update imports

- target_chains/ethereum/contracts/contracts/pyth/Pyth.sol
- target_chains/ethereum/contracts/contracts/wormhole-receiver/ReceiverMessages.sol
- target_chains/ethereum/contracts/package.json
This PR changes the contract version from `1.3.0-alpha` to `1.3.0` as the audits came out positive. There is a one liner change in Wormhole Receiver `parseAndVerifyVM` method to catch an error earlier that is suggested by the auditors.
> [eth] Finalize accumulator contract

- price_pusher/package.json
- price_pusher/src/sui/sui.ts
It seems like sui pusher's reliability problem is caused by the object versions of the gas coins in this code getting mismatched with the ones on-chain. This PR refreshes the version of the gas objects every time a transaction fails, which hopefully will fix the issue.
It's not easy to test this since it takes a long time to hit the error in the first place, but it should be safe to deploy this and see what happens. It's definitely not going to make things worse.
> [price_pusher] Refresh sui object versions

- governance/xc_admin/packages/xc_admin_frontend/components/InstructionViews/WormholeInstructionView.tsx
- governance/xc_admin/packages/xc_admin_frontend/components/tabs/Proposals.tsx
- governance/xc_admin/packages/xc_admin_frontend/contexts/PythContext.tsx
Bugfix on hook dependencies
Show target pyth program if available and unique and use that cluster to calculate product/account mappings:
Show approved/rejected count:
> [xc-admin-frontend] XC admin frontend fix part2

- governance/xc_admin/packages/xc_admin_frontend/components/common/CopyPubkey.tsx
> [xc-admin] break when key is too long

- governance/xc_admin/packages/xc_admin_frontend/components/tabs/Proposals.tsx
We only check for pyth oracle programs addresses not all pyth programs, the name was misleading
> [xc-admin-frontend] Rename title of pyth programs for clarification

- price_service/client/js/README.md
We've been planning to point users across all chains to the generic price service client. In particular, cosmwasm users don't have an ecosystem-specific SDK at the moment.
This PR adds docs to this client so that we can actually point people here.
> Add price service client readme

- .github/workflows/pre-commit.yml
- .pre-commit-config.yaml
- hermes/Dockerfile
- hermes/README.md
- hermes/rust-toolchain
The latest hermes version requires a feature that is not available on old nightly versions.
This PR also updates the readme running instructions. The readme is outdated and we need to update its content on a separate PR.
> fix(hermes): fix rust version

- hermes/Cargo.lock
- hermes/Cargo.toml
- hermes/build.rs
- hermes/src/api.rs
- hermes/src/api/rest.rs
- hermes/src/api/types.rs
This PR adds utoipa for API docs to the /docs route. I just added docs for one endpoint, and they're not 100% correct. It's actually a little finicky to get the specification right, so we'll have to mess around with it a bit to understand how it works better.
I also drive-by fixed build.rs to detect the current build target and compile the go binary for that architecture.
> [hermes] add utoipa for API docs

- hermes/README.md
- hermes/rust-toolchain
- hermes/src/api.rs
- hermes/src/api/rest.rs
- hermes/src/api/types.rs
This PR adds reasonable docs for the 1 method that is documented. Everything seems to work *except* the schemas for PriceId and Price, which are defined in a different crate so will need some special handling.
This was relatively painful to get working (I had to trial and error a bunch of stuff), but I think it's pretty repeatable at this point. We just have to copy paste the exact same macros over to the remaining API endpoints.
> [hermes] Add docs for 1 method

- hermes/Cargo.lock
- hermes/Cargo.toml
- hermes/src/api/ws.rs
Some WS clients were receiving "Abnormal Connection Closure" errors. Usually clients handle this without any problem but not all of them. This PR fixes the issue by sending specific close message upon receiving close message from client. I tested it using Postman (to produce the error and check the fix).
This PR also refactors the ws.rs code by making it simpler and using tokio::time::Interval instead of a manually implemented interval. Lastly, it updates the axum package to include newer patches.
> fix(hermes): send close message on WS closure

- hermes/Cargo.lock
- hermes/Cargo.toml
- hermes/src/api/ws.rs
The server response on hermes was "ok" instead of "success" on a correct request from client. We didn't catch it earlier because the client code only relied on whether it's error or not.
> fix(hermes): use compatible ws format as xc-server

- target_chains/ethereum/contracts/.gitignore
- target_chains/ethereum/contracts/README.md
- target_chains/ethereum/contracts/coverage.sh
- target_chains/ethereum/contracts/package.json
Add an npm helper to output the html coverage files via:
npm run coverage
This requires lcov and genhtml to be installed.
> chore(ethereum): add html coverage bits

- hermes/Cargo.lock
- hermes/Cargo.toml
- hermes/src/store/proof/wormhole_merkle.rs
Fix hermes construct_update_data to support generating update_data for more than 255 messages. This is very unlikely to happen in normal cases but the way WS <> store interact can cause this to happen when a WS client subscribes to all price feeds.
> fix(hermes): handle rare cases on update data

- price_service/server/package.json
- price_service/server/src/__tests__/rest.test.ts
- price_service/server/src/rest.ts
We are going to switch over to Hermes for our db and it will break the `get_price_feed` method which parses the update data. Some clients rely on the get_price_feed endpoint and after our data source migration from Price Service to Hermes they are going to break. This code adds the support for Accumulator messages to keep the API working.
Other alternatives:
- Asking protocols to switch to Hermes: We are not yet supporting the benchmarks data from Hermes and haven't decided whether we actually want to do it.
- Write hermes data in another database and keep the price service writer running: This is a possible solution but will require us to change all our usages of the cross-chain data table (in data_workflows, web-api, benchmarks) at some point and fragments the data (every user must be …
> feat(price-server): support parsing accumul data

- hermes/src/api.rs
- hermes/src/config.rs
- hermes/src/main.rs
- hermes/src/network/p2p.rs
- hermes/src/network/pythnet.rs
In some cases arguments are passed and accidentally renamed (like `api_addr -> rpc_addr`) or are unnecesarily converted (see `api_addr.to_string()` which is then parsed again with `api_addr.parse()`. In the future, we are likely to add many more arguments to Hermes as well, so this commit moves them into a separate struct which is then forwarded throughout the application instead which has the side effect of clearing some of these inconsistencies up as well.
The struct by default is cloned, but this only happens during launch of a hermes service components and can be passed by ref everywhere else so the cost doesn't matter.
As a drive by this makes an opinionated reformatting of attributes to reduce indentation (or increase it) for clarity. And moves logging to the sites they are most …
> refactor(hermes): pass run args as struct, add docstrings

- hermes/src/api/rest.rs
- hermes/src/api/rest/get_price_feed.rs
- hermes/src/api/rest/get_vaa.rs
- hermes/src/api/rest/get_vaa_ccip.rs
- hermes/src/api/rest/index.rs
- hermes/src/api/rest/latest_price_feeds.rs
- hermes/src/api/rest/latest_vaas.rs
- hermes/src/api/rest/live.rs
- hermes/src/api/rest/price_feed_ids.rs
- hermes/src/api/rest/ready.rs
Currently `rest.rs` contains all endpoints and will likely grow over time. This moves endpoints into their own submodules which makes it clearer which types are associated with each endpoint. As a drive by this also clears up the formatting of some of the comments and attributes, and minorly rewords a few comments to add markdown code blocks etc.
> refactor(hermes): move rpc endpoints into submodules

- target_chains/aptos/examples/fetch_btc_price/Move.toml
- target_chains/aptos/examples/mint_nft/Move.toml
After moving contracts to "target_chains" directory code for Aptos examples were not updated.
This PR updates Pyth dependency subdirs in these two examples.
> update Aptos examples Pyth dependency subdir

- price_pusher/package.json
- price_pusher/src/injective/injective.ts
account sequence mismatch error could happen in the simulation but the try catch did not cover that part
Verified the fix by manually incrementing the sequence number twice after each transaction so a refetch was necessary
> [price-pusher] Bugfix in handling account sequence mismatch in injective

- hermes/src/api.rs
- hermes/src/main.rs
- hermes/src/network/p2p.rs
- hermes/src/network/pythnet.rs
- hermes/src/store.rs
- hermes/src/store/storage.rs
This PR refactors hermes to have a cleaner shut down. It removes all sudden process exits and indicates to the current tasks they should shut down. This introduces about 1 second of shut down latency but allows for a clean exit. We currently have no tasks that corrupt from an abrupt shut down but this might not be true if we introduce stateful storage etc so adding it now will make it easier in future.
> refactor(hermes): clean exit

- target_chains/ethereum/contracts/contracts/pyth/Pyth.sol
- target_chains/ethereum/contracts/package.json
We have a deprecated `getUpdateFee` method that takes the size of updateData as argument and returns the price. We needed to keep it to keep backward compatibility. However, to keep it fully backward compatible we need to update its logic to always remain a over estimate of the actual cost.
> fix(eth): update legacy updateFee method pricing

- target_chains/ethereum/examples/oracle_swap/contract/src/OracleSwap.sol
Fixes a minor underflow comparison issue in `OracleSwap.sol` example
> fix: underflow issue

- hermes/README.md
The old readme contained many details about the future of Hermes which was not there and confused some people. Those details are now removed and the intro reflects what Hermes currently is.
> doc(hermes): update readme

- .github/workflows/pre-commit.yml
By default, pre-commit ci runs for all files which takes so long. This is because `extra_args` is `--all-files` by default. This pr changes the `extra_args` on PRs to make sure only the changes in the PR are checked.
> chore: improve precommit ci

- hermes/Cargo.lock
- hermes/Cargo.toml
- hermes/src/api.rs
- hermes/src/config.rs
- hermes/src/config/benchmarks.rs
- hermes/src/config/pythnet.rs
- hermes/src/config/rpc.rs
- hermes/src/config/wormhole.rs
- hermes/src/main.rs
- hermes/src/network/p2p.rs
- hermes/src/network/pythnet.rs
Since clap v3, structopt has been in maintenance mode. Structopt functionality was merged directly into clap, this PR moves us to clap v4,and refactors the current hermes configuration code while doing so, in particular:
- Breaks the configuration object into multiple modules.
- Cleans up argument defaults.
- Cleans up the command and argument documentation strings.
- Fixes the output to be over more lines for clarity (when `--help` not `-h`)
- Adds a new subcommand `show-env` that prints all configuration environment variables.
This renames some of the commands so this does break the current argument scheme. The changes in particular are just to make the commands a little more verbose/clear/consistent:
- `--pythnet-ws-endpoint` -> `--pythnet-ws-addr`
- `--pythnet-http-endpoint` -> …
> refactor(hermes): refactor configuration

- hermes/Cargo.lock
- hermes/Cargo.toml
- hermes/src/aggregate.rs
- hermes/src/api/rest.rs
- hermes/src/api/rest/get_price_feed.rs
- hermes/src/api/rest/get_vaa.rs
- hermes/src/api/rest/get_vaa_ccip.rs
- hermes/src/api/rest/latest_price_feeds.rs
- hermes/src/api/rest/latest_vaas.rs
- hermes/src/api/ws.rs
- hermes/src/state/benchmarks.rs
This check will make rejects faster (and block invalid requests to benchmarks). The other benefit is that we can log the errors from the get_price_feeds_with_update_data since it should not fail anymore.
> feat(hermes): Check price ids exist before each request

- target_chains/aptos/contracts/sources/pyth.move
Move the fee logic to the end of update flow, so we can use the update verification output for calculating how many updates were in the VAAs. This is a profile of what it used to look like before the optimization. As you can see almost all the gas cost is because of doing the wormhole verification logic three times.
> Optimize aptos contract to verify messages only once

- governance/xc_admin/packages/xc_admin_frontend/components/tabs/General.tsx
Users can now add a "symbol" field in the metadata in the JSON. This will change the symbol of the price feed.
> Allow changing the symbol

- hermes/Cargo.lock
- hermes/Cargo.toml
Forgot to bump this in previous PR.
> chore(hermes): bump to version 0.3.0, backwards incompatible CLI features

- hermes/Cargo.lock
- hermes/Cargo.toml
- hermes/src/state/cache.rs
Before this change, there was a lock for each message and it could cause the updateData for multiple ids have 2 updates (because of the race with the thread updating the states). This change adds a RwLock which makes sure that when the entire message state is updating, no one can read from it while allowing concurrent reads in other occasions.
> fix(hermes): add lock for the entire message state

- governance/xc_admin/packages/xc_admin_frontend/hooks/useMultisig.ts
There was a race condition where a thread (with the wrong parameters) would set some of these fields to the wrong value before it could be cancelled. Hopefully this fixes it.
> Fix the race condition by putting the setters at the end of the function

- hermes/Cargo.lock
- hermes/Cargo.toml
- hermes/src/api.rs
- hermes/src/api/ws.rs
- hermes/src/config/rpc.rs
Previously we were using ip address from connecting socket for rate limiting but it is often an internal IP in production environments (as the service is behind a load balancer or proxy). This PR uses ip inside headers (by default `X-Forwarded-For`) instead to make sure we get the actual requester ip.
> feat(hermes): use ip from request headers for ratelimiting

- target_chains/ethereum/contracts/contracts/pyth/Pyth.sol
- target_chains/ethereum/contracts/contracts/pyth/PythAccumulator.sol
- target_chains/ethereum/contracts/contracts/pyth/PythInternalStructs.sol
- target_chains/ethereum/contracts/forge-test/GasBenchmark.t.sol
- target_chains/ethereum/contracts/forge-test/Pyth.WormholeMerkleAccumulator.t.sol
- target_chains/ethereum/contracts/forge-test/utils/PythTestUtils.t.sol
- target_chains/ethereum/contracts/package.json
- target_chains/ethereum/sdk/solidity/AbstractPyth.sol
- target_chains/ethereum/sdk/solidity/IPyth.sol
- target_chains/ethereum/sdk/solidity/MockPyth.sol
- target_chains/ethereum/sdk/solidity/abis/AbstractPyth.json
- target_chains/ethereum/sdk/solidity/abis/IPyth.json
- target_chains/ethereum/sdk/solidity/abis/MockPyth.json
- target_chains/ethereum/sdk/solidity/package.json
Tried to reuse the logic as much as possible to limit additional bytecode.
After the changes the PythUpgradable bytecode is 24.22 KiB.
> Initial version of parsePriceFeed with uniqueness validation

- governance/xc_admin/packages/xc_admin_common/src/multisig_transaction/index.ts
- governance/xc_admin/packages/xc_admin_frontend/components/InstructionViews/WormholeInstructionView.tsx
- governance/xc_admin/packages/xc_admin_frontend/components/tabs/Proposals.tsx
Refactor so that we don't need to write this type of code : 
```
{parsedInstruction instanceof PythMultisigInstruction
? 'Pyth Oracle'
: parsedInstruction instanceof WormholeMultisigInstruction
? 'Wormhole'
: parsedInstruction instanceof
MessageBufferMultisigInstruction
? 'Message Buffer'
: parsedInstruction instanceof
SystemProgramMultisigInstruction
? 'System Program'
: parsedInstruction instanceof
BpfUpgradableLoaderInstruction
? 'BPF Upgradable Loader'
: 'Unknown'}
```
> Refactor MultisigInstruction

- price_pusher/package.json
- price_service/client/js/package.json
- price_service/sdk/js/package.json
- price_service/server/package.json
- target_chains/aptos/sdk/js/package.json
- target_chains/cosmwasm/sdk/js/package.json
- target_chains/ethereum/sdk/js/package.json
- target_chains/sui/sdk/js/package.json
Some users have reported that the old version of axios and axios-retry have some problems raising exceptions handling the responses from price service and hermes. This PR removes the version lock of these two (which was introduced to keep these two packages compatible) and updates them to the latest versions.
> fix(price-service/client): remove axios version lock

- pyth-rng/Cargo.lock
- pyth-rng/Cargo.toml
- pyth-rng/config.yaml
- pyth-rng/src/api.rs
- pyth-rng/src/api/chain_ids.rs
- pyth-rng/src/api/index.rs
- pyth-rng/src/api/revelation.rs
- pyth-rng/src/command/generate.rs
- pyth-rng/src/command/get_request.rs
- pyth-rng/src/command/register_provider.rs
- pyth-rng/src/command/request_randomness.rs
- pyth-rng/src/command/run.rs
- pyth-rng/src/config.rs
- pyth-rng/src/config/generate.rs
- pyth-rng/src/config/get_request.rs
- pyth-rng/src/config/register_provider.rs
- pyth-rng/src/config/request_randomness.rs
- pyth-rng/src/config/run.rs
- pyth-rng/src/ethereum.rs
- pyth-rng/src/main.rs
- pyth-rng/src/state.rs
This PR adds support for a single service to return random numbers for multiple blockchains. Main changes here are:
* Extracted ethereum network parameters to a config file
* Make private-key optional for ethereum network instantiation (so you don't need it for every CLI command)
* Make the state store a map from chain ids -> random number chains
> [pyth-rng] Add support for multiple blockchains

- price_pusher/package.json
- price_pusher/src/sui/command.ts
- price_pusher/src/sui/sui.ts
This is useful for running 2 pushers in parallel
> [sui-pusher] Add option to choose a different account derived from the same mnemonic

- hermes/Cargo.lock
- hermes/Cargo.toml
- hermes/src/metrics_server.rs
Openmetrics specification expects its own content-type instead of plain text. I didn't set it before as Prometheus still accepts text format but apparently there are some scrapers (like datadog) that decide dynamically what format to use for parsing based on the content type and our format follows Openmetrics specification. Prometheus should be able to parse it but weirdly it didn't work in our situation. An example of inconsistency is how counters are represented. In Openmetrics specification the metric name is appended by `_total` whereas normal prometheus just uses the metric name.
[This](https://github.com/DataDog/integrations-core/issues/14772) is the relevant issue mentioning datadog behaviour on parsing Prometheus and Openmetrics metrics.
> fix(hermes): fix metrics content-type

- .github/workflows/ci-fortuna.yml
- .github/workflows/push-fortuna-image.yml
- fortuna/Cargo.lock
- fortuna/Dockerfile
- fortuna/src/command/generate.rs
- fortuna/src/config.rs
- fortuna/src/config/generate.rs
- fortuna/src/config/get_request.rs
- fortuna/src/config/register_provider.rs
- fortuna/src/config/request_randomness.rs
- fortuna/src/config/run.rs
- target_chains/ethereum/contracts/contracts/random/PythRandom.sol
Add a CI workflows to bulid/test and publish a docker image
turns out the last PR had some build failures so I fixed those too
> Fortuna CI workflows

- fortuna/Cargo.lock
- fortuna/Cargo.toml
- fortuna/src/api/revelation.rs
- fortuna/src/command/generate.rs
- fortuna/src/command/run.rs
Per the API design guidelines, add support for multiple binary encodings to fortuna. This PR makes the endpoint take a `?encoding=` query parameter. Binary values are returned as a json object of the form: `{ encoding: "hex", data: "123ab" }`
(this is a nice-to-have, but I think it's going to save us a lot of questions from users of the form "how do i convert this array to a hex string")
> [fortuna] Support multiple random value encodings

- target_chains/ethereum/entropy_sdk/solidity/package.json
I think I need this field to get NPM to publish this new package.
> [entropy] make the SDK public

- fortuna/Cargo.toml
- fortuna/src/config.rs
- fortuna/src/config/generate.rs
- fortuna/src/config/get_request.rs
- fortuna/src/config/request_randomness.rs
- fortuna/src/config/run.rs
- target_chains/ethereum/entropy_sdk/solidity/README.md
- target_chains/ethereum/entropy_sdk/solidity/package.json
- target_chains/ethereum/examples/coin_flip/README.md
- target_chains/ethereum/examples/coin_flip/app/src/flip_coin.ts
- target_chains/ethereum/examples/coin_flip/contract/scripts/deploy.sh
- target_chains/ethereum/examples/coin_flip/contract/src/CoinFlip.sol
Couple minor changes in here. commented inline
> [entropy] Minor updates to parameters / docs

- price_pusher/docker-compose.mainnet.sample.yaml
- price_pusher/docker-compose.testnet.sample.yaml
- price_service/server/docker-compose.mainnet.yaml
- price_service/server/docker-compose.testnet.yaml
The old version of spy doesn't work any more on testnet. This PR updates the version to make sure spy can work on testnet.
> chore: update spy guardian version

- target_chains/near/receiver/src/ext.rs
- target_chains/near/receiver/src/lib.rs
- target_chains/near/receiver/src/state.rs
- target_chains/near/receiver/tests/workspaces.rs
Current API forces users to do conversions from price identifiers, small improvement to allow passing a hex string instead. Backwards compatible. Also fixes a small drive by problem from a rename I didn't propagate to the tests.
> feat(near): parse string identifiers

- target_chains/ethereum/contracts/README.md
- target_chains/ethereum/contracts/contracts/entropy/Entropy.sol
- target_chains/ethereum/contracts/contracts/entropy/EntropyState.sol
- target_chains/ethereum/contracts/forge-test/Entropy.t.sol
- target_chains/ethereum/contracts/forge-test/EntropyGasBenchmark.t.sol
- target_chains/ethereum/contracts/forge-test/utils/EntropyTestUtils.t.sol
- target_chains/ethereum/entropy_sdk/solidity/EntropyErrors.sol
- target_chains/ethereum/entropy_sdk/solidity/EntropyEvents.sol
- target_chains/ethereum/entropy_sdk/solidity/EntropyStructs.sol
- target_chains/ethereum/entropy_sdk/solidity/IEntropy.sol
Working on gas optimizations for entropy. This PR got a little out of hand but I'm glad I did it before the audit because the gas optimizations turned out to be nontrivial.
This PR adds a very basic gas benchmark for entropy, then does some code optimizations to bring down the gas usage. There are three main optimizations. Two of these are easy and one is less easy.
* (easy) use uint128 for fees instead of uint256
* (easy) Reduce the size of the Request struct. Store `hash(providerCommitment, userCommitment)` instead of both values, and store the number of hashes instead of the provider's sequence number.
* (less easy) store requests in a 2 level hash table (an array and a mapping) instead of just a mapping. There's an extensive code comment explaining this design, but basically it allows …
> [entropy] Entropy gas benchmarks and optimizations

- governance/xc_admin/packages/xc_admin_common/src/chains.ts
- target_chains/ethereum/contracts/contracts/pyth/PythGovernanceInstructions.sol
allocate a chain id and governance module for stacks. They need a governance module because they have a bunch of new governance instructions that it doesn't make sense to support under the existing Target module.
> [stacks] Add constants for Stacks

- target_chains/ethereum/contracts/contracts/entropy/Entropy.sol
- target_chains/ethereum/contracts/forge-test/Entropy.t.sol
- target_chains/ethereum/entropy_sdk/solidity/EntropyErrors.sol
- target_chains/ethereum/entropy_sdk/solidity/EntropyStructs.sol
Require the reveal method to be called by the same msg.sender that called request. This prevents a denial of service attack (see inline comment)
> [entropy] Add authorization for reveal method

- target_chains/ethereum/contracts/forge-test/Executor.t.sol
Add tests for all of the security checks in validating VAAs etc.
> [entropy] More executor tests

- fortuna/README.md
- fortuna/src/config/register_provider.rs
- target_chains/ethereum/contracts/README.md
- target_chains/ethereum/contracts/contracts/entropy/Entropy.sol
Edit some documentation and add readmes as prep for the audit.
> [entropy] Update readmes and docs

- governance/xc_admin/packages/xc_admin_common/src/__tests__/MessageBufferMultisigInstruction.test.ts
- governance/xc_admin/packages/xc_admin_common/src/multisig_transaction/MessageBufferMultisigInstruction.ts
- governance/xc_admin/packages/xc_admin_common/src/multisig_transaction/idl/staking.json
- governance/xc_admin/packages/xc_admin_common/src/multisig_transaction/index.ts
- governance/xc_admin/packages/xc_admin_common/tsconfig.json
- governance/xc_admin/packages/xc_admin_frontend/components/tabs/Proposals.tsx
- target_chains/solana/Cargo.lock
This will be useful to review some proposals to transfer authorities to governance and also for adding other Anchor programs in the future.
> Add staking program and mesh program to xc-admin UI

- target_chains/near/receiver/src/lib.rs
- target_chains/near/receiver/src/state.rs
- target_chains/near/receiver/tests/workspaces.rs
Doesn't require migration, state is already storing the right values. Just changes the `Price` type to use NEAR's U64/I64 types to make sure the result from contract calls serializes correctly. The reason we don't use pyth_sdk directly is because NEAR requires overriding serde which can't be done on imported types.
> fix(near): match Price interface from pyth-sdk

- governance/xc_admin/packages/xc_admin_common/src/propose.ts
Proposer server (the server that makes proposals with the ops key) was failing too often.
The main change here is I implemented some retry logic when it fails to send a transaction. If it fails 5 times in a row it will crash.
It adds some logging too.
It also refreshes the blockhash when the blockhash becomes stale (this wasn't handled properly previously).
> [xc-admin-proposer] Handle RPC errors

- target_chains/ethereum/contracts/contracts/executor/Executor.sol
- target_chains/ethereum/contracts/contracts/pyth/Pyth.sol
- target_chains/ethereum/contracts/forge-test/Executor.t.sol
- target_chains/ethereum/contracts/foundry.toml
- target_chains/ethereum/contracts/truffle-config.js
This change reverts the solidity version to 0.8.4 as the current version troubles the Pyth price feeds contract deployment. Some tests are changed to use the methods available in the older version.
Also, the Pyth contract version is updated. This is because we made a change to the Governance structs (to add Stacks) that results in a new bytecode.
> chore(target_chains/eth): revert solidity version

- pythnet/pythnet_sdk/Cargo.toml
- pythnet/pythnet_sdk/src/accumulators/merkle.rs
- pythnet/pythnet_sdk/src/wire.rs
- pythnet/pythnet_sdk/src/wire/prefixed_vec.rs
- pythnet/pythnet_sdk/src/wormhole.rs
I want to use `MerklePriceUpdate` in the receiver contract for Solana.
I made two changes :
- Derive `BorshSerialize` and `BorshDeserialize` for `MerklePriceUpdate`
- Bump borsh to 0.10.3
> [pythnet-sdk] Bump borsh add borsh to MerklePriceUpdate

- fortuna/Cargo.toml
- target_chains/cosmwasm/Cargo.lock
Update fortuna to have depend on pythnet-sdk by path for clarity.
Update Cargo.lock for coswasm receiver contract.
> [pythnet-sdk] Fix CI. Make dependency path. 

- target_chains/solana/cli/src/cli.rs
- target_chains/solana/cli/src/main.rs
- target_chains/solana/programs/pyth-solana-receiver/src/lib.rs
Command in the CLI to initialize the Pyth receiver on Solana
> [solana-receiver] Initialize receiver from CLI

- price_service/server/docker-compose.mainnet.yaml
- price_service/server/docker-compose.testnet.yaml
The new spy has a QUIC upgrade logic for mainnet which happens on January 16. This upgrade is breaking and all the spy runners should upgraded their spies.
> chore(price_service): update spy version and bootstrappers

- target_chains/solana/Cargo.lock
- target_chains/solana/cli/src/cli.rs
- target_chains/solana/cli/src/main.rs
- target_chains/solana/programs/pyth-solana-receiver/Cargo.toml
- target_chains/solana/programs/pyth-solana-receiver/src/error.rs
- target_chains/solana/programs/pyth-solana-receiver/src/lib.rs
Adds an instruction to post a price update in 1 transaction.
This function can only be called with 5 guardian signatures or less.
There will be two guys to post a price update.
- post_price_update : 2 transactions but verify 13 signatures and the same VAA can be used to post multiple price updates (for different price feeds)
- post_price_update_atomic : 1 transactions, <= 5 signatures
> [solana] Post update atomic

- .pre-commit-config.yaml
- pythnet/pythnet_sdk/src/messages.rs
pythnet-sdk CI has been failing for a bit.
Bumping nightly version in the pre-commits worked.
I think the error was caused by a new version of `ahash` that our `nightly-2023-03-01` didn't like
> Fix pythnet-sdk ci

- target_chains/solana/programs/pyth-solana-receiver/src/error.rs
- target_chains/solana/programs/pyth-solana-receiver/src/lib.rs
In Anchor the owners of accounts are hardcoded in the struct.
For example when we import `GuardianSet`, Anchor expects the owner of such account to be worm2ZoG2kUd4vFXhvjh93UUH596ayRfgQ2MgjNMTth (the official wormhole contract).
For us we want to be flexible and get the address of wormhole from the config, therefore we need to work around this and implement some stuff manually.
> [solana] Fix guardian set owner bug

- target_chains/solana/programs/pyth-solana-receiver/src/lib.rs
This makes it easy to reuse accounts.
You can also use this to build a push oracle by sequentially posting a price feed's update to the same account.
> [solana] Reuse accounts

- fortuna/Cargo.lock
- fortuna/Cargo.toml
- fortuna/src/command/register_provider.rs
- fortuna/src/command/run.rs
- fortuna/src/state.rs
There was one discussion in slack about having multiple contract on a chain. Therefore, I bind contract address too when computing the hash chain.
> [fortuna] bind provider and contract address

- target_chains/ethereum/sdk/solidity/MockPyth.sol
- target_chains/ethereum/sdk/solidity/package.json
We've recently changed Pyth to store the feeds on parse* methods if the updateData provided contains fresh prices. This change adds the same feature to the MockPyth.
> fix(target_chains/ethereum): update MockPyth to address Pyth

- contract_manager/src/contracts/evm.ts
- contract_manager/store/chains/EvmChains.yaml
- contract_manager/store/contracts/EvmContracts.yaml
- governance/xc_admin/packages/xc_admin_common/src/chains.ts
- target_chains/ethereum/contracts/networks/314.json
- target_chains/ethereum/contracts/networks/314159.json
This change adds RPC configuration for Filecoin and Hedera and adds the contract addresses for Filecoin.
> chore(ethereum): add new networks

- target_chains/ethereum/contracts/contracts/executor/ExecutorErrors.sol
- target_chains/ethereum/entropy_sdk/solidity/EntropyErrors.sol
Used the same format existing in PythErrors.sol
This website was very handy:
https://abi.hashex.org/
> Add entropy error signatures for easier access and debugging

- target_chains/solana/programs/pyth-solana-receiver/src/lib.rs
- target_chains/solana/programs/pyth-solana-receiver/src/sdk.rs
- target_chains/solana/programs/pyth-solana-receiver/tests/test_governance.rs
> [Solana] governance tests

- target_chains/ethereum/entropy_sdk/solidity/README.md
- target_chains/ethereum/sdk/solidity/README.md
By default, foundry expects every library to be a git project. This approach does not work well with SDKs in monorepos (like ours). However, you can also install the dependencies using NPM and then use remappings.txt to point to the SDK. This is a little janky, but it seems to be the recommended approach for this case 🤷  
see issue here https://github.com/foundry-rs/foundry/issues/1847
> [doc] Provide installation directions for Foundry

- governance/xc_admin/packages/xc_admin_common/src/cluster.ts
- governance/xc_admin/packages/xc_admin_frontend/components/tabs/General.tsx
Revert xc-admin to support only 32 publishers until pyth-agent can handle 64 publishers.
> [xc-admin] Revert 64 publishers

- hermes/build.rs
The `set -o pipefail` in the shell snippet in the build script is a bash feature and is not supported in all shells and failed Docker build. Removing it this along with the `-u` because that is also not used in the small shell snippet here but keeping `-e` to abort the script on errors.
Triggered a manual workflow to verify it works. ([link](https://github.com/pyth-network/pyth-crosschain/actions/runs/7883606305))
> fix(hermes): update build.rs to fix Docker build

- target_chains/solana/Cargo.lock
- target_chains/solana/Cargo.toml
- target_chains/solana/cli/Cargo.toml
- target_chains/solana/cli/src/main.rs
- target_chains/solana/programs/pyth-solana-receiver/Cargo.toml
- target_chains/solana/programs/pyth-solana-receiver/src/lib.rs
- target_chains/solana/programs/pyth-solana-receiver/src/sdk.rs
- target_chains/solana/programs/pyth-solana-receiver/src/state/mod.rs
- target_chains/solana/programs/pyth-solana-receiver/tests/common/mod.rs
- target_chains/solana/programs/pyth-solana-receiver/tests/test_governance.rs
- target_chains/solana/programs/pyth-solana-receiver/tests/test_post_price_update_from_vaa.rs
- target_chains/solana/programs/pyth-solana-receiver/tests/test_post_updates.rs
- target_chains/solana/programs/pyth-solana-receiver/tests/test_post_updates_atomic.rs
- target_chains/solana/pyth_solana_receiver_state/Cargo.toml
- target_chains/solana/pyth_solana_receiver_state/src/config.rs
- target_chains/solana/pyth_solana_receiver_state/src/lib.rs
- target_chains/solana/pyth_solana_receiver_state/src/price_update.rs
In the smart contract we are pinning anchor to 0.28.0 because of a Wormhole dependency.
I want consumers to be able to import our types in their code, but it's not great if they have to pin anchor to that version.
The compromise is moving the structs to a different crate that doesn't pin anchor and that can be imported both by the on-chain program and by consumer programs.
> refactor(solana): separate anchor state to another crate

- .github/workflows/ci-ethereum-contract.yml
- governance/xc_admin/packages/xc_admin_common/src/cluster.ts
- target_chains/ethereum/contracts/package.json
p.s (on the CI fix): Here is my theory: Apparently older forge had some bugs in cloning the dependencies of its own dependencies properly. `ds-test` is a dependency of `forge-std` that has some functionalities for testing were new and not really at the version we were using. Now that they've fixed the issue we are facing a problem as the ds-test doesn't have the new functions. I couldn't find relative PR for this though, it's just a guess. I could fix the CI by pinning foundry to an older version but this one is better.
> chore(xc_admin/frontend): set pythnet max publishers to 64

- target_chains/ethereum/entropy_sdk/solidity/README.md
- target_chains/ethereum/entropy_sdk/solidity/package.json
- target_chains/ethereum/sdk/solidity/README.md
- target_chains/ethereum/sdk/solidity/package.json
I was checking NPM to see if the other doc fix landed, and I noticed that `####` doesn't render properly over there. Replace with `###`
> [entropy] Fix doc formatting

- target_chains/solana/sdk/js/pyth_solana_receiver/package.json
Publish workflow is failing because this package `prepublishOnly` script does not run successfuly.
> fix(solana-receiver-js): Add test script to make prepublishOnly work

- contract_manager/package.json
- contract_manager/src/chains.ts
- contract_manager/src/contracts/sui.ts
- contract_manager/store/contracts/SuiPriceFeedContracts.yaml
- price_pusher/package.json
- price_pusher/src/sui/command.ts
- price_pusher/src/sui/sui.ts
- target_chains/cosmwasm/deploy-scripts/package.json
- target_chains/sui/sdk/js/package.json
- target_chains/sui/sdk/js/src/client.ts
- target_chains/sui/sdk/js/src/examples/SuiRelay.ts
Reopening #1294 as Github wasn't smart enough to pick up the rebase.
Upgraded to 0.49.1 which was fully backward incompatible 😭
Some getter functions (like getExecutionStatusError) were removed so replaced them with their internal logic
Upgraded typescript version when needed.
Removed batch attestation support
The typesystem got a lot stricter and had to ignore some errors for now. Otherwise, there would be lots of code for type narrowing.
Left to do:
> chore(target_chains/sui): update sui js packages

- target_chains/solana/programs/pyth-solana-receiver/src/lib.rs
- target_chains/solana/programs/pyth-solana-receiver/tests/common/mod.rs
- target_chains/solana/programs/pyth-solana-receiver/tests/test_post_price_update_from_vaa.rs
- target_chains/solana/programs/pyth-solana-receiver/tests/test_post_updates.rs
- target_chains/solana/programs/pyth-solana-receiver/tests/test_post_updates_atomic.rs
The big change here to review is the following. Previously during setup we had to pay rent of the treasury accounts otherwise when you send 1 lamport that doesn't cover the rent and it would fail. Now the first person to use a treasury account will pay the rent 0.0009 SOL. It makes it more ergonomic to deploy.
Other changes:
- move minimum signatures check for consistency with the Wormhole codebase
- try_deserialize_unchecked -> try_deserialize for the guardian check
> fix: solana audit 2

- target_chains/solana/programs/pyth-solana-receiver/src/lib.rs
- target_chains/solana/programs/pyth-solana-receiver/src/sdk.rs
- target_chains/solana/programs/pyth-solana-receiver/tests/test_governance.rs
- target_chains/solana/programs/pyth-solana-receiver/tests/test_post_price_update_from_vaa.rs
- allow post_update_atomic to return VerificationLevel::Full if it meets guardian quorum
- add cancel_governance_authority_transfer instruction
> fix: solana audit 3

- .github/workflows/ci-sui-contract.yml
- target_chains/sui/contracts/Move.lock
- target_chains/sui/contracts/Move.mainnet.toml
- target_chains/sui/contracts/Move.testnet.toml
- target_chains/sui/contracts/Move.toml
- target_chains/sui/contracts/sources/governance/contract_upgrade.move
- target_chains/sui/contracts/sources/governance/governance.move
- target_chains/sui/contracts/sources/governance/set_data_sources.move
- target_chains/sui/contracts/sources/governance/set_stale_price_threshold.move
- target_chains/sui/contracts/sources/governance/set_update_fee.move
- target_chains/sui/contracts/sources/hot_potato_vector.move
- target_chains/sui/contracts/sources/merkle_tree.move
- target_chains/sui/contracts/sources/pyth.move
- target_chains/sui/contracts/sources/pyth_accumulator.move
- target_chains/sui/contracts/sources/setup.move
- target_chains/sui/contracts/sources/state.move
Developers on Sui need to pin the same Sui version as their dependencies and it enforces everyone to use the same Sui version.
Pyth and Wormhole Sui versions have been old and this change updates them to the latest testnet version (1.19.1) to make integrations with us easier. Wormhole has undergone a similar change and thereforce its version has changed as well.
No contract deployment is needed for this change as it only unblocks downstream consumers for compiling their contracts.
> chore(target_chains/sui): update sui and wormhole dependency

- contract_manager/src/governance.ts
- governance/xc_admin/packages/crank_executor/src/index.ts
- governance/xc_admin/packages/proposer_server/src/index.ts
- governance/xc_admin/packages/xc_admin_common/src/__tests__/TransactionSize.test.ts
- governance/xc_admin/packages/xc_admin_common/src/executor.ts
- governance/xc_admin/packages/xc_admin_common/src/propose.ts
- target_chains/solana/sdk/js/pyth_solana_receiver/src/PythSolanaReceiver.ts
- target_chains/solana/sdk/js/solana_utils/src/index.ts
- target_chains/solana/sdk/js/solana_utils/src/transaction.ts
This fixes the bug where some `addPrice` proposals didn't work.
I also refactor the fee logic to move it inside `solana-utils`
The key change is we need to change `MAX_EXECUTOR_PAYLOAD_SIZE`
> fix: Make room for compute ixs

- governance/xc_admin/packages/xc_admin_frontend/components/layout/Layout.tsx
fix ui footer where it doesnt show on the bottom of the screen when screen size is relatively huge, this change makes the layout takes 100% of the view height so that layout will be on the bottom of the screen relative of the size
> fix(xc-admin): fix ui footer placement

- SECURITY.md
- hermes/README.md
- price_service/client/js/README.md
- target_chains/cosmwasm/contracts/README.md
- target_chains/ethereum/entropy_sdk/solidity/README.md
- target_chains/sui/contracts/sources/batch_price_attestation.move
- target_chains/sui/contracts/sources/pyth.move
- using relative links in the repo
- fix some typos in `.move` files
> chore: fix nits

- contract_manager/store/chains/EvmChains.yaml
- contract_manager/store/contracts/EvmPriceFeedContracts.yaml
- governance/xc_admin/packages/xc_admin_common/src/chains.ts
- target_chains/ethereum/sdk/js/package.json
- target_chains/ethereum/sdk/js/src/index.ts
> chore(target_chains/ethereum): add manta_sepolia

- target_chains/solana/sdk/js/pyth_solana_receiver/package.json
- target_chains/solana/sdk/js/solana_utils/package.json
`0.1.0` got already published. I want the latest version to be published so bumping.
> chore: release solana pull oracle packages

- .github/workflows/pypi-express-relay-utils.yml
simple fix to get publishing working
> fix workflow

- governance/xc_admin/packages/xc_admin_cli/package.json
- governance/xc_admin/packages/xc_admin_cli/src/index.ts
- governance/xc_admin/packages/xc_admin_common/package.json
- governance/xc_admin/packages/xc_admin_common/src/multisig_transaction/MessageBufferMultisigInstruction.ts
- governance/xc_admin/packages/xc_admin_common/src/multisig_transaction/index.ts
- target_chains/solana/sdk/js/pyth_solana_receiver/package.json
- target_chains/solana/sdk/js/pyth_solana_receiver/src/index.ts
This change adds Solana Receiver IDL to xc-admin to support parsing them in the xc-admin Frontend. Also adds two CLI commands to request and accept governance authority transfer.
> feat(governance/xc_admin): add initial support for solana receiver

- governance/xc_admin/Dockerfile
- governance/xc_admin/packages/xc_admin_frontend/Dockerfile
xc-admin now depends on Solana receiver's SDK and the Dockerfiles should include it in their build.
> fix(governance/xc_admin): fix Dockerfiles

- governance/xc_admin/Dockerfile
- governance/xc_admin/packages/xc_admin_frontend/Dockerfile
Apparently xc-admin now also needs price service SDK because the Solana receiver depends on it.
> fix(governance/xc_admin): add complete dependencies to the dockerfile

- target_chains/cosmwasm/Cargo.lock
- target_chains/cosmwasm/contracts/pyth/Cargo.toml
This should fix CI failing in `main`
> chore: update cosmwasm to used the wormhole published packages

- target_chains/solana/rust-toolchain.toml
This should fix an issue in `cargo publish`
> chore: bump toolchain for solana target chain

- target_chains/solana/pyth_solana_receiver_sdk/Cargo.toml
Remove star dependency to publish `pyth-solana-receiver-sdk`
> chore: no star dependency

- hermes/src/aggregate.rs
- hermes/src/api.rs
- hermes/src/api/ws.rs
- hermes/src/main.rs
- hermes/src/state.rs
This change removes the manual broadcast implementation to send out API notifications to WS subscribers.
> refactor(hermes): use broadcast channel for api notifications

- hermes/Cargo.lock
- hermes/rust-toolchain
- hermes/src/network/wormhole.rs
- hermes/src/state/cache.rs
Bump to latest nightly, brings a couple of benefits:
- Get's hermes past any annoying `ahash` transitive dependency clashes recent libraries adopted.
- The `.value()` call was removed from the unstable BTree Cursor we're, fixes that.
> chore: update to latest nightly

- hermes/src/aggregate.rs
- hermes/src/aggregate/wormhole_merkle.rs
- hermes/src/state.rs
- hermes/src/state/cache.rs
First commit of several for moving services behind an abstraction of `State` under `src/state/*`. Does a few drive by cleanups:
- Renames to `Cache` as it caches multiple things, and eventually might be good to replace with a generic store.
- Type aliases some of the more complex types, also leads to a cleaner rust doc.
- Implements down-casting from `State` to `Cache` to introduce better service separation.
> refactor(hermes): state->cache downcasting

- hermes/src/main.rs
Slightly more intuitive to abstract behind a vector rather than introduce the pinning.
> refactor(hermes): no need to Box futures

- hermes/src/aggregate.rs
- hermes/src/state.rs
- hermes/src/state/benchmarks.rs
Followup to #1432 with the same treatment to `Benchmarks`, also strips the unnecessary async_trait that newer Rust versions no longer needs.
> refactor(hermes): state->benchmarks downcasting

- hermes/src/aggregate.rs
- hermes/src/api.rs
- hermes/src/api/rest/v2/price_feeds_metadata.rs
- hermes/src/network/pythnet.rs
- hermes/src/price_feeds_metadata.rs
- hermes/src/state.rs
Continuation of #1432 and #1435
> refactor(hermes): state->price_feed_metadata downcasting

- target_chains/ethereum/contracts/blast-gas-claim-patch.diff
- target_chains/ethereum/contracts/mode-gas-claim-patch.diff
This change adds the change in our implementation that allowed support for enabling gas claims on Blast and Mode as a reference.
> chore(target_chains/ethereum): add Blast and Mode gas claim patches

- target_chains/solana/sdk/js/pyth_solana_receiver/package.json
- target_chains/solana/sdk/js/pyth_solana_receiver/src/PythSolanaReceiver.ts
Adds support for passing price feed ids as strings to the fetchPriceFeedAccount method. I already added support to the method that gets the account address, but missed this other method.
> [solana receiver sdk] Support string feed ids

- target_chains/solana/Cargo.lock
- target_chains/solana/programs/pyth-push-oracle/Cargo.toml
- target_chains/solana/programs/pyth-push-oracle/src/lib.rs
- target_chains/solana/programs/pyth-push-oracle/tests/test_update_price_feed.rs
If someone tries to update a feed with a stale price, ignore the update instead of throwing an error.
> [solana push oracle] Idempotent updates

- hermes/src/aggregate.rs
- hermes/src/network/wormhole.rs
Sending over the broadcast channel only fails when there are no receivers. We should ignore it instead of propagating it.
> fix(hermes): ignore broadcast send result

- apps/price_pusher/package.json
- apps/price_pusher/src/solana/command.ts
By using "processed" to poll, we have a more recent view of the blockchain.
> fix(solana_pusher): use processed to poll

- apps/hermes/Cargo.lock
- apps/hermes/Cargo.toml
- apps/hermes/src/network/pythnet.rs
- apps/hermes/src/network/wormhole.rs
`tokio::select` disables the branch that runs the wh connection if it returns OK and it never gets checked again. This change changes the `run` return to never return OK and does some refactoring as well.
> fix(hermes): reconnect on wh connection termination

- .dockerignore
Our dockerignore ignores all the files containing cache in their name and hermes had an exception here. This change was missed in moving Hermes around.
> fix(hermes): update cache.rs path in dockerignore

- apps/price_pusher/package.json
- apps/price_pusher/src/solana/solana.ts
This behavior is bad because sometimes it causes the pusher to get stuck forever.
Since this pusher is only used on Devnet right now, I am just dropping this feature.
> fix: remove alreadySending flag

- apps/hermes/src/config/pythnet.rs
Prefix the env var with Pythnet to be more clear.
> refactor(hermes): Change Pythnet mapping account env var

- apps/hermes/Cargo.lock
- apps/hermes/Cargo.toml
- apps/hermes/src/config/pythnet.rs
All arguments in `config/pythnet.rs` have `pythnet` as their prefix. Also they use `addr` instead of `address`. This change makes them consistent.
> refactor(hermes): match mapping address argument style with the rest

- governance/xc_admin/packages/xc_admin_frontend/components/tabs/Proposals/Proposal.tsx
Found this bug in prod:
https://proposals.pyth.network/?tab=proposals&proposal=D77X2ZX93eW9Ss5k2xRLhwgEnhMh195YVrXQ7w1teU9s
> fix: display bigint properly

- apps/fortuna/Cargo.lock
- apps/fortuna/rust-toolchain
also it has a minor update to cargo.lock file.
> fix: specify only channel and date for the toolchain

- contract_manager/package.json
- target_chains/aptos/cli/src/commands/aptos.ts
- target_chains/cosmwasm/deploy-scripts/package.json
- target_chains/cosmwasm/deploy-scripts/src/configs.ts
- target_chains/cosmwasm/deploy-scripts/src/instantiate-pyth.ts
- target_chains/cosmwasm/deploy-scripts/src/instantiate-wormhole.ts
- target_chains/ethereum/contracts/package.json
- target_chains/ethereum/contracts/scripts/batchDeployReceivers.ts
- target_chains/sui/cli/package.json
- target_chains/sui/cli/src/cli.ts
- target_chains/sui/cli/src/upgrade_pyth.ts
This change renames the contract manager package name to @pythnetwork/contract-manager to be consistent with our package names.
> chore(contract_manager): Rename package to @pythnetwork/contract-manager

- .pre-commit-config.yaml
- pythnet/pythnet_sdk/Cargo.toml
- pythnet/pythnet_sdk/src/messages.rs
- target_chains/solana/Cargo.lock
- target_chains/solana/pyth_solana_receiver_sdk/Cargo.toml
In anchor 0.30.0, it's not enough to implement `BorshSerialize` and `BorshDeserialize` for your structs.
You also need to implement the trait `IdlBuild`.
Thankfully the derive macro for `AnchorSerialize` and `AnchorDeserialize` does this for you automatically. 
I want to add this derive macro in pythnet_sdk when the solana-program feature is on.
This will allow people to use pyth-solana-receiver-sdk with anchor 0.30.0
> feat: add anchor to pythnet sdk

- target_chains/starknet/contracts/src/hash.cairo
- target_chains/starknet/contracts/src/merkle_tree.cairo
- target_chains/starknet/contracts/src/pyth.cairo
- target_chains/starknet/contracts/src/reader.cairo
- target_chains/starknet/contracts/src/wormhole.cairo
- target_chains/starknet/contracts/tests/wormhole.cairo
I'd like to transition from Result to panics for error handling in VAA parsing. This is just the first part, which also serves as an illustration of the changes I want to make.
I think removing Result is better here because:
- Our price update and governance methods should not return a Result:
- Handling errors gracefully can lead to vulnerabilities. For example, if we write a new guardian set and encounter an error halfway through, we must revert the transaction. If we instead return the value to the caller, it can ignore error and commit the transaction, leaving our contract in an invalid state.
- A user may fail to handle the error properly, causing bugs or even vulnerabilities in their own contract.
- Working with writable methods that return Result is inconvenient. For example, …
> refactor(target_chains/starknet): remove Result from reader

- apps/price_pusher/package.json
- apps/price_pusher/src/evm/command.ts
- apps/price_pusher/src/evm/evm.ts
This change makes gasLimit configurable and also adds an updateFeeMultiplier which is useful in Hedera as they have an inconsistency between the `value` passed in tx and the `value` on-chain.
> feat(price_pusher): add more options to evm pusher

- apps/fortuna/Cargo.lock
- apps/fortuna/Cargo.toml
- apps/fortuna/src/chain/ethereum.rs
- apps/fortuna/src/keeper.rs
Example logs
```2024-05-03T06:27:06.081429Z  INFO ThreadId(01) fortuna::command::run:193: Root of chain id arbitrum-sepolia matches commitment
2024-05-03T06:27:06.081771Z  INFO ThreadId(10) fortuna::command::run:211: Registered shutdown signal handler...
2024-05-03T06:27:06.082888Z  INFO ThreadId(10) keeper: fortuna::keeper:84: starting keeper chain_id="arbitrum-sepolia"
2024-05-03T06:27:06.083797Z  INFO ThreadId(01) fortuna::command::run:81: Starting server on: 127.0.0.1:34000
2024-05-03T06:27:06.476360Z  INFO ThreadId(04) keeper: fortuna::keeper:86: latest safe block: 40062855 chain_id="arbitrum-sepolia"
2024-05-03T06:27:06.965157Z  INFO ThreadId(10) keeper:process_new_blocks: fortuna::keeper:436: Waiting for new block ranges to process chain_id="arbitrum-sepolia" …
```
> feat(fortuna_staging): use spans to create a hierarchy of logs

- apps/price_pusher/package.json
- apps/price_pusher/src/index.ts
- apps/price_pusher/src/sui/command.ts
- apps/price_pusher/src/sui/sui.ts
We have a bunch of locked gas objects on Sui for some reason. These are usually returned in the error message of the failed tx, but they aren't being returned currently for some reason. Add a command line option so we can manually ignore them to get the process started again.
> [price_pusher] Option to ignore gas objects

- .github/workflows/ci-aptos-contract.yml
- target_chains/aptos/contracts/Move.toml
- target_chains/aptos/start_node.sh
This PR bumps Aptos dependencies and CI to match the latest CLI release, and mirrors [this PR on Wormhole](https://github.com/wormhole-foundation/wormhole/pull/3915)
> chore(aptos): bump to 3.1.0 toolchain/cli

- target_chains/starknet/contracts/src/pyth.cairo
- target_chains/starknet/contracts/src/pyth/errors.cairo
- target_chains/starknet/contracts/src/pyth/interface.cairo
- target_chains/starknet/contracts/src/pyth/price_update.cairo
There are no significant code changes, it's all just restructuring.
We have to preserve the `pyth::pyth` inline module because `#[starknet::contract]` requires it. Also it's difficult to use `Storage` outside of that inline module. So I've moved everything else out of this file to keep the file size reasonable.
> refactor(target_chains/starknet): split pyth module

- apps/hermes/src/api.rs
- apps/hermes/src/api/metrics_middleware.rs
- apps/hermes/src/api/rest/v2/sse.rs
- apps/hermes/src/api/ws.rs
- apps/hermes/src/metrics_server.rs
- apps/hermes/src/network/pythnet.rs
- apps/hermes/src/network/wormhole.rs
- apps/hermes/src/price_feeds_metadata.rs
- apps/hermes/src/state.rs
- apps/hermes/src/state/aggregate.rs
- apps/hermes/src/state/metrics.rs
- apps/hermes/src/state/wormhole.rs
This PR refactors the Wormhole API under services, and also wraps up Metrics. The main benefit of this PR is it separates out the runtime part of Wormhole from the Wormhole interface rather than everything being in one file.
This is a followup to the other similar refactors:
- #1432 
- #1435 
- #1439 
- #1479
> refactor(hermes): state->wormhole/metrics downcasting

- .github/workflows/push-xc-admin-frontend-image.yml
- governance/xc_admin/packages/xc_admin_frontend/Dockerfile
xc-admin-frontend needs to have some environment variables during build time to make them available on the client-side. This PR adds the most important one.
> fix(xc_admin_frontend): inject env variable for RPC in docker build

- governance/xc_admin/packages/crank_pythnet_relayer/src/index.ts
By default the compute unit limit for a tx is 200k but this is not
enough for all of our instructions. This change adds an instruction
to the pythnet relayer to set it to 1m to make sure all instructions
can be executed without problem.
> fix(xc_admin/crank_pythnet_relayer): increase compute unit limit 

- .github/workflows/ci-ethereum-contract.yml
- target_chains/ethereum/contracts/forge-test/Entropy.t.sol
- target_chains/ethereum/contracts/forge-test/Executor.t.sol
- target_chains/ethereum/contracts/forge-test/Pyth.WormholeMerkleAccumulator.t.sol
- target_chains/ethereum/contracts/forge-test/VerificationExperiments.t.sol
- target_chains/ethereum/contracts/forge-test/utils/PythTestUtils.t.sol
- target_chains/ethereum/contracts/forge-test/utils/WormholeTestUtils.t.sol
- target_chains/ethereum/contracts/foundry.toml
This change modifies the tests so the warnings go away. However, there are some warnings in the dependencies and they couldn't be resolved.
> refactor(target_chains/ethereum): fix forge warnings

- apps/fortuna/Cargo.lock
- apps/fortuna/Cargo.toml
- apps/fortuna/src/chain.rs
- apps/fortuna/src/chain/eth_gas_oracle.rs
- apps/fortuna/src/chain/ethereum.rs
- apps/fortuna/src/keeper.rs
- apps/fortuna/src/main.rs
So this was a fun one. It turns out that the default fee estimation logic in ethers.rs has a lower bound on the priority fee of 3 gwei. This value is way too high for the L2s that entropy is deployed on.
(see this logic here https://github.com/gakonst/ethers-rs/blob/master/ethers-providers/src/rpc/provider.rs#L452
which calls this to estimate the fee https://github.com/gakonst/ethers-rs/blob/master/ethers-core/src/utils/mod.rs#L496
which uses this constant as a lower bound https://github.com/gakonst/ethers-rs/blob/master/ethers-core/src/utils/mod.rs#L88 )
Unfortunately, there isn't a way to configure this behavior in ethers.rs , so I've ended up copy/pasting the relevant bits and dividing the constants by 100k which puts them more in the range of l2 behavior.
> [fortuna] Adjust gas oracle logic to eliminate ethers.rs priority fee lower bound

- governance/xc_admin/packages/xc_admin_frontend/components/tabs/Proposals/InstructionsSummary.tsx
- governance/xc_admin/packages/xc_admin_frontend/components/tabs/Proposals/ProposalRow.tsx
- governance/xc_admin/packages/xc_admin_frontend/components/tabs/Proposals/utils.ts
- governance/xc_admin/packages/xc_admin_frontend/package.json
This PR extends the summary to include publisher and price account details for addPublisher and delPublisher instructions.
> feat(xc_admin_frontend): add more details to summary view

- target_chains/starknet/contracts/src/pyth.cairo
- target_chains/starknet/contracts/src/pyth/errors.cairo
- target_chains/starknet/contracts/src/pyth/interface.cairo
- target_chains/starknet/contracts/src/util.cairo
- target_chains/starknet/contracts/tests/pyth.cairo
The stale check is different from the ethereum contract that essentially does `abs(block_timestamp - publish_time) < age`, which seems incorrect to me. Not sure what's the best way to handle the invalid `block_timestamp < publish_time` case, but it shouldn't depend on `age`.
> feat(target_chains/starknet): update if necessary and get no older than

- target_chains/sui/contracts/Move.movement_devnet_m2.toml
Accidentally left off the published-at address for Movement devnet deployment. The deployment can be inspected [here](https://explorer.devnet.m2.movementlabs.xyz/object/0x46522b54385efa424e0582ea4886bb5cfbe11d5c2a6a19ac0c82c2c81c73f9c5?network=devnet).
> fix(sui): add missing Movement deploy address

- contract_manager/store/chains/SuiChains.yaml
- contract_manager/store/contracts/SuiPriceFeedContracts.yaml
- target_chains/sui/contracts/Move.testnet.toml
The updated wh dependency had a redeployment of contract and that resulted in dependency mismatch. Because of that we needed to do a redeployment.
> chore(target_chains/sui): redeploy testnet contract

- apps/fortuna/Cargo.lock
- apps/fortuna/Cargo.toml
- apps/fortuna/src/command/run.rs
Set INF value for gauge if RPC is not accessible.
This would trigger the alerts on the monitoring service. We will not do the same for other gauges (e.g. set balance to 0) since that's just duplicate alerts for the same underlying symptom.
> fix(fortuna): Refactor and improve timestamp lag gauge

- governance/xc_admin/packages/xc_admin_frontend/hooks/usePyth.ts
Recently, a product account was wrongly initialized and didn't have any price accounts, causing the website to crash.
I think it's better to handle it more gracefully, by just ignoring such a product.
> fix(xc_admin_frontend):  product no price account

- apps/fortuna/Cargo.lock
- apps/fortuna/Cargo.toml
- apps/fortuna/src/keeper.rs
We are observing transactions that are successfully submitted to the network but never mined. The additional logs help us making sure the gas details are accurate.
> feat(fortuna): More logging on tx

- target_chains/starknet/contracts/src/byte_buffer.cairo
- target_chains/starknet/contracts/src/lib.cairo
- target_chains/starknet/contracts/src/merkle_tree.cairo
- target_chains/starknet/contracts/src/pyth.cairo
- target_chains/starknet/contracts/src/pyth/fake_upgrades.cairo
- target_chains/starknet/contracts/src/pyth/governance.cairo
- target_chains/starknet/contracts/src/pyth/interface.cairo
- target_chains/starknet/contracts/src/pyth/price_update.cairo
- target_chains/starknet/contracts/src/reader.cairo
- target_chains/starknet/contracts/src/wormhole.cairo
- target_chains/starknet/contracts/src/wormhole/interface.cairo
- target_chains/starknet/contracts/src/wormhole/parse_vm.cairo
- target_chains/starknet/contracts/tests/data.cairo
- target_chains/starknet/contracts/tests/pyth.cairo
- target_chains/starknet/contracts/tests/wormhole.cairo
- target_chains/starknet/tools/test_vaas/src/bin/generate_test_data.rs
- target_chains/starknet/tools/test_vaas/src/lib.rs
Using the same name as the core library type (that's even included in prelude) can be confusing to users. It's probably better to use a different name. Naming suggestions are welcome.
> refactor(target_chains/starknet): rename ByteArray to ByteBuffer

- apps/hermes/Cargo.lock
- apps/hermes/Cargo.toml
- apps/hermes/src/api/types.rs
- apps/hermes/src/network/pythnet.rs
- apps/hermes/src/state/aggregate.rs
I was running `openapi-zod-client https://hermes.pyth.network/docs/openapi.json` and got an error `MissingPointerError: Token "PriceIdentifier" does not exist.` it seems like we have a `RpcPriceIdentifier` which is pretty much similar to `PriceIdentifier` and also allows you to convert to and fro
> fix(apps/hermes/server): use RpcPriceIdentifier instead of PriceIdentifier

- target_chains/starknet/contracts/src/pyth.cairo
- target_chains/starknet/contracts/src/pyth/governance.cairo
- target_chains/starknet/contracts/tests/data.cairo
- target_chains/starknet/contracts/tests/pyth.cairo
- target_chains/starknet/tools/test_vaas/src/bin/generate_test_data.rs
> feat(target_chains/starknet): support SetFeeInToken instruction

- target_chains/solana/pyth_solana_receiver_sdk/README.md
Link doesn't work properly on https://crates.io/crates/pyth-solana-receiver-sdk .
According to https://github.com/rust-lang/crates.io/pull/3973, relative URLS will work both with crates and on Github.
> fix: readme link

- apps/fortuna/Cargo.lock
- apps/fortuna/Cargo.toml
- apps/fortuna/config.sample.yaml
- apps/fortuna/src/chain/eth_gas_oracle.rs
- apps/fortuna/src/config.rs
- apps/fortuna/src/keeper.rs
- contract_manager/scripts/upgrade_evm_entropy_contracts.ts
This should save us from having to keep dialing up/down the blast fees. I've tried to set up the logic so that it ensures the provider is always profitable and doesn't adjust the fees too often, but we'll probably have to tune this. See inline comment explaining the update logic.
> [fortuna] Automated fee adjustment based on gas prices

- pnpm-lock.yaml
- target_chains/sui/cli/package.json
ts-node is needed for the `cli` command.
> fix(target_chains/sui/cli): add ts-node to deps

- .tool-versions
- governance/xc_admin/packages/xc_admin_frontend/package.json
- governance/xc_admin/packages/xc_admin_frontend/pages/index.tsx
- pnpm-lock.yaml
Deployment of this in the k8s node needs to be coordinated with observer, [balance tracker](https://github.com/pyth-network/balance-tracker/pull/4) and the deduplication of key files in the deployment repo.
> [xc-admin-frontend] Unify publisher keys file schema with observer and balance tracker

- target_chains/starknet/sdk/js/package.json
- target_chains/starknet/sdk/js/src/index.ts
`ByteBuffer.fromHex` was actually using base64 🤦
> fix(target_chains/starknet): fix ByteBuffer.fromHex and add more conversions

- contract_manager/package.json
- governance/xc_admin/packages/crank_executor/package.json
- governance/xc_admin/packages/crank_pythnet_relayer/package.json
- governance/xc_admin/packages/proposer_server/package.json
- governance/xc_admin/packages/xc_admin_cli/package.json
- governance/xc_admin/packages/xc_admin_common/package.json
- governance/xc_admin/packages/xc_admin_frontend/package.json
- pnpm-lock.yaml
- target_chains/sui/cli/package.json
This change updates @pythnetwork/client package that has a change that allows encoding large upd_product proposals. More info on [this PR](https://github.com/pyth-network/pyth-client-js/pull/79) in the pyth-client-js repo.
> fix(xc-admin/frontend): handle large upd_product proposals

- apps/price_pusher/package.json
- apps/price_pusher/src/aptos/aptos.ts
- apps/price_pusher/src/injective/injective.ts
- apps/price_pusher/src/pyth-price-listener.ts
- apps/price_pusher/src/solana/solana.ts
- apps/price_pusher/src/sui/sui.ts
This PR updates the price pusher code to cause a crash when the RPC has issues. The RPC issues can be either the target network or Hermes.
This also solves #1704.
> refactor(apps/price_pusher): crash on RPC failures

- governance/xc_admin/packages/crank_executor/package.json
- governance/xc_admin/packages/crank_pythnet_relayer/package.json
- governance/xc_admin/packages/proposer_server/package.json
- governance/xc_admin/packages/xc_admin_common/package.json
- package.json
- pnpm-lock.yaml
This PR fixes some issues with the various xc_admin packages' dependencies.  Specifically:
- Deduplicate the version of `@certusone/wormhole-sdk`
- Add a missing `express` dependency for `proposer_server`
- Add a missing `bn.js` dependency for `xc_admin_common`
- Don't allow `@solana/web3.js` to move to the v1.93.0 -- this version [upgrades `rpc-websockets` to v9](https://github.com/solana-labs/solana-web3.js/releases/tag/v1.93.0), which includes [a significant change to the way that package is built](https://github.com/elpheria/rpc-websockets/pull/164) which does not appear to be working with our codebase -- I'll have to investigate later
- Fix issue where `@injectivelabs/sdk-ts` wasn't getting deployed by `pnpm deploy`, causing the servers to fail to start
The last issue turned out to …
> chore(xc_admin): fix xc_admin dependencies

- target_chains/sui/contracts/Move.lock
- target_chains/sui/contracts/Move.mainnet.toml
- target_chains/sui/contracts/Move.movement_m2_devnet.toml
- target_chains/sui/contracts/Move.testnet.toml
Apparently the address of Pyth in the addresses section should be the address of the first published package and only `published-at` should change upon upgrades.
The rest of the changes are cleaning up other addresses as they are not used. The wormhole address gets imported automatically by the dependency.
> fix(target_chains/sui): Update addresses in Move.tomls

- target_chains/solana/sdk/js/solana_utils/package.json
- target_chains/solana/sdk/js/solana_utils/src/transaction.ts
Most of the time, we want to add compute units to every transaction that we send to improve land rate.
There one edgecase where a instruction is so big that if we add compute units instruction we go over the limit.
This wasn't handled well, I'm pushing a fix.
> fix:solana utils single tx

- apps/hermes/server/Cargo.lock
- apps/hermes/server/Cargo.toml
- apps/hermes/server/src/api/rest/ready.rs
- apps/hermes/server/src/state/aggregate.rs
This change modifies the not_behind readiness indicator to use the most recent slot from Pythnet accumulator instead of taking the max because we think that during forks validators might return an absurdly large slot. It also makes it more verbose by returning the indicators and the initial values for them so we can investigate better if the issue persists.
> fix(hermes): tune readiness probe

- apps/price_pusher/config.solana.mainnet.sample.json
- apps/price_pusher/package.json
- apps/price_pusher/src/solana/command.ts
- apps/price_pusher/src/solana/solana.ts
We are using a fixed priceUpdate per bundle constant but it might need to be changed as the price proof size increases. This change makes it configurable.
> fix(apps/price_pusher/solana): make priceUpdates per bundle configurable

- apps/price_pusher/package.json
- apps/price_pusher/src/solana/solana.ts
Solana devnet pusher doesn't work great.
Since we have no Jito, we need to land many transactions sequentially. And until now it sequentially follows the order in `price-config.yaml`. In periods of bad landing rate it crashes before getting to the end of the sequence. Therefore price feeds towards the end of the list never get updated.
By randomizing the order of price updates to avoid the imbalance between the top of the list and the bottom of the list in terms of frequency of updates.
> fix(price-pusher): randomize price feed ids

- target_chains/solana/Cargo.lock
- target_chains/solana/pyth_solana_receiver_sdk/Cargo.toml
- target_chains/solana/pyth_solana_receiver_sdk/src/lib.rs
fix #1759 
I got the error 
On debugging i found out that it is originating for pythnet-sdk for src/wire.rs
issue : MerklePriceUpdate uses serde or Borsh while the the program was using Anchor, so i used borsh for s/dserailization
> changed anchor serailze/deserailize to borsh

- contract_manager/store/tokens/Tokens.yaml
I added this field initially to account for the fact that the chain has different mapping from "wei" to HBAR than the typical EVM chain. This was a hack though, and it looks like someone has fixed this issue somewhere else.
> fix(contract_manager) Set HBAR decimals to 18

- apps/api-reference/src/components/EvmProvider/index.tsx
- apps/api-reference/src/server-config.ts
This variable doesn't really need to be present outside of prod because we really don't need walletocnnect enabled in lower environments.
> fix(api-refernece) only require WALLETCONNECT_PROJECT_ID in prod

- pnpm-lock.yaml
- target_chains/fuel/sdk/js/package.json
gh action for `Publish Pyth JS packages` is failing due to `test` command being removed from `pyth-fuel-js` so removing it from `prepublishOnly` script
> fix(target_chains/fuel): remove test from prepublishOnly

- target_chains/fuel/contracts/src/constants.rs
- target_chains/fuel/contracts/src/pyth_utils.rs
Use `/out/release` instead of `/out/debug` for the ABI and BIN files of the Pyth contract.
> fix(target_chains/fuel): resolves issue with incorrect abi paths

- apps/hermes/server/src/state/cache.rs
- pythnet/pythnet_sdk/Cargo.toml
- pythnet/pythnet_sdk/src/messages.rs
- pythnet/pythnet_sdk/src/test_utils/mod.rs
- target_chains/cosmwasm/contracts/pyth/src/contract.rs
- target_chains/near/receiver/tests/workspaces.rs
- target_chains/solana/programs/pyth-push-oracle/src/lib.rs
- target_chains/solana/programs/pyth-push-oracle/tests/test_update_price_feed.rs
- target_chains/solana/programs/pyth-solana-receiver/src/lib.rs
- target_chains/solana/programs/pyth-solana-receiver/tests/test_post_price_update_from_vaa.rs
- target_chains/solana/programs/pyth-solana-receiver/tests/test_post_updates.rs
- target_chains/solana/programs/pyth-solana-receiver/tests/test_post_updates_atomic.rs
`PublisherStakeCapsMessage` is a new type of message, that contains how much stake each publisher should have to maximize their rewards in the context of CIP. 
This message is different from other messages in that there's only one message of this type in the Merkle tree, and also it is potentially really big (since it contains the list of all publishers and their cap).
https://forum.pyth.network/t/community-proposal-for-the-design-of-the-community-integrity-pool-cip/1571
I gets computed in https://github.com/pyth-network/pythnet/pull/302 , and will be consumed by the reward distribution logic on Solana.
> feat: add publisher stake caps to validator

- apps/api-reference/src/apis/evm/get-price.ts
- apps/api-reference/src/apis/evm/get-valid-time-period.ts
- apps/api-reference/src/apis/evm/parse-price-feed-updates-unique.tsx
- apps/api-reference/src/components/Home/index.tsx
- express_relay/examples/easy_lend/contracts/EasyLend.sol
- pnpm-lock.yaml
- target_chains/ethereum/contracts/forge-test/GasBenchmark.t.sol
- target_chains/ethereum/contracts/forge-test/Pyth.Aave.t.sol
- target_chains/ethereum/contracts/package.json
- target_chains/ethereum/sdk/js/README.md
- target_chains/ethereum/sdk/js/src/examples/EvmRelay.ts
- target_chains/ethereum/sdk/solidity/AbstractPyth.sol
- target_chains/ethereum/sdk/solidity/IPyth.sol
- target_chains/ethereum/sdk/solidity/README.md
- target_chains/ethereum/sdk/solidity/abis/IPyth.json
- target_chains/ethereum/sdk/solidity/package.json
getPrice method uses a configured default staleness from the Pyth contract which is normally set to 60 seconds. While this is enough for some types protocols it's very high for latency-sensitive protocols and protocols should use set their own desired staleness. This change removes this method and getEmaPrice and leaves protocols with getPriceUnsafe or getPriceNoOlderThan.
The contract will still support the getPrice method to avoid breaking existing users of it.
> feat(target_chains/ethereum): remove getPrice from IPyth

- contract_manager/src/store.ts
- contract_manager/store/chains/EvmChains.yaml
b3_mainnet wasn't defined correctly in the yaml file and this was resulting in an inscrutable error downstream. Fix the yaml file, and also add a check to make the failure mode more obvious.
> fix(contract_manager) Throw error on unknown chain type

- target_chains/solana/sdk/js/pyth_solana_receiver/package.json
- target_chains/solana/sdk/js/pyth_solana_receiver/src/PythSolanaReceiver.ts
Benchmarks serves the VAAs with 19 signatures, but we only care about verifying 13 to save compute units
> feat: fix solana sdk for benchmarks

- apps/staking/package.json
- apps/staking/src/api.ts
- apps/staking/src/components/AccountHistoryButton/index.tsx
- apps/staking/src/components/Dashboard/index.tsx
- apps/staking/src/components/Dashboard/loaded.tsx
- apps/staking/src/components/Dashboard/spark-chart.tsx
- apps/staking/src/components/Dashboard/wallet-button.tsx
- apps/staking/src/components/Home/index.tsx
- apps/staking/src/components/LoadingSpinner/index.tsx
- apps/staking/src/components/Modal/index.tsx
- apps/staking/src/components/ModalButton/index.tsx
- apps/staking/src/components/Root/wallet-provider.tsx
- apps/staking/src/components/Tokens/index.tsx
- apps/staking/src/components/TransferButton/index.tsx
- apps/staking/src/use-api-context.ts
- apps/staking/src/use-stake-account.tsx
- apps/staking/src/use-transfer.ts
- pnpm-lock.yaml
This PR adds low-res / unstyled implementation for the following new feature requirements that we've discovered:
- Must claim rewards before withdrawing
- Must claim rewards before unstaking
- Add swr to loadData
- Calculate APY in the frontend
- Show how APY will change due to staking tokens
- Show historical APY in a spark chart
- Add functionality to select a stake account if multiple exist for the given wallet
- If wallet is a publisher, show self highlighted (& adjust apy calculation)
- Claim within 1 year
- Show next locked token unlock period & amount
- Show account history
> feat(staking): add low-res implementation for new requirements

- apps/staking/src/api.ts
- apps/staking/src/components/OracleIntegrityStaking/index.tsx
This is a minor refactor to remove `isSelf` from the api and instead calculate it in the components; it felt strange to be deriving this value in the api and made the api a bit messy.
> chore(staking): refactor a bit to remove isSelf

- apps/staking/package.json
- apps/staking/src/components/AccountHistory/index.tsx
- apps/staking/src/components/Header/current-stake-account.tsx
- apps/staking/src/components/Home/index.tsx
- apps/staking/src/components/OracleIntegrityStaking/index.tsx
- apps/staking/src/components/WalletButton/index.tsx
- apps/staking/src/hooks/use-api.tsx
- apps/staking/src/hooks/use-data.ts
- pnpm-lock.yaml
- Fix alignment of stake account indicator in header
- Update language of opt-out modal
- Round APY in publishers table to 2 digits
- Show estimated APY even if amount exceeds wallet balance
- Separate main account from other accounts in stake account menu
- Store last selected stake account in local storage
> feat(staking): implement some feedback items

- governance/pyth_staking_sdk/package.json
the `@pythnetwork/staking-sdk` is causing pyth-publish-js workflow to fail, more info here: https://github.com/pyth-network/pyth-crosschain/actions/runs/10848587703/job/30106315103
specifically it can't figure out if published or not so it assumes it is unpublished, this is blocking fuel release so making it private for now if it's not ready to be published
> fix: pyth-publish-js workflow

- apps/staking/src/components/AccountSummary/index.tsx
- apps/staking/src/components/Dashboard/index.tsx
- apps/staking/src/components/Header/help-menu.tsx
- apps/staking/src/components/Menu/index.tsx
- apps/staking/src/components/OracleIntegrityStaking/index.tsx
- apps/staking/src/components/WalletButton/index.tsx
- Remove account history button
- Fix outline when opening menus
- Fix another alignment issue
- On small screens, enable "Withdraw" button even if there are no tokens available for withdrawal, but show a message indicating such
- Add MDP guide link to help menu & own stake section
> feat(staking): more refinements

- governance/xc_admin/packages/xc_admin_common/src/executor.ts
- governance/xc_admin/packages/xc_admin_common/src/propose.ts
The RPC call `getRecentBlockhash` got deprecated, this what anchor's `sendAndConfirm`  was using. 
We change it to use sendTransactions, our custom transaction dispatching logic.
> fix: executor

- target_chains/solana/sdk/js/pyth_solana_receiver/package.json
- target_chains/solana/sdk/js/pyth_solana_receiver/src/PythSolanaReceiver.ts
- target_chains/solana/sdk/js/pyth_solana_receiver/src/index.ts
We forgot to export this method. It's good to export because it can be used to compute price feed account pubkeys.
> chore: export getPriceFeedAccountForProgram

- apps/staking/src/hooks/use-api.tsx
- governance/pyth_staking_sdk/src/pyth-staking-client.ts
Actually I think this approach is better.
> feat(staking): add default instead of assertWallet

- governance/xc_admin/packages/xc_admin_cli/package.json
- governance/xc_admin/packages/xc_admin_cli/src/index.ts
- governance/xc_admin/packages/xc_admin_common/src/multisig_transaction/MessageBufferMultisigInstruction.ts
- governance/xc_admin/packages/xc_admin_common/src/multisig_transaction/anchor.ts
- governance/xc_admin/packages/xc_admin_common/src/multisig_transaction/index.ts
- pnpm-lock.yaml
Adding an instruction to xc_admin to allow upgrading the on-chain idl of anchor programs.
> feat(xc_admin_cli): support idl upgrades

- pnpm-lock.yaml
lock file was using a newer version (`0.94.6`) by mistake while the types were generated using the version (`0.94.5`). Reverted those changes and only updated `limo-sdk`
> fix: downgrade fuels library

- apps/staking/src/components/PublisherFaq/index.tsx
Some info felt redundant and the order was strange too
> fix: reorder slashing faq

- apps/staking/src/components/Dashboard/index.tsx
- apps/staking/src/components/OracleIntegrityStaking/index.tsx
- apps/staking/src/middleware.ts
- Improve layout of initial landing page after connecting wallet
- Show options to reverse sort on mobile
- Fix paginator
- Fix sort by pool utilization
- Clean up mid-screen sizes (less dead empty space)
- Use a red instead of fuchsia for over utilized pools
- Clean up middleware implementation
- Don't apply middleware to static files
> fix(staking): implement a bunch of staking app fixes

- governance/pyth_staking_sdk/src/pyth-staking-client.ts
Some stake accounts are not created through the createStakeAccount function.
Therefore they need to call joinDaoLlc when delegating/staking.
> fix: join llc before delegating

- apps/staking/src/components/OracleIntegrityStaking/index.tsx
Including selfStakeDelta in the self Publisher's stake column; to keep consistent with the treatment of poolUtilization
> fix: display self-stake forecast

- apps/staking/src/app/api/v1/cmc/supply/route.ts
- apps/staking/src/app/api/v1/locked_accounts/route.ts
- apps/staking/src/components/Menu/index.tsx
- apps/staking/src/components/OracleIntegrityStaking/index.tsx
- apps/staking/src/components/Root/index.tsx
- apps/staking/src/components/Switch/index.tsx
- apps/staking/src/components/WalletButton/index.tsx
- apps/staking/src/components/WalletProvider/index.tsx
- apps/staking/src/config/server.ts
- apps/staking/src/hooks/use-api.tsx
- apps/staking/src/hooks/use-network.tsx
> feat(staking): add a switch to flip between mainnet & devnet

- governance/xc_admin/packages/xc_admin_common/src/__tests__/PriceStoreProgramInstruction.test.ts
- governance/xc_admin/packages/xc_admin_common/src/price_store.ts
Fixes `Error: program ID mismatch`.
> fix(governance/xc_admin): fix price store instruction parsing

- governance/pyth_staking_sdk/src/pyth-staking-client.ts
By default getAssociatedTokenAddress fails if the owner of the token account is a Program Derived Address. This causes problems when for example a program multisig owns a stake account.
> feat: enable pda wallets

- governance/xc_admin/packages/crank_pythnet_relayer/src/index.ts
- governance/xc_admin/packages/xc_admin_common/src/executor.ts
- governance/xc_admin/packages/xc_admin_common/src/price_store.ts
The executor only runs on Solana and we need to run this account creation on relayer which handles Pythnet messages.
> feat(xc-admin): add support for price store in relayer

- target_chains/ethereum/sdk/solidity/README.md
Fixing [issue-1735](https://github.com/pyth-network/pyth-crosschain/issues/1735)
> fix(ethereum/sdk/solidity) Fix Readme

- governance/pyth_staking_sdk/src/pyth-staking-client.ts
Instead of trying to advance all records, only those who are outdated.
> fix: advance only necessary records

- governance/pyth_staking_sdk/src/pyth-staking-client.ts
- governance/pyth_staking_sdk/src/utils/bigint.ts
Until now lowest epoch calculation was wrong because it only took into account delegation records, but these don't exist if you have never claimed.
When the delegation record doesn't exist, you need to look at the activationEpoch of the positions to get a sense of the expiry date of the rewards.
> fix: lowest epoch calc

- apps/price_pusher/package.json
- apps/price_pusher/src/solana/solana.ts
This health check fails sometimes because the slot it queries hasn't become a block yet and has no timestamp. To fix this I will instead query a finalized slots which should always have a timestamp
> fix: get finalized slots

- apps/price_pusher/package.json
- apps/price_pusher/src/solana/solana.ts
With https://github.com/pyth-network/pyth-crosschain/pull/2029 I can see some false positives of Solana being unhealthy that made the pusher crash, because finalized slots are typically 20 seconds in the past (and sometimes it touches 30s).
Let's increase this threshold so that it doesn't crash anymore
> fix: solana health check increase time

- governance/pyth_staking_sdk/src/pyth-staking-client.ts
For locked accounts, which aren't created from the UI, we need to create the token owner record here.
> fix: create token owner record on stake

- express_relay/sdk/js/package.json
- express_relay/sdk/js/src/examples/simpleSearcherLimo.ts
- package.json
- pnpm-lock.yaml
[Semver rules](https://docs.npmjs.com/about-semantic-versioning) don't treat unstable versions (major version 0) the same as stable releases, and the caret notation doesn't bump minor versions for unstable releases. We have to do that manually
> Bump limo version to 0.3.0

- express_relay/sdk/js/package.json
- express_relay/sdk/js/src/examples/simpleSearcherLimo.ts
- express_relay/sdk/python/express_relay/searcher/examples/simple_searcher_svm.py
- express_relay/sdk/python/express_relay/svm/generated/limo/instructions/take_order.py
- express_relay/sdk/python/express_relay/svm/limo_client.py
- express_relay/sdk/python/pyproject.toml
Prior to the recent Limo updates to include `outputAmount` in the take instruction, `fillRate` could refer to the percentage of the remaining input amount to fill. Now that the client must compute out the `outputAmount` to receive, the `fillRate` computation is a bit easier to do if in terms of the original input amount rather than the remaining amount, since we don't have to recompute the percentage of the original input amount that is being filled.
> Bug: correct fill rate in ER Limo simple searcher example

- apps/fortuna/Cargo.lock
- apps/fortuna/Cargo.toml
- apps/fortuna/src/chain/ethereum.rs
- apps/fortuna/src/chain/reader.rs
- apps/fortuna/src/keeper.rs
abstract chain was not able to simulate these calls since the default from address was not a valid account
> fix: Specify sender address on reveal simulations

- packages/component-library/.storybook/preview.tsx
- packages/component-library/src/Checkbox/index.stories.tsx
- packages/component-library/src/Checkbox/index.tsx
- packages/component-library/src/CheckboxGroup/index.stories.tsx
- packages/component-library/src/CheckboxGroup/index.tsx
- packages/component-library/src/Link/index.stories.tsx
- packages/component-library/src/Link/index.tsx
- packages/component-library/src/Radio/index.stories.tsx
- packages/component-library/src/Radio/index.tsx
- packages/component-library/src/RadioGroup/index.stories.tsx
- packages/component-library/src/RadioGroup/index.tsx
Adds first round of form components to the component library.  New components are:
- `Link`
- `Checkbox`
- `CheckboxGroup`
- `Radio`
- `RadioGroup`
There's currently considerable amounts of duplication between `Checkbox` and `Radio` and between `CheckboxGroup` and `RadioGroup`.  I'll refactor the duplication out as I add in more components and get a better idea of where the common styles are that need to be extracted.
> feat(component-library): add first round of form components

- target_chains/solana/Cargo.lock
- target_chains/solana/pyth_solana_receiver_sdk/Cargo.toml
- target_chains/solana/pyth_solana_receiver_sdk/src/price_update.rs
This will allow people to use this with anchor 0.30.1
> fix: cap solana version

- apps/api-reference/turbo.json
- apps/staking/turbo.json
- governance/xc_admin/packages/xc_admin_frontend/turbo.json
This PR adds environment variables to the turbo configuration, which fixes an issue where they aren't available at build time due to [turbo environment strict
mode](https://turbo.build/repo/docs/crafting-your-repository/using-environment-variables#strict-mode). As a result, statically generated pages do not have correct environment variables and in particular things like the RPC aren't set correctly
> fix: add env vars to turbo config

- contract_manager/src/contracts/ton.ts
- target_chains/ton/contracts/contracts/Pyth.fc
- target_chains/ton/contracts/contracts/common/gas.fc
- target_chains/ton/contracts/tests/PythTest.spec.ts
- target_chains/ton/sdk/js/README.md
- target_chains/ton/sdk/js/src/index.ts
- **Fix Trailing Header Size Interpretation**: Corrects the trailing header size to be interpreted in bytes rather than bits.
- **Fix Compute Fee Calculation**: Adjusts the compute fee calculation to accurately factor in the number of updates, preventing potential exploitation where fees could be bypassed by submitting numerous updates.
> fix(target_chains/ton): fix traling header size interpretation & compute fee calculation

- apps/staking/package.json
- pnpm-lock.yaml
Seems like recharts's ResponsiveContainer component in version 2.13.2 wasn't working with React 19, and the issue has been fixed with recharts 2.13.3
> chore(staking): upgrade recharts

- package.json
- pnpm-lock.yaml
This PR removes the [npm pre-commit package](https://www.npmjs.com/package/pre-commit) which was added in https://github.com/pyth-network/pyth-crosschain/pull/805/files.
It appears that this package was added in a misguided attempt to get an automated installer for [the pre-commit hook framework](https://pre-commit.com/).  However, the npm package, despite sharing the same name, actually has nothing to do with that framework.  Instead, the npm package just created a git pre-commit hook that runs `npm test` at the repo root.
This was a no-op until [I added turborepo](https://github.com/pyth-network/pyth-crosschain/pull/2065), because prior to adding turborepo, there _was_ no `test` script at the root.  When I added turbo repo, I set up a `test` script at the root which runs `turbo test` -- …
> chore: remove npm pre-commit package

- README.md
- contract_manager/store/chains/EvmChains.yaml
- contract_manager/store/tokens/Tokens.yaml
so the monthly fee fetching KPI script is more accurate
> fix(contract_manager) Update chains and tokens

- apps/hermes/server/Cargo.lock
- apps/hermes/server/Cargo.toml
- apps/hermes/server/src/api/rest/v2/sse.rs
Caught a bug when testing #2091 on testnet -- the `ignore_invalid_price_ids` param is required on the stream API when it should have been optional. This was raised by @keyvankhademi in the original PR, but it looks like I crossed some wires in my git operations and the commit didn't end up in the branch before I merged it. Thanks to @ayazabbas for the tip on testing the release on testnet first, it helped out here :)
> fix(hermes): make `ignore_invalid_price_ids` param optional on the stream API

- .pre-commit-config.yaml
- apps/hermes/server/src/api/rest/v2/sse.rs
Fix a mismatch between the Hermes toolchain (stable) and the `cargo fmt` command run by precommit in CI (nightly). Reformat the `sse.rs` touched by #2102 to make it pass precommit.
>  chore(hermes): use stable rust toolchain in precommit formatter

- apps/price_pusher/README.md
- apps/price_pusher/package.json
- apps/price_pusher/src/injective/command.ts
- apps/price_pusher/src/injective/injective.ts
- target_chains/cosmwasm/tools/src/chains-manager/injective.ts
- target_chains/cosmwasm/tools/src/ci/deployer/injective.ts
Hey, we'd like to be able to specify the `gasMultiplier` config. Currently, the Pyth price pusher is spending around `14inj` per day more than needed, which ends up at around $9k at current prices. This is why we'd like to optimize. 
I've also updated the `DEFAULT_GAS_PRICE` to `160000000` which is the new default on chain.
> feat: added gas multiplier arg for injective

- .pre-commit-config.yaml
- apps/fortuna/src/api/revelation.rs
- apps/fortuna/src/chain/ethereum.rs
- apps/fortuna/src/chain/reader.rs
- apps/fortuna/src/command/run.rs
- apps/fortuna/src/keeper.rs
- apps/fortuna/src/state.rs
- apps/hermes/server/src/network/wormhole.rs
- governance/remote_executor/programs/remote-executor/src/tests/executor_simulator.rs
- governance/remote_executor/programs/remote-executor/src/tests/test_adversarial.rs
- governance/remote_executor/programs/remote-executor/src/tests/test_basic_instructions.rs
- pythnet/message_buffer/programs/message_buffer/src/lib.rs
- pythnet/message_buffer/programs/mock-cpi-caller/src/lib.rs
- pythnet/message_buffer/programs/mock-cpi-caller/src/state/mod.rs
- target_chains/cosmwasm/contracts/pyth/src/contract.rs
- target_chains/cosmwasm/sdk/rust/src/testing.rs
- target_chains/solana/programs/pyth-push-oracle/src/lib.rs
- target_chains/solana/programs/pyth-solana-receiver/src/lib.rs
- target_chains/solana/programs/pyth-solana-receiver/src/sdk.rs
- target_chains/solana/pyth_solana_receiver_sdk/src/cpi/accounts.rs
- target_chains/solana/pyth_solana_receiver_sdk/src/lib.rs
Pre-commit config in CI previously used `clippy --fix`, which makes `-D warnings` have no effect. Now warnings should be properly denied. I fixed the simple warnings and added allow annonations for more complex cases.
> Deny clippy warnings in CI properly

- apps/hermes/client/js/package.json
this commit https://github.com/pyth-network/pyth-crosschain/commit/e08052c2c42b0c8562fc16147a1448800c4aacb3#diff-d410d1d6da096f2ed035def56a8c9e5ac39c31870cbec8512d0c8c100ae8767aR23 broke the ci for publishing new js packages
> fix(hermes-client): fix hermes-client prepublish script

- .github/workflows/ci-turbo-build.yml
- .github/workflows/ci-turbo-test.yml
- .github/workflows/publish-js.yml
- package.json
- target_chains/ton/contracts/package.json
This PR does a few related things:
- Excludes nextjs packages from building on github as part of CI or before publishing js packages -- this is because these packages are intended to be built on Vercel and require system access & env vars to build that we don't have any good reason to expose to Github Actions
- Adds a new github workflow to run the turbo build in github actions on any PRs that modify any ts/js files
- Renames the "build" script for the pyth-ton package so it doesn't trigger on CI builds -- this script is an interactive build that doesn't seem to produce any results in a CI environment and so it shouldn't be included in the build on CI
> fix(ci): fix CI js builds

- apps/hermes/server/Cargo.lock
- apps/hermes/server/Cargo.toml
- apps/hermes/server/src/api.rs
- apps/hermes/server/src/api/rest.rs
- apps/hermes/server/src/api/rest/index.rs
- apps/hermes/server/src/api/rest/v2/latest_twaps.rs
- apps/hermes/server/src/api/rest/v2/mod.rs
- apps/hermes/server/src/api/types.rs
- apps/hermes/server/src/state/aggregate.rs
Create Hermes endpoint at `/v2/updates/twap/:window_seconds/latest/` to get the latest TWAP prices for a list of price IDs with a dynamic time window (default 300s/5m).
- Hermes will calculate the requested TWAP, but on-chain consumers won’t have a way to verify this calculated price. Thus, the “real” calculation needs to happen on-chain, using the verified prices from `t0` and `t1`, in the target chain contract.
- The calculation returned by Hermes (in `parsed`) will match what our SDK will return from on-chain.
- Thus, the endpoint returns the following structure (`TwapsResponse`):
- `binary` (list of `BinaryUpdate`, where each update contains the start & end `TwapMessages` for a requested feed)
- The `TwapMessages` contain everything needed to compute the TWAP on-chain (cumul price, …
> feat(hermes): create latest TWAP endpoint

- governance/pyth_staking_sdk/src/utils/clock.ts
By getting a finalized block, it is less likely than `getBlockTime` fails.
> fix: use finalized commitment for blocktime

- governance/xc_admin/packages/xc_admin_frontend/components/tabs/General.tsx
- governance/xc_admin/packages/xc_admin_frontend/components/tabs/Proposals/ProposalRow.tsx
- set minimum publishers in proposal after changing publisher set
- fix proposals time
> fix: minor fixes

- lazer/Cargo.lock
- lazer/contracts/solana/package.json
- lazer/contracts/solana/programs/pyth-lazer-solana-contract/Cargo.toml
- lazer/contracts/solana/scripts/migrate_from_0_1_0.ts
- lazer/sdk/rust/protocol/Cargo.toml
- lazer/sdk/rust/protocol/src/lib.rs
- lazer/sdk/rust/protocol/src/message.rs
This script was used for migration on devnet and testnet.
The consumer contracts will need to use these parsing functions because it's not possible to return data from a CPI.
> feat(lazer): add solana contract migration script, add message parsing to protocol

- target_chains/solana/Cargo.lock
- target_chains/solana/cli/Cargo.toml
- target_chains/solana/cli/src/cli.rs
- target_chains/solana/cli/src/main.rs
- target_chains/solana/programs/pyth-solana-receiver/src/error.rs
- target_chains/solana/programs/pyth-solana-receiver/src/lib.rs
- target_chains/solana/programs/pyth-solana-receiver/tests/test_post_twap_updates.rs
- target_chains/solana/pyth_solana_receiver_sdk/src/price_update.rs
This PR makes changes to the Solana receiver contract, the receiver SDK, and the receiver CLI. 
- Add `post-twap-update` command to the CLI. This is useful for users to test the update procedure, and to see an example of how to verify start & end data from Hermes via Wormhole and post it to the receiver contract. 
- Usage: `pyth-solana-receiver-cli --wormhole <WORMHOLE> post-twap-update --start-payload <START_PAYLOAD> --end-payload <END_PAYLOAD>`
- Refactored some existing functions to avoid code duplication
- Add extra validations to `calculate_twap` as brought up in earlier code review.
- Validate that the start & end messages have the same `feed_id` and `exponent`
- Update `TwapUpdate` data model to remove the `verification_level` & `posted_slot` fields.
- After a discussion with …
> feat(solana-receiver-cli): Add `post-twap-update` cmd to CLI, update TWAP data model & validations

- apps/staking/src/components/AccountSummary/index.tsx
- apps/staking/src/components/Dashboard/index.tsx
- apps/staking/src/components/Root/index.tsx
This top bar was taking up a fair amount of space which made it hard for people on smaller screens to realize they could scroll down.  This PR tightens things up to hopefully avoid some of the support load from people not realizing that they need to scroll down to interact with the programs
> chore(staking): tighten up account summary bar

- apps/hermes/client/js/src/examples/HermesClient.ts
- add types
- add how to get a `PriceUpdate` from the message
> fix: improve hermes client example

- target_chains/solana/sdk/js/solana_utils/package.json
- target_chains/solana/sdk/js/solana_utils/src/transaction.ts
Turns out the solution to `Minimum context slot has not been reached` is probably removing the `minContextSlot: blockhashResult.context.slot` config
> fix(proposer server)

- governance/xc_admin/packages/xc_admin_cli/src/index.ts
- governance/xc_admin/packages/xc_admin_common/src/deterministic_stake_accounts.ts
- fail when the stake account already exists (this is useful because otherwise it will lead to stuck proposals)
- print link to the proposal
> chore: xc-admin-cli improvements

- apps/staking/src/app/api/v1/locked_accounts/route.ts
Some locked account owners have complained about the past vesting dates appearing here
> fix: ignore vesting dates in the future

- apps/fortuna/Cargo.lock
- apps/fortuna/Cargo.toml
- apps/fortuna/src/chain/eth_gas_oracle.rs
This value is supposed to be strictly larger than the priority fee
> fix(fortuna): Adjust max_fee_per_gas to account for priority fee adjustments

- apps/insights/src/components/Publisher/layout.module.scss
- apps/insights/src/components/Publisher/layout.tsx
- apps/insights/src/components/Publisher/median-score-history.module.scss
- apps/insights/src/components/Publisher/median-score-history.tsx
- Highlight selected score more clearly
- Show name of selected score instead of "Score History"
- Move documentation button to the right and make it outline
> feat(staking): minor improvements to the median score drawer

- apps/insights/src/components/PriceFeed/publishers-card.tsx
- apps/insights/src/components/PriceFeeds/coming-soon-list.tsx
- apps/insights/src/components/PriceFeeds/price-feeds-card.tsx
- apps/insights/src/components/Publisher/performance.tsx
- apps/insights/src/components/Publisher/price-feeds-card.tsx
- apps/insights/src/components/Publishers/publishers-card.tsx
- packages/component-library/src/SearchInput/index.tsx
- packages/component-library/src/Table/index.module.scss
- Fix column widths so they don't change when the table is empty
- Add empty states to some tables that were missing them
- Add more useful search placeholders
> feat(insights): improve some minor table search UX items

- target_chains/solana/Cargo.lock
- target_chains/solana/programs/pyth-solana-receiver/Cargo.toml
- target_chains/solana/programs/pyth-solana-receiver/src/lib.rs
- target_chains/solana/pyth_solana_receiver_sdk/Cargo.toml
- target_chains/solana/pyth_solana_receiver_sdk/src/error.rs
- target_chains/solana/pyth_solana_receiver_sdk/src/price_update.rs
Performance and security improvements to the SVM TWAP feature.
- Perf optimization: Reused `slot_diff` calculation in `calculate_twap` 
- Security optimization: Previously, the SDK's `get_twap_no_older_than` function only checked that the twap's `end_time` was more recent than `maximum_age`. However, the window size of the twap wasn't checked. This could result in a scenario where an attacker could frontrun a transaction that consumes a hardcoded TwapUpdate PDA. The attacker could overwrite the account with a verified twap of an unexpected window (very long/short). This could have the effect of manipulating, for example, the LTV ratio calculation of a lending protocol. 
- The check has a +/- 1 second tolerance to account for Solana block time variations.
Updated SDK test suite
> fix(pyth-solana-receiver): improve perf and security

- lazer/Cargo.lock
- lazer/sdk/rust/protocol/Cargo.toml
- lazer/sdk/rust/protocol/src/api.rs
our apis should be similar to each other as much as possible.
> refactor!(lazer): update api protocol

- apps/fortuna/Cargo.lock
- apps/fortuna/Cargo.toml
- apps/fortuna/config.sample.yaml
- apps/fortuna/src/config.rs
- apps/fortuna/src/keeper.rs
This PR adds auto-scaling for the transaction gasLimit parameter when the callback fails. There seems to be an issue on abstract-testnet where some transactions hit this limit for unknown reasons.
I also drive-by fixed an error with the fee calculation.
> feat(fortuna): Dynamically increase gas limit for a transaction on failure

- governance/xc_admin/packages/xc_admin_common/src/__tests__/LazerMultisigInstruction.test.ts
- governance/xc_admin/packages/xc_admin_common/src/multisig_transaction/LazerMultisigInstruction.ts
- governance/xc_admin/packages/xc_admin_common/src/multisig_transaction/idl/lazer.json
- governance/xc_admin/packages/xc_admin_common/src/multisig_transaction/index.ts
I had to regenerate the lazer idl with anchor `0.29.0` and comment out `idl-build = ["anchor-lang/idl-build"]` for it to work otherwise all the existing idls on xc-admin will break if i used the idl from anchor `0.30.1` since the idl format changed
> feat(xc-admin): add support for deserializing lazer instructions in xc-admin

- governance/xc_admin/packages/xc_admin_common/src/deterministic_oracle_accounts.ts
On Pythnet, until now product and price accounts were created as seeded accounts with seed `product:{SYMBOL}` and `price:{SYMBOL}`. The problem is the seed can't exceed 32 characters. Some symbols in new price feeds are very long now like `Crypto.LIQUIDBERABTC/WBTC.RR` and fail at creation.
There are many solutions to this:
- slice the first 32 characters of the seed (bad because in the future there might be conflicts??? i.e. two symbols whose 24 first characters are the same but are not equal)
- hash the full seed and take the 32 first characters of the hash (this breaks the old way of doing things and will break all existing proposals since the seeded account needs to be computed at proposal).
> fix: seed too long

- apps/fortuna/Cargo.lock
- apps/fortuna/Cargo.toml
- apps/fortuna/src/keeper.rs
We're currently tracking gas, which is actually the compute units and not the amount in ETH that it costs.
Will bump version and apply on top of the other PR.
> feat(fortuna): Track amount spent on tx fees

- apps/fortuna/Cargo.lock
- apps/fortuna/Cargo.toml
- apps/fortuna/src/config.rs
- apps/fortuna/src/keeper.rs
Two simple changes here
* add a padding multiplier for the gas limit so that the keeper is willing to submit txs that slightly exceed the limit. I noticed a few failing txs in mainnet that are at ~510k gas, which could happen due to differences in the number of hashes. This defaults to 10% and that number should probably be fine without configuration.
* support negative target profit percentages. It turns out that for abstract-testnet, you get a gas refund at the end of the tx which is like 50% of the tx cost. However, you need to set the priority fee *without counting this refund*. Given that, we're systematically overestimating the needed fee.
> feat(fortuna): Add a couple more config values

- lazer/contracts/solana/programs/pyth-lazer-solana-contract/src/lib.rs
- lazer/contracts/solana/programs/pyth-lazer-solana-contract/src/signature.rs
- lazer/contracts/solana/programs/pyth-lazer-solana-contract/tests/test1.rs
- Disallow config account migration if it's already migrated. Repeatedly applied migration could overwrite the config account in an invalid way.
- Fetch message data from the instructions sysvar based on the signature program arguments when verifying instead of trusting the caller to pass correct `message_data` and `message_offset`. Generally, it was the caller contract's responsibility to make sure they specify `message_data` and `message_offset` correctly regardless of the untrusted input. However, this looks unsafe in non-CPI scenario (even though that scenario is not intended for use) and opens a possibility of an incorrect use via CPI. The new approach does not require passing `message_offset` and verifies that `message_data` equals the data at the offset for the verified signature.
> Lazer solana audit fixes

- apps/hermes/client/js/README.md
This pull request corrects the function name from getStreamingPriceUpdates to getPriceUpdatesStream in the README.md file.  The previous name was incorrect and did not match the actual function implementation.
> docs(hermes-client): Correct function name from getStreamingPriceUpdates to getPriceUpdatesStream in README.md

- .github/workflows/ci-lazer-solana-contract.yml
- lazer/contracts/solana/package.json
- lazer/contracts/solana/turbo.json
I was going to fix this so that it installs pnpm properly to use the correct version, however as it turns out this is actually redundant since we already run tests with https://github.com/pyth-network/pyth-crosschain/blob/main/.github/workflows/ci-turbo-test.yml so there's really no reason to duplicate the tests here as well.
> chore: remove node tests from solana lazer contract workflow

- apps/hermes/server/Cargo.lock
- apps/hermes/server/Cargo.toml
this fixes the `v2/price_feeds` endpoint not returning the full list of supported assets as the old version of `pyth-sdk-solana` was hardcoded at 640 price feeds max
> chore(apps/hermes): bump pyth-sdk-solana to v0.10.3

- apps/hermes/client/js/README.md
- apps/hermes/client/js/package.json
- apps/hermes/client/js/src/HermesClient.ts
Also fix an incorrect example in the readme
> fix(hermes-client): ensure relative urls are built properly

- lazer/Cargo.lock
- lazer/sdk/rust/protocol/Cargo.toml
- lazer/sdk/rust/protocol/src/publisher.rs
- lazer/sdk/rust/protocol/src/subscription.rs
Add a type for Lazer publisher errors. This will let us gracefully return an error if they send us a malformed binary update rather than just drop the websocket.
> feat(pyth-lazer-protocol): add pub error type

- apps/staking/src/components/Root/i18n-provider.tsx
- governance/xc_admin/packages/xc_admin_frontend/components/InstructionViews/WormholeInstructionView.tsx
- governance/xc_admin/packages/xc_admin_frontend/components/tabs/Proposals/Proposal.tsx
- pnpm-lock.yaml
See https://pnpm.io/cli/dedupe
> chore: run `pnpm dedupe`

- apps/staking/src/app/api/v1/cmc/supply/route.ts
CMC needs this to return as a number, not as a string.
This PR also cleans up the code a bit.
> fix(staking): match cmc endpoint format to expected format

- lazer/Cargo.lock
- lazer/sdk/rust/protocol/Cargo.toml
- lazer/sdk/rust/protocol/src/publisher.rs
rename `PublisherResponse` -> `ServerResponse` to better communicate that this is a message generated by the server.
> refactor(pyth-lazer-protocol): rename PublisherResponse -> ServerResponse

- .github/workflows/ci-message-buffer-idl.yml
- .github/workflows/ci-pre-commit.yml
The rocksdb version we use in message buffer has a bug that prevents it from building on g++ 13. This PR sets up g++ 12 to fix the build. It also adds a missing libssl1.1 library.
> chore: downgrade g++ to fix librocksdb-sys build in CI

- apps/insights/src/components/PriceComponentDrawer/index.tsx
- apps/insights/src/components/PriceFeed/publishers.tsx
- Make prices smaller in price component drawer
- Hide test components for now - I need to do some more work to ensure the live prices, drawer, and test components are working properly so for now I'll hide these until I can get that work done
> fix(insights): minor fixes

- contract_manager/store/chains/EvmChains.yaml
- contract_manager/store/tokens/Tokens.yaml
> chore(contract_manager): remove fantom token

- lazer/Cargo.lock
- lazer/sdk/rust/client/Cargo.toml
Fix `cargo publish` error: `dependency 'pyth-lazer-protocol' does not specify a version`
https://github.com/pyth-network/pyth-crosschain/actions/runs/13142447766/job/36672604599
> fix(pyth-lazer-client): specify protocol crate version to fix cargo publish

- lazer/Cargo.lock
- lazer/sdk/rust/client/Cargo.toml
- lazer/sdk/rust/protocol/Cargo.toml
- lazer/sdk/rust/protocol/src/router.rs
The current deserializer for the Channel type fails to work with string values loaded from toml by [config](https://crates.io/crates/config) -- the config crate is trying to deserialize an owned `String` but the deserializer expects a borrowed `&str`, causing this error: 
```
invalid type: string "fixed_rate@50ms", expected a borrowed string for key lazer.subscriptions[0]channel" 
```
Fixed by making the deserializer accept both `String` and `&str` (Serde will coerce a `&str` into a `String`).
Also threw in a minor clippy fix (`dev_dependencies` -> `dev-dependencies`).
> fix(pyth-lazer-protocol): deser Channel from String, not &str

- apps/staking/src/api.ts
- apps/staking/src/components/Root/index.tsx
- apps/staking/src/config/server.ts
- apps/staking/src/hooks/use-api.tsx
- governance/pyth_staking_sdk/src/pyth-staking-client.ts
Users that don't have SOL in their wallet can't see their claimable rewards.
I want to fix this by running the simulations with a fixed key that always has SOL, this is possible because claiming rewards for a user is actually permissionsless.
> fix: use key with sol for simulations

- lazer/Cargo.lock
- lazer/sdk/rust/client/Cargo.toml
Upgrade dep `pyth-lazer-protocol` to v0.4.2 so that the updated client can be used in `pyth-native`
> chore(pyth-lazer-client): upgrade dep `pyth-lazer-protocol`

- apps/hermes/client/js/package.json
- apps/hermes/client/js/src/HermesClient.ts
- pnpm-lock.yaml
This PR enables passing the `RequestInit` options for `fetch` to individual `HermesClient` methods.
This PR also fixes merging `AbortControllers`, which was previously not done correctly (but also no way to pass an `AbortController` was actually exposed via the public API, so this is not a breaking change), and upgrades typescript to the catalog version, which is required to support `AbortSignal.any`.
> feat(hermes-client): allow passing fetch options

- governance/xc_admin/packages/crank_pythnet_relayer/src/index.ts
If the relayer fails for whatever reason it is hard to debug what is going on. This change adds more logs to see the details of the proposals which is quite helpful in debugging the issues.
> refactor(governance/xc_admin): add more logs on relayer

- Dockerfile.node
The existing corepack version in the base node image that we have has some problems (on its keys) for installation. See https://github.com/nodejs/corepack/issues/612 for more details.
> fix: update corepack on js dockerfile

- .gitmodules
The same modules already exist at `target_chains/ethereum/sdk/stylus/pyth-mock-solidity/lib`. They shouldn't be in the root dir.
> chore: remove erroneous git modules

- .github/workflows/ci-fuel-contract.yml
- .github/workflows/ci-hermes-server.yml
- .github/workflows/ci-lazer-rust.yml
- .github/workflows/ci-near-contract.yml
- .github/workflows/ci-remote-executor.yml
- .github/workflows/ci-starknet-tools.yml
- .github/workflows/ci-stylus-nostd.yml
- .github/workflows/ci-sui-contract.yml
Reverts pyth-network/pyth-crosschain#2355 -- this broke the near workflow for some reason? Not sure what the problem is but I'm going to roll it back in the meanwhile
> Revert "feat: add rust-cache to all Rust workflows"

- target_chains/near/receiver/workspace-test.sh
Just to be sure that it builds with the dependency versions from the lock file.
> chore(target_chains/near): build with --locked in test

- .github/workflows/ci-near-contract.yml
Fix warning in GHA: 90 days is [the max for public repos](https://docs.github.com/en/organizations/managing-organization-settings/configuring-the-retention-period-for-github-actions-artifacts-and-logs-in-your-organization)
> Lower pyth_near build artifact retention to 90d

- .github/workflows/ci-ethereum-contract.yml
- .github/workflows/ci-pre-commit.yml
- apps/hermes/server/Cargo.lock
- target_chains/solana/Cargo.lock
CI on `main` is failing for two different reasons. (1) the Forge version wasn't pinned for the ethereum contract, and (2) the Cargo.lock file wasn't updated properly after a recent merge. The root cause of the 2nd item is that pre-commit is being run on a subset of files on PRs, which causes it to succeed on PRs then fail on main. I removed this option in the pre-commit check. This means pre-commit will run on all files, which will take longer, though it shouldn't be too long since I already added caching for all the Rust build stuff.
> chore: fix some more CI stuff

- apps/insights/src/components/PriceFeed/price-feed-select.tsx
- apps/insights/src/components/Root/index.tsx
- apps/insights/src/components/Root/search-dialog.tsx
This PR fixes a few related bugs:
- Safari doesn't support `Iterator.filter`, so we need to iterators that need to be filtered into arrays instead.
- The search dialog needs to be closed before triggering navigation or the close animation is janky
- The react-aria ids for publishers in the search dialog need to be disambiguated between clusters because a few publishers use the same keys in pythtest and pythnet
> fix(insights): fix some bugs relating to the search dialog

- apps/hermes/client/js/package.json
- apps/hermes/client/js/src/HermesClient.ts
- pnpm-lock.yaml
The 2.x version of eventsource requires polyfills to work in browsers, but the 3.x version does not.  The 3.x version is also modernized and ships its own types.
> chore(hermes-client): upgrade eventsource

- contract_manager/scripts/generate_upgrade_near_contract_proposal.ts
- contract_manager/src/contracts/near.ts
- contract_manager/store/contracts/NearPriceFeedContracts.yaml
- governance/xc_admin/packages/xc_admin_common/src/chains.ts
- Add propose upgrade script for near
- Manually track governance source and sequence to allow use of `sync_governance_vaas` script
- Remove near from `RECEIVER_CHAINS` because it's already in `WORMHOLE_CHAINS`
> feat(contract_manager): add support for near contract upgrade

- apps/price_pusher/package.json
- apps/price_pusher/src/solana/command.ts
- apps/price_pusher/src/solana/solana.ts
- target_chains/solana/sdk/js/pyth_solana_receiver/examples/post_price_update.ts
- target_chains/solana/sdk/js/pyth_solana_receiver/examples/update_price_feed.ts
- target_chains/solana/sdk/js/pyth_solana_receiver/package.json
- target_chains/solana/sdk/js/pyth_solana_receiver/src/PythSolanaReceiver.ts
- target_chains/solana/sdk/js/pyth_solana_receiver/src/vaa.ts
Recently our merkle proof size grew due to newly added feeds. This caused two `postUpdate` ixs to no longer fit inside a single tx. This resulted in us needing to use more transactions to land our updates, which means increased operational costs of running the price pusher.
This PR uses [Address Lookup Tables](https://solana.com/developers/guides/advanced/lookup-tables) to save space in order to fit 2 postUpdate ixs in a single tx again.
The following accounts are static and are indexed in the ALT: 
1. Pyth Solana Receiver
[rec5EKMGg6MxZYaMdyBfgwp4d5rB9T1VQH5pJv5LtFJ](https://explorer.solana.com/address/rec5EKMGg6MxZYaMdyBfgwp4d5rB9T1VQH5pJv5LtFJ)
2. Treasury (id 0):
[GakrHE9QQeeJKoZ6oww9qzJZrzXY7C1jZdVfpYHc6KSz](https://solscan.io/account/GakrHE9QQeeJKoZ6oww9qzJZrzXY7C1jZdVfpYHc6KSz)
3. …
> feat(price_pusher/solana): use an Address Lookup Table to reduce number of txs

- contract_manager/store/contracts/NearPriceFeedContracts.yaml
I've applied the VAA with seq no 408 on near mainnet.
> chore(target_chains/near): update last executed governance sequence

- .github/workflows/ci-pre-commit.yml
At the moment, pre-commit randomly takes the full 25 mins because it can't find the cache entry for the Rust build. I think what's happening is that we are evicting the `main` branch cache sometimes due to the Github cache size limit. (see inline comment for more details)
> chore: Update cache saving policy for github actions

- .github/workflows/ci-pre-commit.yml
My last change apparently introduced a syntax error in the workflow, and also disabled running it on pull requests 🤦
> chore: fix precommit workflow

- lazer/contracts/evm/src/PythLazer.sol
- lazer/contracts/evm/src/PythLazerLib.sol
- lazer/contracts/evm/test/PythLazer.t.sol
Fixed by using OpenZeppelin's ECDSA library instead of the raw ecrecover function.
Fixed by adding `_disableInitializers()` to the constructor. Updated tests to set up a proxy.
It's not possible to remove the `if update.length < 71` check because that would add a possibility of out-of-bounds access at the next line (`update[69:71]`).
Removed `migrate()`.
Removed unused import.
> fix(lazer): address evm contract audit

- .github/workflows/ci-ethereum-contract.yml
- .github/workflows/ci-message-buffer-idl.yml
- .github/workflows/ci-turbo-build.yml
- .github/workflows/ci-turbo-test.yml
- .github/workflows/publish-js.yml
Add libusb to github action runners (where `pnpm install` is needed)
One of our node dependencies, `node-hid`, is a native extension which depends on `libusb`.  In the past this dependency has distributed precompiled binaries so it wasn't necessary to have `libusb` because usually the compile wouldn't be required as part of the install.    However, it seems something has changed and those precompiled binaries are no longer being found reliably, and so we need to make sure we have `libusb` available wherever we do a `pnpm install` in case a build is needed.
N/A, if CI succeeds then it works.
> fix: add libusb to github action runners that do pnpm install

- apps/insights/src/components/PriceComponentDrawer/index.module.scss
- apps/insights/src/components/PriceComponentDrawer/index.tsx
Fixes an issue where the items in the price component drawer would stretch to fill the height, resulting in jumping after loading and stretching on tall screens.
Fixes a display bug.
> fix(insights): fix feed component drawer stretching on large screens

- apps/insights/src/components/Publisher/layout.module.scss
- apps/insights/src/components/Publisher/layout.tsx
Fix OIS infobox not properly spanning columns
Before:
After:
> fix(insights): fix ois info box not spanning columns

- apps/insights/src/components/Overview/index.tsx
Include the live count of price feeds as a final data point after the kpi history metrics in the insights hub Overview tab metric cards.
Previously, we only displayed the historical values for the number of price feeds.  However, since we're adding price feeds fairly fast, this means there's an obvious discrepancy between the last data point for the number of feeds which shows up in the metric card in the Overview page and the much higher number of feeds that you see on the price feeds page.
This PR solves the problem by including a data point for today's value along with the KPI metrics.
TBH it's a bit janky because this means the amount of time between the last two data points much less than between any other two points -- all other points will have a month between them but the last …
> fix(insights): add live price feeds count to the end of kpi metrics

- apps/insights/src/components/CopyButton/index.module.scss
- apps/insights/src/components/CopyButton/index.tsx
- apps/insights/src/components/EntityList/index.module.scss
- apps/insights/src/components/PriceFeed/layout.module.scss
- apps/insights/src/components/PriceFeed/layout.tsx
- apps/insights/src/components/PriceFeeds/price-feeds-card.module.scss
- apps/insights/src/components/PriceFeeds/price-feeds-card.tsx
- apps/insights/src/components/Publisher/layout.tsx
- apps/insights/src/components/PublisherKey/index.module.scss
- apps/insights/src/components/PublisherKey/index.tsx
- apps/insights/src/components/PublisherTag/index.module.scss
- apps/insights/src/components/PublisherTag/index.tsx
Implement the new `CopyButton` component design.
> feat(insights): implement new CopyButton design

- .github/CODEOWNERS
CODEOWNERS for GH workflows, CODEOWNERS itself
Reduce the chances of PRs to use the [medium or large runners](https://github.com/pyth-network/pyth-crosschain/pull/2431) racking up our spend
Only via the GH verification:
> This CODEOWNERS file is valid.
I don't believe we can fully test until it's merged.
> chore(ci): update reviewers for /.github/ and CODEOWNERS

- .github/workflows/ci-lazer-solana-contract.yml
- .github/workflows/ci-turbo-test.yml
- lazer/contracts/solana/turbo.json
Move anchor tests back to a separate workflow. 
Solana contract brings too many new dependencies (Rust, Solana SDK, anchor) to `pnpm test` so it complicates the setup process for pnpm users a lot.
Adjusted CI tests.
> chore: move lazer contract tests out of pnpm test

- lazer/Cargo.lock
- lazer/contracts/solana/programs/pyth-lazer-solana-contract/Cargo.toml
- lazer/contracts/solana/programs/pyth-lazer-solana-contract/src/lib.rs
- lazer/contracts/solana/programs/pyth-lazer-solana-contract/src/signature.rs
- lazer/contracts/solana/programs/pyth-lazer-solana-contract/tests/test1.rs
- Support LeEcdsa payload in Solana contract
- Track EVM addresses in Solana contract for ECDSA verification
Consumers asked for it.
> feat(lazer): support ecdsa signers in solana contract

- contract_manager/scripts/common.ts
- contract_manager/scripts/deploy_evm_entropy_contracts.ts
- contract_manager/scripts/deploy_evm_pulse_contracts.ts
- contract_manager/src/contracts/evm.ts
- contract_manager/src/contracts/evm_abis.ts
- contract_manager/src/store.ts
- target_chains/ethereum/contracts/contracts/pulse/IPulse.sol
- target_chains/ethereum/contracts/contracts/pulse/Pulse.sol
Added deployment script for Pulse contracts on EVM chains with configurable initialization parameters. This includes:
- New `deploy_evm_pulse_contracts.ts` script for deploying PulseUpgradeable and ERC1967Proxy
- Added `EvmPulseContract` class for interacting with deployed Pulse contracts
- Fixed bytecode handling in `deployIfNotCached` to support different bytecode formats
These changes are necessary to:
1. Support deployment of Pulse contracts across different EVM chains
2. Allow customization of contract initialization parameters via CLI
3. Fix bytecode handling issues with different compiler outputs (object vs string)
4. Provide a consistent interface for interacting with Pulse contracts after deployment
I've manually tested the deployment script on multiple EVM chains (Linea Sepolia, …
> feat(contract_manager): add deploy_evm_pulse_contracts script

- governance/xc_admin/packages/xc_admin_frontend/components/tabs/General.tsx
- support renaming a symbol
- set maxLatency upon feed creation
These two are features/requests from price feeds ops council.
I checked it manually through the UI and logs to ensure the new instruction for updating metadata gets created.
> chore(governance/xc_admin): add a few features to frontend

- lazer/Cargo.lock
- lazer/sdk/rust/protocol/Cargo.toml
- lazer/sdk/rust/protocol/src/api.rs
- lazer/sdk/rust/protocol/src/router.rs
Changes needed to support price request (historical prices with signatures)
Our users need this api
Manually tested the api
> feat(pyth-lazer-protocol): add price request

- apps/fortuna/Cargo.lock
- apps/fortuna/Cargo.toml
- apps/fortuna/src/eth_utils/utils.rs
- apps/fortuna/src/keeper/process_event.rs
> fix(fortuna): Propagate submission errors correctly

- .github/workflows/ci-pre-commit.yml
The pre-commit cache expired and on re-download, it's causing some solana-net build error. Presumably solana semver is broken somewhere but I'm not sure. CI is also taking 30 mins right now which is going to block everyone.
I'm disabling pre-commit on prs temporarily while I debug to unblock people. I will reenable and fix any problems after.
> chore: Pause pre-commit on branches

- apps/fortuna/Cargo.lock
- apps/fortuna/Cargo.toml
- apps/fortuna/src/eth_utils/utils.rs
Add in the calculation of the padded gas limit. I dropped this padding value during the refactor. This is probably responsible for the current set of gas estimation issues.
> fix(fortuna): Fix gas padding bug caused by refactor

- .github/workflows/ci-pre-commit.yml
- .pre-commit-config.yaml
Partially resume pre-commit CI. The problem is that a dependency of the pythnet_sdk has updated so that it now requires a newer rust version. Upgrading our rust version causes other problems however. The right fix to this is probably to add a Cargo.lock file (but I don't have one unfortunately). 
Luckily the failure happens in the test package, so as a temporary stopgap turn off the test part of the clippy check.
> chore: (partially) resume pre-commit CI action

- contract_manager/store/chains/TonChains.yaml
i think this was broken during the refactor here https://github.com/pyth-network/pyth-crosschain/pull/2160/files#diff-b0c3a1ff52c917a976a1a4b2b91011340840e9253d92a5b4b3dda2df366d8d21R4-R6
> fix(contract_manager): ton rpc url

- target_chains/ethereum/contracts/contracts/pulse/IPulse.sol
- target_chains/ethereum/contracts/contracts/pulse/Pulse.sol
- target_chains/ethereum/contracts/contracts/pulse/PulseErrors.sol
- target_chains/ethereum/contracts/contracts/pulse/PulseEvents.sol
- target_chains/ethereum/contracts/contracts/pulse/PulseState.sol
- target_chains/ethereum/contracts/forge-test/Pulse.t.sol
I was looking through the Pulse contract and noticed some issues:
* There's a security issue with the IPulseConsumer interface as anyone can mock data and pass it as the legitimate response to the request
* publishTimes are unix timestamps so should be uint64
* The provider fee / backup mechanism doesn't work properly because it doesn't account for pyth fees, and it also doesn't give any incentive to backup providers.
> fix(pulse): Miscellaneous contract fixes

- apps/api-reference/vercel.json
- apps/entropy-debugger/vercel.json
- apps/insights/vercel.json
- apps/staking/vercel.json
- governance/xc_admin/packages/xc_admin_frontend/vercel.json
- packages/component-library/vercel.json
Vercel's ignore command hasn't been reliably working, resulting in a ton of Vercel noise on PRs that aren't touching apps and a ton of unneeded builds.
I have been going back and forth with Vercel for a while and recently received this message:
> Hi Connor,
>
> Thanks for your patience. 
>
> I received an update from the Engineering team indicating that this appears to be a bug where ENABLE_EXPERIMENTAL_COREPACK is not properly detected during the ignore build step. We apologise for any inconvenience this may have caused. To resolve the issue, could you please remove the environment variable ENABLE_EXPERIMENTAL_COREPACK from the project settings and create a vercel.json file with the following code?
> {
>   "$schema": "https://openapi.vercel.sh/vercel.json",
>   "env": {
> …
> Fix vercel ignore command

- lazer/contracts/aptos/Move.toml
- lazer/contracts/aptos/tests/pyth_lazer_tests.move
Fix Aptos contract CI by explicitly creating a coin conversion map in the test setup.
A recent update to the `AptosFramework` dependency made it required to explicitly define a coin conversion map when initializing a coin. We init an APT coin in tests to verify fee withdrawals. Since our dep was pointed to `mainnet`, this caused CI to randomly start failing. This fix adheres to the requirement and also pins the version to the latest revision to avoid other surprises from deps.
> fix(lazer/aptos-contract): add coin conversion map to tests

- contract_manager/store/chains/EvmChains.yaml
- contract_manager/store/contracts/EvmEntropyContracts.yaml
- contract_manager/store/contracts/EvmPriceFeedContracts.yaml
- contract_manager/store/contracts/EvmWormholeContracts.yaml
- governance/xc_admin/packages/xc_admin_common/src/chains.ts
> chore(deployments) Story Testnet

- pnpm-lock.yaml
- target_chains/sui/cli/README.md
- target_chains/sui/cli/turbo.json
- target_chains/sui/sdk/js/README.md
- target_chains/sui/sdk/js/package.json
- target_chains/sui/sdk/js/src/examples/SuiRelay.ts
- target_chains/sui/sdk/js/turbo.json
Updated SUI JS SDK and CLI to use Turbo to help with dependency management. Updated the README to reflect this. Also fixed the relay example to use feed ids as string instead of number. 
There were a litany of issues getting the SUI JS SDK and CLI to work at all. I got help from Connor to figure out what is wrong and how to fix it. Now, the examples should work out of box and without too much trouble. 
Manually tested by cleaning up repo locally using `git clean -fdx` and then installing with pnpm in root. Then, running examples and cli commands using turbo successfully.
> feat(target_chains/sui): Use Turbo for Commands

- apps/staking/src/components/Header/help-menu.tsx
- apps/staking/src/components/Header/index.tsx
- apps/staking/src/components/Header/stats.tsx
This PR fixes the staking app header to not overlap on some screen sizes.
I suppose when we added the Governance Total Staked section, we didn't properly test across all screen sizes, and the header looks  broken on some.
Before:
After:
> fix(staking): fix header to not overlap on small screen sizes

- apps/staking/src/components/AccountSummary/index.tsx
- apps/staking/src/components/Header/current-stake-account.tsx
- apps/staking/src/components/Header/index.tsx
- apps/staking/src/components/Header/stats.tsx
- apps/staking/src/components/Root/index.tsx
- apps/staking/src/components/WalletButton/index.tsx
More fixes for #2482 .
The fix in #2482 did not account for the header state when the wallet is connected, which additionally shows the current stake account and requires more space.
Before:
After:
> fix(staking): fix header on small screens 2: This Time It's Personal

- .github/workflows/ci-turbo-build.yml
- .github/workflows/ci-turbo-test.yml
- .github/workflows/publish-js.yml
I discovered that these tasks all install libusb twice, probably due to separate branches including similar fixes that were open at the same time.  This PR removes the redundant installation.
> fix: remove redundant libusb install

- apps/argus/Cargo.lock
- apps/argus/src/api.rs
- apps/argus/src/chain/ethereum.rs
- apps/argus/src/chain/reader.rs
- apps/argus/src/command/run.rs
- apps/argus/src/keeper.rs
- apps/argus/src/keeper/block.rs
- apps/argus/src/keeper/process_event.rs
Deletes the read-only mock contract for Entropy, which was only used by the fortuna web api.
> feat(argus): Delete more unneeded logic

- pnpm-workspace.yaml
- target_chains/ethereum/sdk/js/README.md
- target_chains/ethereum/sdk/solidity/PythAggregatorV3.sol
- target_chains/ethereum/sdk/solidity/README.md
> deprecate(pyth-evm-js): Add deprecation notice

- packages/component-library/.storybook/preview.tsx
Fix the storybook background config.
The api for this changed in some storybook version between when I implement it originally and now, and I just noticed it isn't working since the storybook has been intermittently broken for a while.  This PR fixes it.
> fix: fix storybook background color

- .github/workflows/ci-ethereum-contract.yml
- .github/workflows/ci-lazer-solana-contract.yml
- .github/workflows/ci-message-buffer.yml
- .github/workflows/ci-turbo-build.yml
- .github/workflows/ci-turbo-test.yml
- .github/workflows/publish-js.yml
Installing node packages requires libusb & libudev due to some native extensions that get compiled during install.  However this started failing today, presumably due to package upgrades in the upstream repository.
This PR fixes the libusb & libudev install to do an `apt-get update` before installing the packages.
CI is currently failing on tasks that require these libs.
We'll see when the Github Actions trigger
> fix: fix installing libusb in github actions

- .gitignore
- apps/api-reference/vercel.json
- apps/entropy-debugger/vercel.json
- apps/insights/vercel.json
- apps/staking/vercel.json
- governance/xc_admin/packages/xc_admin_frontend/vercel.json
- packages/component-library/vercel.json
- vercel-ignore.sh
It seems like vercel does not correctly use corepack during the `ignoreCommand`, which was the cause of the flakiness with ignoring builds for so long.
We thought we had fixed it in #2468 , but it turns out this doesn't actually work -- it seems like Vercel does not properly apply env vars from the `vercel.json` config file -- so in effect that just disabled corepack entirely.  It wasn't a huge issue as Vercel was choosing a close enough version of pnpm by default, but it would be better to actually use corepack and ensure Vercel is using the exact same version of pnpm that we are locked to in the monorepo.
This PR, along with readding the `ENABLE_EXPERIMENTAL_COREPACK` env var via the Vercel dashboard, should both re-enable corepack on builds AND fix the `ignoreCommand` to properly use …
> fix: fix vercel's use of corepack during the ignoreCommand

- apps/hermes/server/Cargo.lock
- apps/hermes/server/Cargo.toml
- apps/hermes/server/src/api/rest/v2/sse.rs
- apps/hermes/server/src/state/aggregate.rs
- apps/hermes/server/src/state/aggregate/wormhole_merkle.rs
- apps/hermes/server/src/state/cache.rs
The application was experiencing an issue where multiple events could be sent for the same slot under certain conditions:
1. When a slot was processed out of order (e.g., slot 100, then 101, then 100 again), the system would send both a `New` event and an `OutOfOrder` event for the same slot.
2. During concurrent processing of updates for the same slot, race conditions could lead to duplicate events being sent.
This resulted in downstream consumers (like SSE clients) receiving redundant events, which could cause unnecessary processing and potential bugs.
We implemented a more efficient mechanism to ensure that only one event is ever sent per slot:
1. Modified `store_wormhole_merkle_verified_message` to check if a state already exists for the given slot before storing it, returning a …
> fix(apps/hermes): fix duplicate events for processed slots

- .github/workflows/ci-lazer-solana-contract.yml
Add `--locked` to `cargo install` and build it on rustc 1.79 because it doesn't build on 1.80 or later.
Build was failing because a dependency required newer rustc.
> chore(lazer): add locked to anchor install in CI

- pnpm-lock.yaml
This PR rebuilds the `pnpm-lock.yaml` file again.
It seems some recent commit merged some changes to the lockfile that were made before all the lockfile maintenance recently was done, which appears to have effectively reverted the wallet ui dependency updates for the proposals app, and has broken the wallet UI.
> fix: rebuild lockfile again

- apps/price_pusher/config.solana.mainnet.sample.json
- apps/price_pusher/config.solana.testnet.sample.json
- apps/price_pusher/package.json
- apps/price_pusher/src/solana/balance-tracker.ts
- apps/price_pusher/src/solana/command.ts
> feat(apps/price_pusher): update price config file references, add Solana balance tracker, and enable metrics

- lazer/contracts/evm/src/PythLazer.sol
Add a mapping to allow quick check of trusted signer.
Asked by a consumer.
> feat(lazer): add mapping to improve efficiency of evm contract

- target_chains/solana/Cargo.lock
- target_chains/solana/pyth_solana_receiver_sdk/Cargo.toml
Remove the solana-program<2 bound in our `pyth-solana-receiver-sdk` dependencies to enable using the SDK with anchor 0.31.0.
- `anchor-lang` v0.31.0 requires `solana-program=^2`. Thus, this change enables using anchor 0.31.0 with our SDK. This change has been requested by a few consumers. 
- `bytemuck_derive` has been restricted to <=1.8.1 since after this version, minimum rust version 1.84 is required, which breaks compatibility with the other packages in the workspace.
- We did not bump the minimum anchor version to 0.31.0 since solana-program ^2 requires a higher rust version, which would also break compatibility with other packages in the workspace.
- Once this lands, I'll publish [this repo](https://github.com/guibescos/anchor-pyth/tree/v0.30.1) to our GH org which shows a example of …
> chore(pyth-solana-receiver-sdk): enable solana-program >= 2 (and thus anchor-lang 0.31.0)

- contract_manager/store/chains/CosmWasmChains.yaml
- contract_manager/store/contracts/CosmWasmPriceFeedContracts.yaml
- contract_manager/store/contracts/CosmWasmWormholeContracts.yaml
- pnpm-lock.yaml
- target_chains/cosmwasm/deploy-scripts/README.md
- target_chains/cosmwasm/deploy-scripts/package.json
- target_chains/cosmwasm/deploy-scripts/src/instantiate-wormhole.ts
- target_chains/cosmwasm/tools/src/chains-manager/cosmwasm.ts
Deploy cosmwasm to xion_testnet_2. Also removes the previous xion deployment as it doesn't exist anymore.
> chore(target_chains/cosmwasm): replace xion_testnet with xion_testnet_2

- apps/fortuna/Cargo.lock
- apps/fortuna/Cargo.toml
- apps/fortuna/src/eth_utils/utils.rs
- apps/fortuna/src/keeper/process_event.rs
Retry if tx receipt indicates failure
> fix(fortuna): Retry if receipt indicates failure

- apps/hermes/server/Cargo.lock
- apps/hermes/server/Cargo.toml
- apps/hermes/server/src/api/rest.rs
- apps/hermes/server/src/api/rest/v2/latest_twaps.rs
- apps/hermes/server/src/state/aggregate.rs
- apps/hermes/server/src/state/cache.rs
This PR refactors how Hermes fetches the data for the TWAP calculation to improve reliability. 
- The internal API for TWAP now accepts `window_seconds: u64` and `end_time: RequestTime`, instead of `start_time: RequestTime` and `end_time: RequestTime`.
- This allows us to first fetch the end messages, then calculate the `start_time` based on the publish time of the end messages. Previously, the actual time difference between start and end messages could differ from the intended window size since the latest timestamp in the cache could be older than the wall time. This change guarantees that the start and end messages are `window_seconds` apart.
- This also aligns better with the semantics we want to uphold for the public API.
- Added a new `RequestTime::LatestTimeEarliestSlot` request …
> fix(hermes): improve TWAP reliability - non-optional price selection and consistent time windows

- .github/workflows/ci-turbo-build.yml
- .github/workflows/publish-js.yml
- apps/api-reference/package.json
- apps/api-reference/turbo.json
- apps/api-reference/vercel.json
- apps/insights/package.json
- apps/insights/turbo.json
- apps/insights/vercel.json
- apps/staking/package.json
- apps/staking/turbo.json
- apps/staking/vercel.json
- package.json
- turbo.json
Do not build packages that rely on the Vercel environment using `turbo build`, instead move them to build with `turbo build:vercel`
For many of our UI applications, in order to build the package, a number of environment variables must be present.
The values for these env vars are stored in Vercel, however not everyone who contributes to this repository will have access to Vercel.
This PR modifies the turbo config to not build those packages on `turbo build`. This is generally probably the right thing since we don't want those packages to build in Github Actions either, given the environment is not going to be present in GHA and so the builds would likely fail there too.
After this PR, to build any packages that rely on Vercel environments, you will run `turbo build:vercel`.  Running …
> Only build stuff that requires Vercel env to build on Vercel

- apps/entropy-debugger/src/store/entropy-deployments.ts
Official Conflux blockchain explorer ConfluxScan is now live with new domain links. This PR updates the ConfluxScan link.
Check the official announcement here: https://forum.conflux.fun/t/confluxscan-domain-update-announcement-march-28-2025/21920
> chore: update ConfluxScan link

- apps/price_pusher/package.json
- apps/price_pusher/src/solana/solana.ts
> chore(apps/price_pusher): update jito bundle endpoint

- apps/fortuna/Cargo.lock
- apps/fortuna/Cargo.toml
- apps/fortuna/src/keeper/fee.rs
Reject setting the fees too high
We estimate priority fees similar to how ethers.rs library does it. This is the general algo:
1- Get the priority fees of the last 10 blocks
2- Sort them
3- Get the median OR if there is any sudden increase, take the median from that index forward  (https://github.com/gakonst/ethers-rs/blob/master/ethers-core/src/utils/mod.rs#L590)
Now the way priority fees are calculated for a block is just the average of priority fees for the transactions in that block. So if a block (https://berascan.com/block/2933426) only includes a single tx with very high priority fee, that would be overall priority fee for that block. So what happened for fortuna is we took that priority fee (because of that sudden increase heuristic) and set our fees according to that and that led …
> fix(fortuna): fix too high fees

- apps/insights/src/components/Explanations/index.tsx
- apps/insights/src/components/Publishers/index.tsx
- apps/insights/src/components/Publishers/publishers-card.tsx
- apps/insights/src/services/clickhouse.ts
Adds a "Permissioned Feeds" column to the publisher list in Insights Hub.
The ranking is hard to understand without this column, so adding this column helps making the ranking information obvious.
> feat(insights): add permissioned feeds column to the publisher list

- contract_manager/src/contracts/evm.ts
> chore(contact-manager) Fix Fetch fees script

- .dockerignore
- apps/argus/Cargo.lock
- apps/hermes/server/Cargo.lock
- apps/hermes/server/Cargo.toml
- apps/hermes/server/src/config.rs
- apps/hermes/server/src/config/cache.rs
- apps/hermes/server/src/main.rs
Make the cache size configurable, bump default to 1600 slots. 
This was motivated by the need to store more 1000 slots (400s) of data in Hermes to serve TWAPs from. The size is now configurable with a default of 1600 slots (640s), which is sufficient for our advertised max of 600s.
> feat(hermes): configurable cache size

- apps/staking/src/components/WalletTester/index.tsx
- apps/staking/src/middleware.ts
Adds better feedback when testing wallets
Currently the feedback only feels nice if your wallet pops up, but e.g. if you use walletconnect you don't get a popup so the app looks like it isn't doing anything after you click "test"
> feat(staking): improve tester app feedback

- pythnet/pythnet_sdk/src/wire.rs
add test for update data with fixture
This is a good test but also a good tool to deserialize update data for troubleshooting. If we get many requests to parse the update data we can add it as an API to Hermes or make a CLI for it but I don't think it's necessary for now.
> refactor(pythnet/pythnet_sdk): add test for update data with fixture

- apps/staking/src/app/api/v1/amount_staked_per_account/route.ts
- apps/staking/src/config/server.ts
- apps/staking/turbo.json
- governance/pyth_staking_sdk/package.json
- governance/pyth_staking_sdk/src/pyth-staking-client.ts
- governance/pyth_staking_sdk/src/utils/position.ts
- pnpm-lock.yaml
Adds an endpoint to the staking app to return a stake summary per account.
This is required to calculate Fogo flames
> feat: add a staking endpoint to return a stake summary per account

- governance/pyth_staking_sdk/src/pyth-staking-client.ts
> chore(staking-sdk): add logging to debug amount_staked_per_account

- governance/pyth_staking_sdk/package.json
- governance/pyth_staking_sdk/src/pyth-staking-client.ts
This PR bumps the staking-sdk version in preparation for release.  I also remove some debug logging I'd added in #2561  and improve error handling a bit.
I need to release the updated version of the staking sdk for use in fogo points and I need to clean up the logging before I can do that.
> chore(staking-sdk): rev staking-sdk version

- .github/CODEOWNERS
- .github/workflows/publish-js.yml
- governance/pyth_staking_sdk/package.json
- lerna.json
- package.json
- pnpm-lock.yaml
- pnpm-workspace.yaml
We need to use `pnpm publish` instead of `lerna publish` now that we're using catalogs, because pnpm is responsible for resolving the catalogs into real dependencies.
This PR also bumps staking-sdk since the published version currently has unresolved catalog dependencies.
> fix: use pnpm to publish instead of lerna

- .github/workflows/publish-js.yml
Add `--no-git-checks` to the pnpm publish command.
Without this, pnpm fails to publish off a tag as it believes we're not on a publish branch.
> fix: set --no-git-checks on pnpm publish

- .github/workflows/ci-fortuna.yml
- apps/fortuna/src/command/inspect.rs
- target_chains/ethereum/entropy_sdk/solidity/abis/EntropyStatusConstants.json
- target_chains/ethereum/entropy_sdk/solidity/package.json
I renamed a variable in the entropy contract, which broke Fortuna (which depends on the ABI). Update to use the new variable name.
In the process I exported the ABI for the entropy constants. Unfortunately, it's not easy to use this library in ethers.rs because the ABI looks like a contract and doesn't have the constant values in it. 
I also added the ABI directory to the fortuna CI to prevent similar issues going forward.
> fix(fortuna): Fix fortuna CI

- governance/pyth_staking_sdk/eslint.config.js
- governance/pyth_staking_sdk/package.json
- governance/pyth_staking_sdk/src/pyth-staking-client.ts
- governance/pyth_staking_sdk/src/utils/pool.ts
Some more fixes / improvements to staking-sdk:
- Don't disable eslint rules unnecessarily
- Ensure we handle `Uint8Array`s in the response body too
- Throw an explicit error if we reach the end of the stream without finding a result
> fix(staking-sdk): more staking-sdk improvements

- target_chains/cosmwasm/examples/cw-contract/Cargo.lock
- target_chains/ethereum/contracts/contracts/pyth/Pyth.sol
- target_chains/ethereum/contracts/contracts/pyth/PythAccumulator.sol
- target_chains/ethereum/contracts/contracts/pyth/PythInternalStructs.sol
- target_chains/ethereum/contracts/forge-test/Pyth.t.sol
- target_chains/ethereum/contracts/forge-test/utils/PythTestUtils.t.sol
- target_chains/ethereum/contracts/package.json
- target_chains/ethereum/sdk/solidity/AbstractPyth.sol
- target_chains/ethereum/sdk/solidity/IPyth.sol
- target_chains/ethereum/sdk/solidity/IPythEvents.sol
- target_chains/ethereum/sdk/solidity/MockPyth.sol
- target_chains/ethereum/sdk/solidity/PythErrors.sol
- target_chains/ethereum/sdk/solidity/PythStructs.sol
- target_chains/ethereum/sdk/solidity/PythUtils.sol
- target_chains/ethereum/sdk/solidity/abis/AbstractPyth.json
- target_chains/ethereum/sdk/solidity/abis/IPyth.json
- target_chains/ethereum/sdk/solidity/abis/IPythEvents.json
- target_chains/ethereum/sdk/solidity/abis/MockPyth.json
- target_chains/ethereum/sdk/solidity/abis/PythErrors.json
- target_chains/ethereum/sdk/solidity/abis/PythUtils.json
- target_chains/fuel/contracts/Cargo.lock
- target_chains/near/example/Cargo.lock
- Added comprehensive TWAP (Time-Weighted Average Price) functionality to the Pyth contract system including:
- New data structures: `TwapPriceFeed`, `TwapPriceInfo`, `TwapPriceFeedMessage`
- New methods for TWAP calculations and updates
- Optimized fee structure for TWAP updates
- Added extensive test coverage including negative test cases
- Added new error types for TWAP-related validation
These changes are necessary to:
1. Support TWAP price feed calculations which provide more stable price data by averaging over time
2. Improve UX by optimizing fee structure (charging for single update instead of both updates)
3. Ensure robust error handling for TWAP-related operations
4. Keep dependencies up to date for security and compatibility
5. Maintain code quality through comprehensive test …
> feat(target_chains/ethereum): add twap

- contract_manager/store/chains/CosmWasmChains.yaml
- contract_manager/store/contracts/CosmWasmPriceFeedContracts.yaml
- contract_manager/store/contracts/CosmWasmWormholeContracts.yaml
- contract_manager/store/contracts/NearPriceFeedContracts.yaml
- governance/xc_admin/packages/xc_admin_common/src/chains.ts
This PR adds the specs of Pyth deployment on Xion Mainnet.
> chore(target_chains/cosmwasm): add xion mainnet

- .github/workflows/publish-rust-lazer-publisher-sdk.yml
Minor typo in publish script causes it to fail. 
To publish lazer publisher sdk to crates
> fix: Publish Script for Lazer Publisher SDK

- target_chains/ethereum/contracts/contracts/entropy/Entropy.sol
- target_chains/ethereum/contracts/forge-test/Entropy.t.sol
- target_chains/ethereum/entropy_sdk/solidity/EntropyErrors.sol
- target_chains/ethereum/entropy_sdk/solidity/EntropyEvents.sol
- target_chains/ethereum/entropy_sdk/solidity/EntropyStructs.sol
- target_chains/ethereum/entropy_sdk/solidity/IEntropy.sol
- target_chains/ethereum/entropy_sdk/solidity/abis/EntropyErrors.json
- target_chains/ethereum/entropy_sdk/solidity/abis/EntropyEvents.json
- target_chains/ethereum/entropy_sdk/solidity/abis/IEntropy.json
Follow up to the last PR around allowing providers to mark on-chain callbacks as failed. The previous PR covers cases where the contract manually reverts. This PR covers the case where the callback runs out of gas. 
This PR gives each callback a gas limit which is stored in the on-chain struct. Providers can set a default gas limit, or users can manually specify a different gas limit when making a request. We mark callbacks as failed if they revert with an out-of-gas error *and* the transaction had enough gas to forward -- there are some EVM nuances here that we need to be careful about. See inline comments for details.
Explicitly marking on-chain requests as failed will make the state transitions of entropy much clearer to end users.
> feat(entropy): Add on-chain gas limits and mark out-of-gas failures on-chain

- apps/staking/src/components/WalletTester/index.tsx
Add a network switch to the wallet tester.
We have an MDP who would like to run through the wallet test using a devnet fireblocks workspace.  However, it seems that the way walletconnect or fireblocks works prevents even connecting in the wrong network (other wallets will let you connect and switch networks after connecting).
To unblock this user, I'm adding a network switch so they can switch to testnet before connecting their wallet.  I'm only adding it in the wallet tester although probably it makes sense to eventually replace the wallet connect modal from `@solana/wallet-adapter` with a custom one so we can offer this option anywhere that the wallet connection UI flow shows up instead.
> feat(staking): add devnet switch to wallet tester

- target_chains/ethereum/contracts/contracts/pulse/scheduler/Scheduler.sol
- target_chains/ethereum/contracts/contracts/pulse/scheduler/SchedulerErrors.sol
- target_chains/ethereum/contracts/contracts/pulse/scheduler/SchedulerState.sol
- target_chains/ethereum/contracts/contracts/pyth/Pyth.sol
- target_chains/ethereum/contracts/contracts/pyth/PythAccumulator.sol
- target_chains/ethereum/contracts/contracts/pyth/PythInternalStructs.sol
- target_chains/ethereum/contracts/forge-test/PulseScheduler.t.sol
- target_chains/ethereum/contracts/forge-test/Pyth.t.sol
- target_chains/ethereum/contracts/forge-test/utils/PulseTestUtils.t.sol
- target_chains/ethereum/contracts/forge-test/utils/PythTestUtils.t.sol
- target_chains/ethereum/sdk/solidity/AbstractPyth.sol
- target_chains/ethereum/sdk/solidity/IPyth.sol
- target_chains/ethereum/sdk/solidity/MockPyth.sol
- target_chains/ethereum/sdk/solidity/README.md
- target_chains/ethereum/sdk/solidity/abis/AbstractPyth.json
- target_chains/ethereum/sdk/solidity/abis/IPyth.json
- target_chains/ethereum/sdk/solidity/abis/MockPyth.json
- target_chains/ethereum/sdk/solidity/package.json
This PR fixes the "atomic" subscription update guarantee (ensuring all feeds in a subscription are updated together,) by using slots instead of timestamps for the validation.
The main motivation for this is that timestamps (`publishTime`) can be misleading for validating an "atomic" subscription update, as one or more assets might have closed markets, and will retain timestamps from their last trading period.
Thus, we use Pythnet slots for the atomicity validation, since they are consistent across all assets regardless of market status. 
- We still use timestamps to validate the heartbeat update condition. We now take the max of all passed in timestamps (rather than the first) to ensure that if any of the feeds need updating, we perform the update.
Pythnet slot number is available in the …
> fix(pulse-scheduler): validate atomic subscription updates using slots instead of timestamps

- target_chains/ethereum/contracts/contracts/pulse/scheduler/Scheduler.sol
- target_chains/ethereum/contracts/forge-test/PulseScheduler.t.sol
- target_chains/ethereum/contracts/forge-test/PulseSchedulerGasBenchmark.t.sol
- target_chains/ethereum/contracts/forge-test/utils/PulseSchedulerTestUtils.t.sol
- target_chains/ethereum/contracts/forge-test/utils/PulseTestUtils.t.sol
- Create a gas benchmark test for PulseScheduler. Covers the most common usage patterns:
- Updating a subscription's feeds, and then querying the prices. Will be done frequently by users and keepers.
- For 1, 2, 8, 10, 20 feeds.
- Querying current set of active subscriptions. Will be done frequently by keepers.
- For 10, 100, 1000 subscriptions, where half of them are active.
- Refactor common test helpers out into `PulseSchedulerTestUtils.t.sol`
Benchmarks should be run with -vv to see the gas usage of the operations under test, excluding the setup costs. 
See results here: https://app.warp.dev/block/Hs5rmQjIUKvq1X6Sdxl6nw
Need it to be able to profile the current and future gas usage of the contract.
> test(pulse-scheduler): add gas benchmark

- target_chains/ethereum/contracts/contracts/pulse/scheduler/Scheduler.sol
- target_chains/ethereum/contracts/contracts/pulse/scheduler/SchedulerErrors.sol
- target_chains/ethereum/contracts/contracts/pulse/scheduler/SchedulerState.sol
- target_chains/ethereum/contracts/forge-test/PulseScheduler.t.sol
1. Add the ability to mark subscriptions as permanent. Permanent subscriptions disallow destructive actions, such as removing price feeds or withdrawing funds.
2. Allow anyone to fund a subscription, not just the manager.
3. Refactor tests with helper methods since they were getting a bit unwieldy.
1. It's valuable for some consumers to lock down a subscription so that it can't be tampered by a manager. They may simply be using a vault manager hot wallet there, not a multisig. That wallet could potentially rug the subscription. But, other users may find it useful to be able to stop a subscription, e.g. someone subscribes to a memecoin that goes to 0 and they want to stop the sub. Thus, we add an optional `isPermanent` flag to the subscription, which will disallow destructive actions when …
> feat(pulse-scheduler): add permanent subscriptions, allow permissionless funding, clean up tests

- target_chains/ethereum/contracts/contracts/pulse/scheduler/Scheduler.sol
- target_chains/ethereum/contracts/contracts/pulse/scheduler/SchedulerErrors.sol
- target_chains/ethereum/contracts/contracts/pulse/scheduler/SchedulerState.sol
- target_chains/ethereum/contracts/forge-test/PulseScheduler.t.sol
- target_chains/ethereum/contracts/forge-test/PulseSchedulerGasBenchmark.t.sol
- target_chains/ethereum/contracts/forge-test/utils/PulseSchedulerTestUtils.t.sol
- target_chains/ethereum/contracts/forge-test/utils/PulseTestUtils.t.sol
- Extract duplicated SubscriptionParam validations into a `_validateAndPrepareSubscriptionParams` helper function.
- Improve validations to prevent undesirable state and behavior:
- Disallow subscriptions with zero feeds, since this will blow up later when indexing into empty arrays.
- Disallow duplicate price IDs in a subscription, since this will pollute the mappings and make removal logic ambiguous.
- Disallow duplicate whitelisted readers, enforce a maximum whitelist size to prevent maliciously large whitelists.
- Ensure that `heartbeatSeconds` and `deviationThresholdBps` are non-zero when those UpdateCriteria are enabled, since those would evaluate to always-true conditions.
- Ensure `minPublishTime` is clamped to zero to avoid integer underflow. This should be unlikely since …
> refactor(pulse-scheduler): improve SubscriptionParams validation

- apps/hermes/server/src/api/ws.rs
Add a new flag `ignore_invalid_price_ids` to WebSocket subscriptions that enables partial subscriptions when some price IDs are invalid. When enabled, Hermes will establish the WebSocket connection and stream updates only for the valid price IDs while silently ignoring any invalid ones. This enhancement aligns the WebSocket API behaviour with the existing REST API functionality introduced in #2091.
This change simplifies integration for clients who need to subscribe to multiple price feeds but don't require all of them to be valid. Current workarounds are suboptimal:
1. Sending individual subscription requests for each ID (increasing connection overhead)
2. Attempting a bulk subscription, parsing error messages to identify invalid IDs, then retrying with filtered IDs
The new flag provides …
> feat(hermes-server) Add `ignore_invalid_price_ids` flag to hermes ws endpoint

- lazer/Cargo.lock
- lazer/contracts/solana/programs/pyth-lazer-solana-contract/Cargo.toml
- lazer/sdk/rust/protocol/Cargo.toml
- lazer/sdk/rust/protocol/src/router.rs
Expose channel id constants publicly. It's useful when you want to hardcode it.
> Lazer protocol/expose channel ids

- target_chains/ethereum/contracts/contracts/pulse/scheduler/Scheduler.sol
- target_chains/ethereum/contracts/contracts/pulse/scheduler/SchedulerErrors.sol
- target_chains/ethereum/contracts/contracts/pulse/scheduler/SchedulerState.sol
- target_chains/ethereum/contracts/forge-test/PulseScheduler.t.sol
- target_chains/ethereum/contracts/forge-test/utils/PulseSchedulerTestUtils.t.sol
- Prevent all updates to permanent subs since any kind of update can be used to harm the availability of the feed
- Remove GasConfig. Gas limits will be set on the Keeper for simplicity and we will take the risk on spiking gas costs.
- Updated existing tests
> fix(pulse-scheduler): disallow all updates to permanent subs, remove GasConfig

- target_chains/ethereum/contracts/contracts/pulse/scheduler/IScheduler.sol
- target_chains/ethereum/contracts/contracts/pulse/scheduler/Scheduler.sol
- target_chains/ethereum/contracts/contracts/pulse/scheduler/SchedulerState.sol
- target_chains/ethereum/contracts/forge-test/PulseScheduler.t.sol
Optimize gas usage when querying for all active subscriptions.
This is one the most frequent access patterns in scheduler, since keepers need to poll the set of active subscriptions periodically to keep their state consistent. It's a view function so it will just be simulated, but since we could potentially store thousands of subscriptions, we still want to make it efficient.
This optimization sacrifices a bit of gas when activating/deactivating subscriptions (which should be relatively uncommon), for efficiency gains in the `getActiveSubscriptions` function. Previously we needed to iterate through all subscriptions to collect the active ones. This doesn't scale well as more subscriptions get deactivated. 
Now, we store the active subscriptions in an `activeSubscriptionIds` array for …
> feat(pulse-scheduler): optimize gas when querying active subscriptions

- target_chains/solana/Cargo.lock
- target_chains/solana/pyth_solana_receiver_sdk/Cargo.toml
- target_chains/solana/pyth_solana_receiver_sdk/src/price_update.rs
Anchor does not handle the FeedId type for the AnchorSerialize trait. 
This was already patched for pythnet_sdk in https://github.com/pyth-network/pyth-crosschain/blob/main/pythnet/pythnet_sdk/src/messages.rs#L94-L95
This patch reflects that same fix in the solana_receiver_sdk
> Fix missed FeedId anchor serialization patch

- target_chains/ethereum/contracts/contracts/pulse/IScheduler.sol
- target_chains/ethereum/contracts/contracts/pulse/README.md
- target_chains/ethereum/contracts/contracts/pulse/Scheduler.sol
- target_chains/ethereum/contracts/contracts/pulse/SchedulerGovernance.sol
- target_chains/ethereum/contracts/contracts/pulse/SchedulerState.sol
- target_chains/ethereum/contracts/contracts/pulse/SchedulerUpgradeable.sol
- target_chains/ethereum/contracts/forge-test/PulseScheduler.t.sol
- target_chains/ethereum/contracts/forge-test/PulseSchedulerGasBenchmark.t.sol
- target_chains/ethereum/contracts/forge-test/PulseSchedulerGovernance.t.sol
- Add governance instructions to Pulse
- Add ability to transfer admin capability to another address using a 2-step propose & accept flow
- Admin and Owner can execute governance instructions 
- Owner can upgrade the contract
- Enforce minimum balance when adding feeds to a subscription
- Minor misc updates to docs/formatting
- Added the following governance instructions:
- `upgradeContract`
- `setMinimumBalancePerFeed`
- Minimum balance per feed a subscription needs to maintain. Enforced when adding feeds or withdrawing funds.
- `setSingleUpdateKeeperFeeInWei`
- Fee per single feed update to pay the keeper. Unenforced right now, will implement in the next PR.
- These instructions haven't been added to other parts of the governance stack yet. We can likely do that when we want to actually …
> feat(pulse): add governance instructions, admin transfer capability

- target_chains/ethereum/contracts/contracts/pyth/PythGovernance.sol
- target_chains/ethereum/contracts/contracts/pyth/PythGovernanceInstructions.sol
- Added `SetFeeInToken` action (index 7) to `GovernanceAction` enum in `PythGovernanceInstructions.sol`
- Updated indices for `SetTransactionFee` (8) and `WithdrawFee` (9) to maintain alignment with TypeScript enum
- Added no-op handling for `SetFeeInToken` in `PythGovernance.sol`
- Updated function documentation comments to reflect new action indices
- The TypeScript `TargetAction` enum and Solidity `GovernanceAction` enum were out of sync
- `SetFeeInToken` existed in TypeScript but was missing in Solidity, causing index misalignment
- EVM chains don't need to implement `SetFeeInToken` functionality, but must recognize it as a valid action
- Maintaining consistent action indices across chains is critical for cross-chain governance
Testing verification:
1. Existing tests in …
> fix(pyth-governance): add no-op for SetFeeInToken action on EVM chains and update action indices

- apps/fortuna/src/command/get_request.rs
- apps/fortuna/src/command/inspect.rs
- apps/fortuna/src/command/setup_provider.rs
- target_chains/ethereum/contracts/contracts/entropy/Entropy.sol
- target_chains/ethereum/contracts/forge-test/Entropy.t.sol
- target_chains/ethereum/entropy_sdk/solidity/IEntropy.sol
- target_chains/ethereum/entropy_sdk/solidity/abis/IEntropy.json
As the description says -- it turns out that you can't decode the old struct data with the new struct format. This restores the old method signatures and adds new methods for retrieving the new versions of the structs.
I don't love that we have new methods here for retrieving requests / providers, but that's the only way I see to ensure that all users of the contract continue working.
I tested getting both a request and a provider from an old contract.
> fix(entropy): Restore old signatures for methods returning structs

- apps/entropy-debugger/src/lib/revelation.ts
- apps/fortuna/Cargo.lock
- apps/fortuna/Cargo.toml
- apps/fortuna/src/api.rs
- apps/fortuna/src/api/revelation.rs
- apps/fortuna/src/chain/ethereum.rs
- apps/fortuna/src/chain/reader.rs
- apps/fortuna/src/keeper/block.rs
Improve revelations api for arbitrum based chains
Current revelations api doesn't work well where `block.number` on-chain is different from what rpc returns. In arbitrum based chains, one points to the L1 block and the other to the L2 block.
> fix(entropy): Use the block number of event instead of request data for revelation api

- target_chains/ethereum/contracts/contracts/pulse/Scheduler.sol
- target_chains/ethereum/contracts/contracts/pulse/SchedulerErrors.sol
- target_chains/ethereum/contracts/contracts/pulse/SchedulerState.sol
- target_chains/ethereum/contracts/forge-test/PulseScheduler.t.sol
- target_chains/ethereum/contracts/forge-test/PulseSchedulerGasBenchmark.t.sol
Add keeper payment in `updatePriceFeeds`
Keepers are permissionless and we pay them in-band if they successfully call `updatePriceFeeds`. If the trigger condition isn't satisfied or the subscription doesn't have enough funds, they won't get paid.
This is a temporary payment model, the long term goal is to add a monthly subscription to make it easy for users to consume the service, rather than keeping their balance topped up. However, the basic mechanism of paying the keeper for successful updates will be the same, just the fee calculation will change.
> feat(pulse): keeper payment

- apps/staking/src/components/WalletTester/index.tsx
Instead, we will now use the default behavior from `@pythnetwork/solana-utils`, which aligns with what the staking sdk does and is to keep retrying until either the tx is successfully completed OR the user kills the app.
> fix(staking): remove max retries from wallet tester

- apps/hermes/server/Cargo.lock
- apps/hermes/server/Cargo.toml
- apps/hermes/server/src/api/rest/v2/sse.rs
- apps/hermes/server/src/api/ws.rs
- Added a 24-hour connection timeout for SSE endpoint
- Added a 24-hour connection timeout for WS endpoint
- Each client connection will automatically disconnect after 24 hours of continuous connection, with a proper error message sent before closing.
- Prevents resource leaks from indefinite connections
- Ensures proper cleanup of long-running connections
- Each client gets their own independent 24h window from their connection time
- Provides clear error messaging to clients about connection termination
Testing steps:
1. Verified that each new SSE/WS client connection gets its own independent 24h timeout
2. Confirmed that the timeout message is properly sent before connection close
3. Tested that the stream properly terminates after the timeout period
4. Verified that existing …
> feat(apps/hermes): add connection timeout for SSE & WebSocket connections

- apps/fortuna/src/chain/ethereum.rs
- target_chains/ethereum/contracts/contracts/entropy/Entropy.sol
- target_chains/ethereum/contracts/forge-test/Entropy.t.sol
- target_chains/ethereum/entropy_sdk/solidity/EntropyEventsV2.sol
- target_chains/ethereum/entropy_sdk/solidity/IEntropy.sol
- target_chains/ethereum/entropy_sdk/solidity/abis/IEntropy.json
- target_chains/ethereum/entropy_sdk/solidity/package.json
Add a new set of EntropyEvents to improve on the previous spec. Specifically, add indexing for the salient attributes, stop depending on struct definitions (which, if changed, break the event signature), and add dummy bytes for future extensibility.
In the process, I have omitted events for code paths that we are going to kill off (like the old pull flow).
> feat(entropy): Event V2 spec

- lazer/Cargo.lock
- lazer/contracts/solana/programs/pyth-lazer-solana-contract/Cargo.toml
- lazer/contracts/solana/programs/pyth-lazer-solana-contract/src/lib.rs
The lack of mut annotation is not causing any security risk (because if you pass it as readable it'll fail later when being used as writable). However, it breaks downstream users who rely on the published lib crate of the contract when making CPI to the contract.
> fix(lazer/solana): add mut annotation on treasury account

- target_chains/ethereum/contracts/forge-test/Entropy.t.sol
Update the expectEmit calls to test all topics and data. These were previously only testing the data field.
This is going to conflict with the other outstanding PR but I'll resolve that depending on which gets approved first.
> fix(entropy): Fix calls to expectEmit in tests

- apps/staking/package.json
- apps/staking/src/components/WalletTester/index.tsx
- apps/staking/src/hooks/use-api.tsx
- governance/pyth_staking_sdk/src/index.ts
- pnpm-lock.yaml
This PR updates the wallet tester to use the wallet's `sendTransaction` method, instead of using `sendTransaction` from `@pythnetwork/solana-utils`.  This should help account for slower wallets like Fireblocks.
We have a fireblocks user who is complaining about not being able to get the tester to work, and we believe the root cause is that tx is being delayed by the wallet -- which would make sense for Fireblocks' UX.
> fix(staking): use wallet's `sendTransaction` for wallet tester

- apps/fortuna/Cargo.lock
- apps/fortuna/Cargo.toml
- apps/fortuna/src/eth_utils/traced_client.rs
As the title suggests. 
erpc should handle long request issues with hedging and timeout configs but if the connection to erpc is dead for whatever reason, the keeper becomes stuck. This change will fix that, there is no need for a timeout config here as it should exist in erpc configs.
> feat(fortuna): Add timeout for rpc calls

- apps/price_pusher/package.json
- apps/price_pusher/src/controller.ts
- apps/price_pusher/src/metrics.ts
Added a new gauge metric `pyth_price_update_delay` to track the delay between source and target timestamps relative to each price feed's configured threshold. The metric is calculated as:
```
sourceLatestPricePublishTime - targetLatestPricePublishTime - priceConfigTimeDifference
```
- Each price feed has its own `timeDifference` configuration, making static thresholds suboptimal
- Enables dynamic alerting based on per-feed configuration rather than hardcoded values
- Handles market hours gracefully - during off-hours, `sourceLatestPrice` won't update, keeping the delay constant
- Allows setting unified alerts (e.g. `delay > 2min`) while respecting individual feed configurations
- Simplifies monitoring by normalizing delays against their expected thresholds
Steps to verify:
1. Deployed to …
> feat(metrics): add price update delay metric and update method

- target_chains/ethereum/contracts/contracts/pulse/IScheduler.sol
- target_chains/ethereum/contracts/contracts/pulse/Scheduler.sol
- target_chains/ethereum/contracts/forge-test/PulseScheduler.t.sol
- target_chains/ethereum/contracts/forge-test/PulseSchedulerGasBenchmark.t.sol
Remove unnecessary `priceIds` parameter from `updatePriceFeeds`
The `updatePriceFeeds` function takes updateData and priceIds from the Keeper, and verifies that the provided priceIds match the subscription’s priceIds. However, this isn't necessary as we can use the subscription param's priceIds list, and the  the `Pyth.parsePriceFeedUpdatesWithSlots` call validates that the updateData contains the desired priceIds.
If updateData contains any extra prices not matching the provided priceIds, they will be skipped and will not appear in the result, and if updateData doesn't contain enough prices for the subscription's feeds, it will revert with `PythErrors.PriceFeedNotFoundWithinRange()`
> fix(pulse): remove priceIds parameter from updatePriceFeeds

- target_chains/ethereum/contracts/contracts/entropy/Entropy.sol
- target_chains/ethereum/contracts/contracts/entropy/EntropyState.sol
- target_chains/ethereum/contracts/forge-test/Entropy.t.sol
- target_chains/ethereum/entropy_sdk/solidity/IEntropy.sol
- target_chains/ethereum/entropy_sdk/solidity/abis/IEntropy.json
Add a set of `requestV2` methods that give callers optionality on specifying providers etc. I think we get a set of questions like "what's a provider" or "what's userRandomNumber" which originate from the confusing function signatures in the user interface.
I'm not sure why we didn't do this in the first place -- i think for some reason we thought we couldn't override method names. It works though so I think we go for it.
I think we may want to pull out some of these methods into a separate solidity interface to make it easier for users of entropy to see the methods they want to call as well. If you're onboard with the interface changes, then I can do that next.
This should make it easier for developers to use entropy -- just call `requestV2()` and get a callback.
> feat(entropy): More ergonomic v2 interface

- target_chains/ethereum/entropy_sdk/solidity/IEntropy.sol
- target_chains/ethereum/entropy_sdk/solidity/IEntropyV2.sol
- target_chains/ethereum/entropy_sdk/solidity/abis/EntropyEventsV2.json
- target_chains/ethereum/entropy_sdk/solidity/abis/IEntropyV2.json
- target_chains/ethereum/entropy_sdk/solidity/package.json
Split out the V2 functionality into a separate file. The intention is that developers can interact exclusively with the IEntropyV2 interface. This interface hides internal methods for providers etc that users don't need to know about. Meanwhile, we retain the IEntropy interface (which has the old functions + provider functions + inherits the V2 functions) as the full interface the contract implements.
These changes should make it easier for users to identify the functionality they need
> feat(entropy): Split out V2 interface into separate file.

- apps/fortuna/src/config.rs
- apps/fortuna/src/keeper.rs
- apps/fortuna/src/keeper/block.rs
As the title
I'm trying to refactor the codebase and make the keeper functions more manageable. This was a low-hanging fruit.
We are not using websockets in any of the chains and I'm not sure if we can do it through erpc.
> fix(fortuna): remove wss related code

- apps/price_pusher/package.json
- apps/price_pusher/src/aptos/balance-tracker.ts
- pnpm-lock.yaml
Updated the Aptos client implementation to use the new `@aptos-labs/ts-sdk` instead of the deprecated `aptos` package, and simplified balance tracking by using the dedicated `getAccountAPTAmount` method.
These changes are necessary to:
1. Use the latest Aptos TypeScript SDK which offers improved functionality and better support
2. Replace the complex manual balance tracking with the SDK's built-in method that automatically handles both Fungible Asset and Coin formats
3. Ensure compatibility with upcoming Movement chain updates that follow Aptos SDK standards
The changes have been manually tested against both Movement and Aptos chains to ensure the balance tracker correctly fetches and displays token balances. Tests verified that the `getAccountAPTAmount` method correctly tracks balances …
> feat(apps/price_pusher): update Aptos balance tracker to use new SDK and improve balance retrieval

- target_chains/ethereum/contracts/contracts/pulse/Scheduler.sol
Use `priceUpdates` from `memory` instead of `storage` in `_getPricesInternal`
Cheaper to iterate through memory, although this doesn't apply for large structs, as the initial copy from storage into memory is expensive.
Optimization saves 16k gas querying for a sub with 20 feeds: https://app.warp.dev/block/YEc8EQ1MBKjhbm38Ft5TLj
> fix(pulse): use memory instead of storage for priceUpdates struct

- target_chains/ethereum/contracts/contracts/pulse/Scheduler.sol
Remove mention of gasConfig in the sub param validation function.
Gas config is no longer part of a subscription's on-chain metadata, these docs are obsolete.
> refactor(pulse): remove mention of gas config in sub param validation

- apps/price_pusher/package.json
- apps/price_pusher/src/sui/balance-tracker.ts
Fixed Sui balance tracker retrieval logic
Previous approach was returning the wrong value.
> fix: balance retrieval in SuiBalanceTracker

- target_chains/ethereum/contracts/contracts/pulse/Scheduler.sol
- target_chains/ethereum/contracts/forge-test/PulseScheduler.t.sol
Enforce minimum balance in updateSubscription even when reducing or keeping the number of feeds the same.
Initially we didn't enforce the check if the user is decreasing their feed count or keeping it the same. The thought was to be friendly to the user in case they are trying to reduce their funds burn rate. However, this is inconsistent behavior and might actually confuse the user, and it's safer to always check. Now, in all cases where the sub is getting updated and remaining active, the check is enforced.
> fix(pulse): enforce min bal for all active updated subs

- target_chains/ethereum/contracts/contracts/entropy/Entropy.sol
- target_chains/ethereum/contracts/forge-test/Entropy.t.sol
As the title says. Track gas usage and emit it in the event.
I previously omitted gas tracking in this recovery flow (which is identical to the old callback flow). However, I realized tracking gas will be useful here -- if a user's callback fails and they recover it, they probably want to know how much gas it used so they can set the gas limit better next time.
> feat(entropy): Add gas tracking for the callback recovery flow

- .github/workflows/ci-message-buffer.yml
- .github/workflows/ci-remote-executor.yml
- .github/workflows/ci-solana-contract.yml
Switch from solana to agave releases when install solana. Solana releases URL seems down.
CI is crashing without these changes.
> fix: use agave releases instead of solana labs

- target_chains/ethereum/contracts/contracts/entropy/Entropy.sol
- target_chains/ethereum/contracts/forge-test/Entropy.t.sol
- target_chains/ethereum/entropy_sdk/solidity/EntropyEventsV2.sol
- target_chains/ethereum/entropy_sdk/solidity/IEntropyV2.sol
- target_chains/ethereum/entropy_sdk/solidity/abis/EntropyEventsV2.json
- target_chains/ethereum/entropy_sdk/solidity/abis/IEntropy.json
- target_chains/ethereum/entropy_sdk/solidity/abis/IEntropyV2.json
Three minor changes:
1. rename "providerRandomNumber" and "userRandomNumber" to xContribution for clarity.
2. emit these contributions in the new EventsV2 revealed event (so users can generate a retry call in forge from the event, without hitting the fortuna API)
3. update docs around how the protocol works and security assumptions (this was a comment from AR)
> feat(entropy): Minor items to prep for testnet deployments

- governance/xc_admin/packages/xc_admin_cli/src/index.ts
Now the amount to stake is customizable (defaults to the traditional value of 100,000 PGAS)
We need to stake some validators with a lower amount.
> feat: add amount to stake in the flow to stake new validators via governance

- apps/hermes/server/Cargo.lock
- apps/hermes/server/Cargo.toml
- apps/hermes/server/src/config/pythnet.rs
- apps/hermes/server/src/network/pythnet.rs
We used mapping account to get the product metadata but it involves many calls and many node providers have been facing issues with it. This change removes mapping account and uses `getProgramAccounts` to fetch all accounts in one go.
> refactor(hermes/server): use program accounts instead of mapping acct

- target_chains/ethereum/contracts/contracts/entropy/Entropy.sol
- target_chains/ethereum/contracts/contracts/pyth/Pyth.sol
- target_chains/ethereum/contracts/forge-test/Echo.t.sol
- target_chains/ethereum/contracts/foundry.toml
- target_chains/ethereum/contracts/hardhat.config.ts
- target_chains/ethereum/contracts/truffle-config.js
Updates the solc compiler to 0.8.29 (the version before latest version) so the contracts fit the contract size limit. I checked a few explorers to make sure they support this solc version. See the comments on some adjustments.
> chore(target_chains/ethereum): cut a release for price feeds contracts

- .github/workflows/publish-rust-lazer-publisher-sdk.yml
- lazer/Cargo.lock
- lazer/publisher_sdk/proto/publisher_update.proto
- lazer/publisher_sdk/proto/pyth_lazer_transaction.proto
- lazer/publisher_sdk/proto/transaction_envelope.proto
- lazer/publisher_sdk/rust/Cargo.toml
- lazer/publisher_sdk/rust/build.rs
- lazer/publisher_sdk/rust/src/lib.rs
- lazer/sdk/rust/protocol/Cargo.toml
- Removes the publisher ID field from the publisher update sent by publishers. Publishers don't need know what their ID is, and its better to not ask them to self report it. 
- Removes update index from feed update context. It's unnecessary, and I will make assertions to make sure the ordering and length of the array match the publisher updates vec exactly. 
- Moved transaction envelope definition to publisher SDK to skip one decode step. Also added comments, adopting Pavel's comment styling in the Pyth Lazer repo.
- Switched the parser to use protoc and then added the argument to generate rust docs for the generated types, as per Pavel's [PR](https://github.com/pyth-network/pyth-lazer/pull/346). 
Reduces some burden on publishers by not requiring them to know their own IDs. The update …
> feat(pyth-lazer/publisher-sdk): Move Transaction Envelope Definitions to SDK

- .github/workflows/ci-lazer-rust.yml
- lazer/Cargo.lock
- lazer/publisher_sdk/proto/dynamic_value.proto
- lazer/publisher_sdk/proto/governance_instruction.proto
- lazer/publisher_sdk/proto/pyth_lazer_transaction.proto
- lazer/publisher_sdk/rust/Cargo.toml
- lazer/publisher_sdk/rust/build.rs
- lazer/publisher_sdk/rust/src/lib.rs
Add proto declarations describing payload of a governance transaction.
We want to manage Lazer through Pyth governance.
> feat(lazer): add governance instructions protocol

- contract_manager/src/chains.ts
- contract_manager/store/chains/EvmChains.yaml
- contract_manager/store/contracts/EvmEntropyContracts.yaml
- contract_manager/store/contracts/EvmPriceFeedContracts.yaml
- contract_manager/store/contracts/EvmWormholeContracts.yaml
Remove chains that are no longer live & their corresponding entropy deployments
> chore(contract manager): Remove old chains and contracts

- contract_manager/scripts/execute_vaas.ts
- contract_manager/scripts/list_entropy_contracts.ts
as the title says
this lets you execute a single specific VAA, which is great to test a single contract upgrade within a batch, or retry a specific failure.
> feat(contract manager): Add sequence number support to execute_vaas and print Entropy owner

- apps/hermes/server/Cargo.lock
- apps/hermes/server/Cargo.toml
- apps/hermes/server/src/api/ws.rs
The previous change in #2599 has added a side effect that doesn't allow empty subscriptions anymore and that has broken some of downstream users. This change removes the new behaviour. If we need we can only have this behaviour when the flag of ignore invalid ids is set.
> fix(apps/hermes/server): allow subscriptions with empty price feed ids

- target_chains/ethereum/contracts/deploy/zkSyncDeployNewEntropyImpl.ts
as it says
we need this to upgrade entropy contracts
> chore(entropy): deployment script for entropy upgrades

- target_chains/ethereum/contracts/contracts/pulse/Scheduler.sol
Apply the checks-effects-interactions pattern -- update the balance before the Pyth parse call, even though there is a low chance of a reentrancy attack since we control the Pyth contract.
> fix(pulse): update balance before parse call

- governance/xc_admin/packages/xc_admin_common/src/programs/core/core_functions.ts
- governance/xc_admin/packages/xc_admin_frontend/hooks/usePyth.ts
filter out products without price accounts from mapping accounts and fix logging logic in usePyth
> refactor: fix product filtering and improve account processing logging in usePyth

- contract_manager/store/chains/EvmChains.yaml
- contract_manager/store/contracts/EvmPriceFeedContracts.yaml
- contract_manager/store/contracts/EvmWormholeContracts.yaml
- governance/xc_admin/packages/xc_admin_common/src/chains.ts
- target_chains/ethereum/contracts/foundry.toml
- target_chains/ethereum/contracts/hardhat.config.ts
- target_chains/ethereum/contracts/truffle-config.js
Add evm new networks and update the compiler to use `paris` evm version (= the evm instructions at the merge) as some newer instructions in newer versions are not supported in all chains.
> chore(target_chains/ethereum): add new networks

- apps/fortuna/Cargo.lock
- apps/fortuna/Cargo.toml
- apps/fortuna/config.sample.yaml
- apps/fortuna/src/command/run.rs
- apps/fortuna/src/command/setup_provider.rs
- apps/fortuna/src/config.rs
- apps/fortuna/src/eth_utils/utils.rs
- apps/fortuna/src/keeper/commitment.rs
- Add a new config that disables fee syncs if the chain is already registered.
- Improve logging:
- Change retry log levels from ERROR to WARN
- Add more info on some other logs
Whenever we deploy a new version or change some configuration, the setup script is executed and fees are synced to the default value. This is unnecessary and can cause problems for some of the requests made within the duration that the fee is reset (if the users are paying for the fee and the value sent to our contract is the tx value signed by user).
> feat(fortuna): better logging + avoid unnecessary fee syncs

- contract_manager/store/contracts/EvmPriceFeedContracts.yaml
- target_chains/ethereum/contracts/deploy.sh
This change modifies the deploy script to download the artifacts from GH releases to make deployments easier and more deterministic. The release also contains artifacts needed for contract verification.
> chore(target_chains/ethereum): use versioned artifacts for deployment

- apps/hermes/server/Cargo.lock
- apps/hermes/server/Cargo.toml
- apps/hermes/server/src/api/ws.rs
> fix(hermes): increase the ws size limit

- packages/component-library/src/NoResults/index.tsx
Mark NoResults as a client component
Because we run react compiler in the component library now, all components must be marked as client components.  I forgot to add the marker to this file.
In general we don't need to worry about automating / tooling this as components will be obviously broken if this marker isn't added, but in this case I didn't catch it because I just turned on react compiler.
> fix(component-library): mark no results page as a client component

- lazer/contracts/evm/README.md
Add all the steps required for a Lazer deployment.
> refactor(lazer/contracts/evm): update README with more deployment details

- .github/CODEOWNERS
Add CODEOWNERS for the lazer components.
Improving team operations by ensuring the correct owners get notified of code changes.
> feat(lazer) Add CODEOWNERS for the lazer components

- lazer/sdk/js/examples/index.ts
- lazer/sdk/js/package.json
- lazer/sdk/js/src/client.ts
- lazer/sdk/js/src/socket/resilient-websocket.ts
- lazer/sdk/js/src/socket/websocket-pool.ts
This PR refactors the PythLazerClient and the underlying components, WebSocketPool and ResilientWebSocket.
* When connecting initially it avoids crashing and retries until it can connect to at east one url
* When a connection drops, it avoids crashing and keep retrying the connection
* The config has been improved to get the parameters with hard-coded defaults. (compared hard coded configs)
* Unnecessary async functions have been changed to sync
* Logging has been improved to show important events and avoid spamming
* Increases the default number of connections to 4 to balance the number of connections per url
The current client is broken, it crashed at the beginning if it can't connect to all the urls and if one of the connections drops it also crashes.
This caused some of our used to …
> feat(pyth-lazer-stk): correctly handle connection drops + other improvements

- apps/insights/src/components/PriceComponentDrawer/index.tsx
Fix IH loading feed component from url
This was not working correctly previously
> fix(insights): properly restore feed component url

- contract_manager/store/tokens/Tokens.json
Remove `CANTO` from `Tokens.json`
This feed has been disabled
> chore(contract_manager): remove CANTO from tokens.json

- lazer/publisher_sdk/proto/state.proto
- lazer/publisher_sdk/rust/src/lib.rs
Move the `state.proto` file from the private internal protocol to public sdk.
This will be needed by `xc-admin`
> feat(lazer) Add the lazer state definitions to `state.proto`

- apps/price_pusher/package.json
- apps/price_pusher/src/aptos/aptos.ts
- apps/price_pusher/src/fuel/fuel.ts
- apps/price_pusher/src/injective/injective.ts
- apps/price_pusher/src/near/near.ts
- apps/price_pusher/src/price-config.ts
- apps/price_pusher/src/pyth-price-listener.ts
- apps/price_pusher/src/solana/solana.ts
- apps/price_pusher/src/sui/sui.ts
- apps/price_pusher/src/ton/ton.ts
The price pusher in many networks would throw an error if a feed doesn't exist and the behaviour was there to prevent config errors but it falls short when we remove a feed. This change adds a warning for non existent feeds but lets the pusher keep functioning (for the remaining feeds).
p.s: evm pusher already had the flag to ignore invalid feeds.
> fix(apps/price_pusher) handle price feed removal more gracefully

- apps/insights/src/components/LivePrices/index.tsx
- apps/insights/src/components/PriceFeed/chart.tsx
- apps/insights/src/hooks/use-price-formatter.ts
Ensure very small numbers display properly instead of rounding to zero.
For some symbols, the price or confidence are very small, and the previous formatting code would round very small numbers to zero.
> fix(insights): don't show very small numbers as zero

- contract_manager/scripts/entropy_debug_reveal.ts
Make the manual reveal script to accept a range.
Helpful for incident recovery
> feat(contract_manager): improve manual reveal script

- apps/hermes/server/Cargo.lock
- apps/hermes/server/Cargo.toml
- apps/hermes/server/src/network/pythnet.rs
Since we are programmatically banning panics in our code, this PR removes an unwrap() by replacing the product account header string with its bytes representation.
- Verified we can fetch the product account
> fix(hermes): remove unwrap for product account header

- .github/workflows/docker-entropy-tester.yml
> feat(entropy-tester): add docker image workflow

- apps/entropy-tester/.gitignore
- apps/entropy-tester/cli/run.js
- apps/entropy-tester/package.json
- apps/entropy-tester/src/index.ts
- apps/entropy-tester/tsconfig.build.json
- apps/entropy-tester/tsconfig.json
tsconfig was not working as I hoped for.
> fix(entropy-tester): adjust cli execution and tsconfigs

- apps/hermes/server/Dockerfile
Update the Hermes Docker base image from rust:1.82.0 to debian:bookworm-slim.
The current base image rust:1.82.0 has known vulnerabilities, as listed on Docker Hub:
https://hub.docker.com/layers/library/rust/1.82.0/images/sha256-fc4cf6c302df3a3cb211027605fd61447cac29d873692041bd21d22c55b5b459
To improve security and reduce image size, we're switching to bookworm-slim as the base image and installing only the necessary Rust toolchain manually.
- Built the image locally
- Ran the Hermes service inside the container to ensure correct behavior
- Verified that the Rust toolchain installs and builds correctly on bookworm-slim
> Update hermes docker base runner

- pyth-lazer-agent/src/lazer_publisher.rs
- pyth-lazer-agent/src/main.rs
- pyth-lazer-agent/src/relayer_session.rs
- backoff reset after several minutes (a pattern we use elsewhere)
- use broadcast::channel instead of mpsc::channel to fan out to relayers at Ali's suggestion
- default config file fix
- drain pending updates vector
> pyth-lazer-agent fixes

- README.md
- apps/hermes/server/Cargo.toml
- apps/hermes/server/build.rs
- apps/hermes/server/src/api.rs
- apps/hermes/server/src/api/rest.rs
- apps/hermes/server/src/api/rest/get_vaa_ccip.rs
- apps/hermes/server/src/api/types.rs
- apps/hermes/server/src/config.rs
- apps/hermes/server/src/config/cache.rs
- apps/hermes/server/src/main.rs
- apps/hermes/server/src/network/wormhole.rs
- apps/hermes/server/src/serde.rs
- apps/hermes/server/src/state.rs
- apps/hermes/server/src/state/aggregate.rs
- apps/hermes/server/src/state/aggregate/metrics.rs
- apps/hermes/server/src/state/aggregate/wormhole_merkle.rs
- apps/hermes/server/src/state/benchmarks.rs
- apps/hermes/server/src/state/cache.rs
- apps/hermes/server/src/state/metrics.rs
- apps/hermes/server/src/state/wormhole.rs
- doc/code-guidelines.md
- doc/rust-code-guidelines.md
We want to add better linting throughout our codebase. I also put together [this guide](https://www.notion.so/pyth-network/Rust-code-guidelines-20a2eecaaac98060b6b2d9a52c9f9141) to help deal with these new lints.
To improve code quality: avoid panics, overflows and other suspicious code patterns.
> doc, refactor(apps/hermes/server): add code guidelines, enable extra clippy lints

- README.md
Add note to README to clean up auto-generated GitHub release notes
> doc: add release changelog note to readme

- apps/quorum/Cargo.lock
- apps/quorum/Cargo.toml
- apps/quorum/src/api.rs
- apps/quorum/src/server.rs
This PR aims to add tests for Pyth quorum
> Add tests for quorum

- apps/entropy-tester/package.json
It is preventing the js publish workflow to work fine.
> fix(js-release): mark entropy-tester as private

- apps/fortuna/Cargo.lock
- apps/fortuna/Cargo.toml
- apps/fortuna/src/main.rs
Uses another log format when not running in shell
Some alerts are not working properly because the error log is multiline and we can't capture the chain_id of the error log
This is exactly how hermes sets up the logging.
> feat(fortuna): json format on prod

- apps/pyth-lazer-agent/Cargo.lock
- apps/pyth-lazer-agent/Cargo.toml
- apps/pyth-lazer-agent/src/config.rs
- apps/pyth-lazer-agent/src/lazer_publisher.rs
> fix(pyth-lazer-agent): add back optional authorization_key

- apps/entropy-tester/config.sample.json
- apps/entropy-tester/package.json
- apps/entropy-tester/src/index.ts
- contract_manager/src/core/chains.ts
Use a custom endpoint for making requests
I was hoping that the load is small enough such that public rpcs would be sustainable. But that was not the case.
> feat(entropy-tester): accept custom endpoint

- apps/entropy-tester/package.json
- packages/component-library/package.json
- pnpm-lock.yaml
Explicitly defining node types across packages
I was personally running into issues with my system not referring back to the monorepo-defined node types version, so we thought it was a good idea to explicitly define versioning.
> fix(ci): Node types catalog

- apps/quorum/Cargo.lock
- apps/quorum/Cargo.toml
- apps/quorum/src/api.rs
This PR aims to add a root url to quorum service to make the current quorum version visible
> Add version url to quorum api

- apps/hermes/server/Cargo.lock
- apps/hermes/server/Cargo.toml
- apps/hermes/server/src/api/rest.rs
- apps/hermes/server/src/network/pythnet.rs
- apps/hermes/server/src/network/wormhole.rs
- apps/hermes/server/src/state/aggregate.rs
- apps/hermes/server/src/state/wormhole.rs
This PR aims to add error logs if the VAA received by PythNet quorum service was invalid.
> Hermes: Add error log when receiving invalid quorum VAA

- target_chains/stylus/contracts/pyth-receiver/src/error.rs
- target_chains/stylus/contracts/pyth-receiver/src/lib.rs
Implemented the get prices functions of the pyth stylus contract.
Important for getting most recent prices, and has an important function definition for making sure that an update is no older than a certain specified age (is_no_older_than). 
Get prices can only be evaluated when other parts of the contract are completed (i.e. initialization). Until then, cargo build is the main system by which I'm verifying things work.
> feat(stylus) - get prices pyth contract functions

- .pre-commit-config.yaml
Update rust related command in pre-commit-config. Remove hardcoded Rust versions so that pre-commit uses versions from rust-toolchain files.
> chore: fix pre-commit-config

- apps/argus/src/config.rs
Remove the fields argus config that no longer exist in  EscalationPolicy
The fields were removed in #2691 causing compilation errors in argus:
```
error[E0560]: struct `EscalationPolicy` has no field named `gas_limit_tolerance_pct`
--> apps/argus/src/config.rs:162:13
|
162 |             gas_limit_tolerance_pct: self.gas_limit_tolerance_pct,
|             ^^^^^^^^^^^^^^^^^^^^^^^ `EscalationPolicy` does not have this field
|
= note: all struct fields are already assigned
error[E0560]: struct `EscalationPolicy` has no field named `initial_gas_multiplier_pct`
--> apps/argus/src/config.rs:163:13
|
163 |             initial_gas_multiplier_pct: self.initial_gas_multiplier_pct,
|             ^^^^^^^^^^^^^^^^^^^^^^^^^^ `EscalationPolicy` does not have this field
|
= note: all struct fields are …
```
> fix(argus) Fix compilation issues related to EscalationPolicy

- target_chains/stylus/Cargo.lock
- target_chains/stylus/Cargo.toml
- target_chains/stylus/contracts/pyth-types/Cargo.toml
- target_chains/stylus/contracts/pyth-types/src/lib.rs
Added a new crate that defines types for structs shared between Wormhole and Pyth stylus contracts
Allows for more flexible refactoring of structs in the future.
The crate currently builds. I will test it further when integrating it into their respective libraries.
> feat(stylus): added crate for types shared across Wormhole and Pyth

- Cargo.lock
- apps/fortuna/Cargo.toml
- apps/fortuna/src/history.rs
- apps/fortuna/src/keeper/fee.rs
Tune the logs on Fortuna:
- Add more logs for fee withdrawals to make tracing easier
- Downgrade pkey unique violation logs since this is expected behavior, we are using the unique constraint to prevent one instance from overwriting a request row that another created.
> chore(fortuna): improve fee withdrawal logs, dont error log on pkey unique constraint violation

- target_chains/ethereum/contracts/hardhat.config.ts
Add configuration for abstract to hardhat and lower solidity version to something supported by Hardhat. Hardhat doesn't build the contracts with 0.8.29 and i backed up until I found one that works.
> chore(entropy): Add hardhat config for abstract and adjust hardhat Solidity version

- apps/fortuna/src/eth_utils/utils.rs
Fix a bug preventing contract reverts during simulation from being captured correctly.
`client.fill_transaction` does a couple things including estimating gas usage and fetching the current gas price. If the contract reverts during the estimating gas phase via simulation, the code expects the error to be propagated as a `GasUsageEstimateError(ContractError::Revert(bytes)).` However, the error handler for the `client.fill_transaction` call wraps the error in a `GasPriceEstimateError`, which prevents the calling code from handling the contract revert properly. We can see this happening in the logs, example:
```
Failed to process event: Gas price estimate error: (code: 3, message: execution reverted, data: Some(String(\"0xc4237352\")))
```
This causes the wrong `reason` to get stored in the …
> fix(fortuna): correctly propagate contract reverts in simulation

- apps/entropy-tester/package.json
- apps/entropy-tester/src/index.ts
Add retries to the entropy-tester script
We use entropy-tester as a synthetic test for Entropy. If the script fails, it's a good signal that something is wrong. However, this can be a bit noisy, as currently a single failed callback raises an alarm, even though it is likely due to a transient chain issue we can't do anything about.
Adding retries to the tester allows us to reduce this noise by only alerting if we fail to receive multiple callbacks in a row. After this change, a critical alert will be fired if 3 callbacks fail back to back, giving us better confidence that something is actually wrong.
- Tested locally with prod config
> feat(entropy-tester): add retries

- target_chains/ethereum/sdk/solidity/IPyth.sol
Corrected natspec on the solidity contract to reflect new changes where updates passed through the "parsePriceFeedUpdates" method are not stored on-chain.
> fix: Fixed parsePriceFeedUpdates natspec

- contract_manager/scripts/transfer_balance_entropy_chains.ts
Sometimes when using `--ratio`, the amount to transfer can be a number with many decimals. `web3.utils.toWei` errors on these numbers with `'[ethjs-unit] while converting number 0.0016499420763857226 to wei, too many decimal places' `
> fix(transfer-balance-entropy-chains): round transfer amount to avoid conv errors

- apps/pyth-lazer-agent/config/config.toml
The prod relayers need `wss://`
> chore(pyth-lazer-agent) Fix mistake in sample config

- Cargo.lock
- apps/pyth-lazer-agent/Cargo.toml
- apps/pyth-lazer-agent/src/relayer_session.rs
Allow the full URL (including path) to be specified for the relayers. Also bump to 0.1.5 for release
The path structure differs and prod and staging so we can't simply hardcode it as `/v1/transactions`
> fix(pyth-lazer-agent) Allow the relayer endpoint path in config

- apps/pyth-lazer-agent/src/main.rs
Add an option to switch between different logging formats (json,compact,pretty).
Customer request
> @bplatak feat(pyth-lazer-agent) Make the logging format configurable

- .github/workflows/publish-rust-lazer-agent.yml
- apps/pyth-lazer-agent/Cargo.toml
Add a gh workflow to publish the `pyth-lazer-agent` to crates.io and update Cargo.toml
Simplifies the deployment of the agent
> feat(pyth-lazer-agent) Publish the agent to crates.io

- target_chains/stylus/contracts/pyth-receiver/src/governance.rs
- target_chains/stylus/contracts/pyth-receiver/src/lib.rs
dividing governance instructions out of lib.rs
> refactor(stylus): dividing governance instructions out of lib.rs

- Cargo.lock
- lazer/sdk/rust/client/Cargo.toml
- lazer/sdk/rust/client/src/backoff.rs
- lazer/sdk/rust/client/src/client.rs
feat: add backoff wrapper + ai generated docs
missing improvements from previous PR
Ran the example
> feat: add backoff wrapper + ai generated docs

- Cargo.lock
- apps/fortuna/Cargo.toml
- apps/fortuna/src/chain/ethereum.rs
I introduced a bug in this method in the PR when I upgraded fortuna to handle the v2 contract. This bug is breaking the stats on callback errors.
> fix(fortuna): Fix bug in get_request_v2

- Cargo.lock
- apps/fortuna/Cargo.toml
- apps/fortuna/src/api.rs
- apps/fortuna/src/api/config.rs
> chore(fortuna)-add-network-id-api

- Cargo.lock
- lazer/publisher_sdk/proto/governance_instruction.proto
- lazer/publisher_sdk/proto/state.proto
- lazer/publisher_sdk/rust/Cargo.toml
- Clarify naming
- Simplify permissions
- Separate "update" and "delete" actions
- Make timestamps required for disable/enable_in_shard
Done as part of implementation of governance.
> feat(lazer): update and improve governance proto

- lazer/sdk/js-solana/package.json
- lazer/sdk/js-solana/tsconfig.build.json
- Run tsc to generate .d.ts files
- Update package.json to point at the location of .d.ts files
The package was missing .d.ts files, so it wasn't possible to use it.
> fix(lazer): include .d.ts files in solana sdk js package

- Cargo.lock
- lazer/sdk/rust/protocol/Cargo.toml
- lazer/sdk/rust/protocol/src/payload.rs
- lazer/sdk/rust/protocol/src/router.rs
Add `PriceFeedProperty::FundingRateInterval` for the new funding rate interval field 
Needed for PF-278
> feat(pyth-lazer) Add funding_rate_interval to feed properties

- Cargo.lock
- lazer/publisher_sdk/proto/transaction_envelope.proto
- lazer/publisher_sdk/rust/Cargo.toml
- lazer/sdk/rust/client/Cargo.toml
Adds reject reasons for if the market is closed for the feed, and if the publisher is not permissioned for that feed. 
We still want to process and store these, but not produce aggregates on them.
> chore(lazer/publisher-sdk): Add Rejections for Market Closed and Unauthorized

- apps/fortuna/Cargo.toml
- apps/fortuna/src/api.rs
- apps/fortuna/src/history.rs
Adds support for filtering logs based on callback failed / callback succeeded state to Fortuna.
Entropy explorer
> feat(fortuna): allow filtering callback failing logs

- .github/workflows/ci-hermes-client-rust.yml
- .github/workflows/publish-rust-hermes-client.yml
- Cargo.lock
- apps/hermes/client/rust/Cargo.toml
- apps/hermes/client/rust/examples/subscribe_price_feeds.rs
> fix: rename hermes rust client to

- target_chains/stylus/contracts/pyth-receiver/src/integration_tests.rs
- target_chains/stylus/contracts/pyth-receiver/src/lib.rs
UpdatePriceFeeds now collects fees from the user before actually going through the update script.
Need to make sure that we validate fee before doing the work so that people can't use the service without paying tax.
> fix(stylus) - fixed order of fee calculation

- Cargo.lock
- lazer/publisher_sdk/rust/Cargo.toml
- lazer/sdk/rust/client/Cargo.toml
- target_chains/ethereum/entropy_sdk/solidity/IEntropy.sol
> Fix version issue in lazer publisher and rust sdks

- apps/insights/src/components/PriceFeedIcon/index.tsx
Currently, we display the Generic icon from the cryptocurrency icons set when we have an asset class which no associated icon.  However, that icon really doesn't make sense for asset classes that aren't cryptos, so instead this PR just blanks out the icon for such cases.
> feat(insights): omit icon when an asset class has no icon

- apps/api-reference/src/apis/evm/update-price-feeds-if-necessary.tsx
There's a typo in https://api-reference.pyth.network/price-feeds/evm/updatePriceFeedsIfNecessary under `Error Response`
> chore(bug): updatePriceFeedsIfNecessary typo fix

- apps/insights/src/cache.ts
- apps/insights/src/services/pyth/get-metadata.ts
> fix: cache hotfix

- lazer/contracts/sui/sources/channel.move
- lazer/contracts/sui/sources/feed.move
- lazer/contracts/sui/sources/pyth_lazer.move
- lazer/contracts/sui/sources/update.move
- lazer/contracts/sui/tests/pyth_lazer_tests.move
- Better parsing and error handling.
- Split up the monolithic parsing code. Now each layer of the payload (e.g. `update`, `feed`, `channel`) is responsible for its own deserialization logic.
- This lets us return granular error messages and gracefully handle bad payloads.
- Existing parse test didn't regress
- Added negative tests to check that granular error handling works
> feat(lazer/sui): better parsing and error handling

- contract_manager/scripts/batchDeployReceivers.ts
Moved [batchDeployReceivers.ts](https://github.com/pyth-network/pyth-crosschain/blob/main/target_chains/ethereum/contracts/scripts/batchDeployReceivers.ts) to contract-manager
> chore: moved batch deploy receiver to contract_manager

- contract_manager/store/tokens/Tokens.json
Running `pnpm exec ts-node scripts/fetch_fees.ts` from contract-manager returns 404 error abruptly.
Removed the MTR token pyth ID that was causing the issue, making the script run.
> chore(bug): remove MTR token pyth ID 

- apps/api-reference/next-env.d.ts
- apps/api-reference/src/apis/evm/parse-price-feed-updates-unique.tsx
- apps/api-reference/src/apis/evm/parse-price-feed-updates.tsx
- apps/api-reference/src/apis/evm/update-price-feeds-if-necessary.tsx
- apps/api-reference/src/apis/evm/update-price-feeds.tsx
- apps/api-reference/src/components/EvmApi/parameter-input.tsx
- apps/api-reference/src/components/EvmApi/parameter.ts
> chore(api-reference) Fix Input fieulds

- apps/developer-hub/content/docs/express-relay/index.mdx
- apps/developer-hub/src/components/IntegrationCard/index.tsx
- apps/developer-hub/src/mdx-components.tsx
Adding introduction page for express relay, migrated from the documentation
> feat(express-relay): adding introduction page for express relay

- apps/entropy-explorer/next-env.d.ts
- apps/entropy-explorer/package.json
- apps/entropy-explorer/src/components/Home/search-controls.tsx
- flake.nix
The `Paginator` suspense boundary was incorrectly referring to the `<Paginator>` component in the fallback case, which was a circular reference and caused the stack to blow up, caused the browser loading spinner to go on indefinitely, and is causing a bunch of errors in the Vercel logs.  This commit fixes that issue.
> fix(entropy-explorer): fix infinite spinner

- Cargo.lock
- lazer/publisher_sdk/proto/governance_instruction.proto
- lazer/publisher_sdk/proto/state.proto
- lazer/publisher_sdk/rust/Cargo.toml
* Add allowed feed IDs to publisher state data.
* Add feature flags to state. They can be used in the future to alter the aggregator's behavior while keeping it deterministic.
* Add aggregated data to feed state.
* Add governance actions for new fields (except aggregated data).
Implementing state and governance.
> feat(lazer): add allowed feeds per publisher, aggregated prices and feature flags to state

- apps/developer-hub/content/docs/express-relay/index.mdx
- apps/developer-hub/content/docs/express-relay/integrate-as-searcher/index.mdx
> chore(express-relay): fix links for express relay

- packages/known-publishers/src/index.tsx
This is currently done by just commenting out all the doxxing info, so that if we decide to resurrect this we can do it easily.  We can properly clean it out & simplify the UI where we reference publishers down the line if it looks like this will stay.
> chore: remove publisher doxxing

- .github/workflows/docker-hip-3-pusher.yml
- apps/hip-3-pusher/.gitignore
- apps/hip-3-pusher/Dockerfile
- apps/hip-3-pusher/config/config.toml
- apps/hip-3-pusher/pyproject.toml
- apps/hip-3-pusher/src/hermes_listener.py
- apps/hip-3-pusher/src/hyperliquid_listener.py
- apps/hip-3-pusher/src/kms_signer.py
- apps/hip-3-pusher/src/lazer_listener.py
- apps/hip-3-pusher/src/main.py
- apps/hip-3-pusher/src/price_state.py
- apps/hip-3-pusher/src/publisher.py
- apps/hip-3-pusher/uv.lock
HIP-3 pusher application draft.
Serve as market data provider for HIP-3 deployers.
> feat: HIP-3 oracle pusher

- Cargo.lock
- lazer/sdk/rust/client/Cargo.toml
- lazer/sdk/rust/client/src/stream_client.rs
This PR aims to reduce lazer rust client memory usage
While we run the router stress test on lazer side, the high memory usage will lead to OOM Killed error in k8s pods. This will reduce the memory usage and fix the issue.
> Reduce lazer rust client memory usage

- apps/hip-3-pusher/config/config.toml
- apps/hip-3-pusher/pyproject.toml
- apps/hip-3-pusher/src/hermes_listener.py
- apps/hip-3-pusher/src/hyperliquid_listener.py
- apps/hip-3-pusher/src/lazer_listener.py
- apps/hip-3-pusher/src/main.py
- apps/hip-3-pusher/src/price_state.py
- apps/hip-3-pusher/src/publisher.py
- apps/hip-3-pusher/uv.lock
> feat(hip-3-pusher): Price fallback logic and staleness checks

- apps/fortuna/src/command/run.rs
We need this to generate api reference from open api schema
https://arc.net/l/quote/qinpvjym
> chore(fortuna) Add server tag in OpenAPI

- apps/hip-3-pusher/config/config.toml
- apps/hip-3-pusher/pyproject.toml
- apps/hip-3-pusher/src/main.py
- apps/hip-3-pusher/src/metrics.py
- apps/hip-3-pusher/src/publisher.py
- apps/hip-3-pusher/uv.lock
Add opentelemetry prometheus exporter and a couple metrics
> feat(hip-3-pusher): Basic metrics, other fixes

- Cargo.lock
- lazer/publisher_sdk/rust/Cargo.toml
- lazer/sdk/rust/protocol/Cargo.toml
- lazer/sdk/rust/protocol/src/jrpc.rs
This PR adds a new method to the jrpc protocol used in lazer agent.
This should allow agent to handle higher loads
manually tested
> feat: add push_updates method to jrpc lazer protocol

- contract_manager/store/chains/EvmChains.json
- contract_manager/store/contracts/EvmPriceFeedContracts.json
- contract_manager/store/contracts/EvmWormholeContracts.json
- governance/xc_admin/packages/xc_admin_common/src/chains.ts
> chore(price-feed): deploy price feed on batman

- Cargo.lock
- lazer/sdk/rust/client/Cargo.toml
- lazer/sdk/rust/client/src/history_client.rs
Remove constants and use values from config
> fix(lazer): use config values in history client

- lazer/contracts/sui/sdk/js/examples/fetch-and-verify-update.ts
- lazer/contracts/sui/sdk/js/package.json
- lazer/sdk/js/examples/history.ts
- lazer/sdk/js/examples/streaming.ts
- lazer/sdk/js/examples/symbols.ts
- lazer/sdk/js/package.json
- lazer/sdk/js/src/client.ts
- Change snake_case method names to camelCase
> fix(lazer/js/sdk): fix casing

- apps/insights/src/components/PriceFeed/header.tsx
- apps/insights/src/components/PriceFeed/price-feed-select.tsx
- apps/insights/src/components/PriceFeeds/coming-soon-list.tsx
- apps/insights/src/components/PriceFeeds/index.tsx
- apps/insights/src/components/PriceFeeds/price-feeds-card.tsx
- apps/insights/src/components/Publisher/performance.tsx
- apps/insights/src/components/Publisher/price-feeds.tsx
- apps/insights/src/components/Publisher/top-feeds-table.tsx
- apps/insights/src/components/Root/search-button.tsx
- packages/component-library/package.json
- packages/component-library/src/SymbolPairTag/index.module.scss
- packages/component-library/src/SymbolPairTag/index.stories.tsx
- packages/component-library/src/SymbolPairTag/index.tsx
- packages/component-library/src/omit-keys.ts
- pnpm-lock.yaml
Adding the PriceTag from IH as SymbolPairTag.
First use case for this is to use it as an example cell renderer for the new data grid in the component library.
> feat(component-library): add symbol pair tag

- target_chains/ethereum/contracts/contracts/entropy/Entropy.sol
- target_chains/ethereum/contracts/test/Entropy.t.sol
This PR removes the check that allows us to mark callbacks as failed (even if enough gas wasn't provided) if they revert with a non-empty return code.
When we wrote this initally, we thought that all out-of-gas reverts from calling contracts would bubble up and be caught by the `ret.length == 0` condition. However, we have found that some contracts catch out-of-gas reverts and then revert with a different error code. This means we can end up calling these callbacks without enough gas. 
Simple fix here is to require enough gas to be provided regardless of the revert code.
> fix(entropy): Only mark callbacks as failed if enough gas was provided, regardless of revert code

- Cargo.lock
- apps/pyth-lazer-agent/Cargo.toml
- apps/pyth-lazer-agent/src/publisher_handle.rs
* Detect update kind (price update or funding rate update)
* Send correct update kind in the transaction
Assuming all updates are funding rate updates is incorrect. This was causing issues with https://github.com/pyth-network/pyth-lazer/pull/865.
Not tested.
> fix(apps/pyth-lazer-agent): determine correct update type in /v2/publisher endpoint handler
