third_party/pyth/evm-watcher/.gitignore, third_party/pyth/evm-watcher/LICENSE, third_party/pyth/evm-watcher/jest.config.js, third_party/pyth/evm-watcher/package-lock.json, third_party/pyth/evm-watcher/package.json, third_party/pyth/evm-watcher/src/abi.json, third_party/pyth/evm-watcher/src/handler.ts, third_party/pyth/evm-watcher/src/index.ts, third_party/pyth/evm-watcher/src/listener.ts, third_party/pyth/evm-watcher/src/pyth-update-event.ts, third_party/pyth/evm-watcher/src/utils.ts, third_party/pyth/evm-watcher/src/watcher.ts, third_party/pyth/evm-watcher/src/watchers/logger.ts, third_party/pyth/evm-watcher/tsconfig.json
It has only the basic structure.
Some notes:
- Currently it has abi.json and I will point to our sdk abi when I release it. 
- Please take a look at PythUpdateEvent and let me know if we need any other information.
- It doesn't have Dockerfile and is not added to tilt. It will be added soon along with readiness checks.
- Currently no event is dispatched because multiple events should be combined into one.
=> Add watcher base files and structures

.github/workflows/image-push.yml
Also rename pyth-price to xc-server
=> Add p2w-attest image

ethereum/migrations/prod-receiver/8_pyth_update_interface_add_update_if_necessary.js, ethereum/migrations/prod/7_pyth_update_interface_add_update_if_necessary.js, ethereum/migrations/test/8_pyth_update_interface_add_update_if_necessary.js, ethereum/package-lock.json, ethereum/package.json
This update adds `updatePriceFeedsIfNecessary`
=> Update solidity sdk version

third_party/pyth/multisig-wh-message-builder/.eslintrc.js, third_party/pyth/multisig-wh-message-builder/.gitignore, third_party/pyth/multisig-wh-message-builder/LICENSE, third_party/pyth/multisig-wh-message-builder/README.md, third_party/pyth/multisig-wh-message-builder/jest.config.js, third_party/pyth/multisig-wh-message-builder/package-lock.json, third_party/pyth/multisig-wh-message-builder/package.json, third_party/pyth/multisig-wh-message-builder/src/index.ts, third_party/pyth/multisig-wh-message-builder/tsconfig.json
- Add project base
- Add initial trial
- add support for wormhole message
- add cli program
=> add pyth multisig cli program

third_party/pyth/multisig-wh-message-builder/README.md, third_party/pyth/multisig-wh-message-builder/package-lock.json, third_party/pyth/multisig-wh-message-builder/package.json, third_party/pyth/multisig-wh-message-builder/src/index.ts, third_party/pyth/multisig-wh-message-builder/src/util.ts, third_party/pyth/multisig-wh-message-builder/src/wallet.ts
thanks to @ali-bahjati for getting this 
one out!
=> add ledger support

pythnet/remote-executor/programs/remote-executor/src/state/governance_payload.rs, pythnet/remote-executor/programs/remote-executor/src/state/posted_vaa.rs
I got the addresses from :
https://www.notion.so/Pythnet-Pythtest-well-known-addresses-9a4ae47c32d64689946135f45c5e5db6
feel free to correct me.
=> Feature flag for bridge address

.github/workflows/remote-executor.yml
=> Add executor tests to CI

pythnet/remote-executor/Cargo.lock, pythnet/remote-executor/programs/remote-executor/Cargo.toml, pythnet/remote-executor/programs/remote-executor/src/error.rs, pythnet/remote-executor/programs/remote-executor/src/lib.rs, pythnet/remote-executor/programs/remote-executor/src/state/posted_vaa.rs, pythnet/remote-executor/programs/remote-executor/src/tests/executor_simulator.rs, pythnet/remote-executor/programs/remote-executor/src/tests/test_adversarial.rs
Fixes a bug in the AnchorVaa struct. The on-chain struct actually contains a magic number before the Vaa.
=> Fix AnchorVaa struct

third_party/pyth/multisig-wh-message-builder/src/index.ts, third_party/pyth/multisig-wh-message-builder/src/util.ts
Format-only PR. I just ran `npm run prettier`
=> Run prettier

third_party/pyth/multisig-wh-message-builder/src/util.ts
I had to fix this for typescript to compile.
=> Fix compilation error

third_party/pyth/multisig-wh-message-builder/src/index.ts
Add a couple bug fixes to the is-active command. Tested this with stan in solana mainnet and it works now.
=> set is-active fixes

aptos/example/Move.toml, aptos/example/sources/example.move
Minimal example of how to use the Pyth Aptos contract.
=> Add example Aptos contract

aptos/contracts/sources/pyth.move
This is a wrapper around `update_price_feeds_if_fresh` which allows users to pass a signer in, allowing it to be used as an entry function.
=> Add `update_price_feeds_if_fresh_with_funder` wrapper function

aptos/contracts/sources/pyth.move, aptos/contracts/sources/state.move, aptos/example/sources/example.move
Clarifying some common questions that have been asked.
=> Add explanatory comments

aptos/contracts/sources/pyth.move
Linking to these directly from the code, as this is most developers first point of entry.
=> Add link to on-demand and update fee docs

ethereum/contracts/pyth/PythGovernance.sol
This PR refactors our `executeGovernanceInstruction` to parse the payloads within itself and pass the action instruction payloads to their corresponding methods. Previously each method used to parse its data.
This was suggested by @tompntn on #355.
=> Refactor the governance code a bit

ethereum/.gitignore, ethereum/README.md, ethereum/forge-test/PythUpgradable.t.sol, ethereum/foundry.toml, ethereum/lib/README.md, ethereum/package.json, scripts/install-foundry.sh
This PR adds the foundry base and some docs about setting it up. 
I'm going to write some benchmark testa in foundry to measure our changes regarding contract optimization. 
Note: I got the install foundry script from wormhole repo.
=> Add foundry base

third_party/pyth/multisig-wh-message-builder/package-lock.json, third_party/pyth/multisig-wh-message-builder/package.json, third_party/pyth/multisig-wh-message-builder/src/index.ts
This command verifies that the given transaction is indeed created by the given payload.
The reason behind this is that it is not possible to verify a wormhole message in the UI. This can do that on the cli.
=> Add verify command for wormhole msg

ethereum/contracts/pyth/Pyth.sol
This PR reduces the gas cost of an unsuccesful `updatePriceIfNecessary`. It mostly modifies the publishTime check of this method to use publish time without querying prices nor any existence check. If a price does not exists then the publishTime is zero and the condition still works fine.
```
testBenchmarkUpdatePriceFeedsIfNecessaryFresh() (gas: -1743 (-0.458%)) 
testBenchmarkUpdatePriceFeedsIfNecessaryNotFresh() (gas: -18884 (-9.651%)) 
```
=> [eth]: Gas improvement: Optimize updatePriceFeedsIfNecessary

.github/workflows/remote-executor.yml
It was named "pre-commit" before. I recently removed the pre-commit part and it currently only has tests.
=> Update remove executor job name to test

.pre-commit-config.yaml, pythnet/remote-executor/programs/remote-executor/src/tests/executor_simulator.rs, pythnet/remote-executor/programs/remote-executor/src/tests/test_adversarial.rs, solana/pyth2wormhole/Cargo.lock, solana/pyth2wormhole/client/Cargo.toml, solana/pyth2wormhole/client/src/attestation_cfg.rs, solana/pyth2wormhole/client/src/batch_state.rs, solana/pyth2wormhole/client/src/lib.rs, solana/pyth2wormhole/client/src/main.rs, solana/pyth2wormhole/client/src/util.rs, solana/pyth2wormhole/client/tests/fixtures/passthrough.rs, solana/pyth2wormhole/client/tests/fixtures/pyth.rs, solana/pyth2wormhole/client/tests/test_attest.rs, solana/pyth2wormhole/client/tests/test_migrate.rs, solana/pyth2wormhole/client/tests/test_set_is_active.rs, solana/pyth2wormhole/program/src/attest.rs, solana/pyth2wormhole/program/src/config.rs, solana/pyth2wormhole/program/src/initialize.rs, solana/pyth2wormhole/program/src/lib.rs, solana/pyth2wormhole/program/src/message.rs, solana/pyth2wormhole/program/src/migrate.rs, solana/pyth2wormhole/program/src/set_config.rs, third_party/pyth/p2w-sdk/rust/src/lib.rs
Also enable auto fix option as it solves most of the obvious problems.
I advice at least one person review the mostly automated changes to the files.
Please note that I made some changes manually, for example `pyth_client` was deprecated and I changed it to use `pyth_sdk_solana::state`.
=> Add clippy to all rust projects

third_party/pyth/multisig-wh-message-builder/src/index.ts, third_party/pyth/multisig-wh-message-builder/src/multisig.ts
Squads doesn't have functions to :
- get all proposals for a given multisig
- get all instructions for a given proposal
This PR adds them to this package
=> Add some function to fetch the multisig state

third_party/pyth/multisig-wh-message-builder/src/index.ts
- Add localnet to clusters with placeholders that will get replaced when tilt integration happens
- Update verify to use getProposalInstructions
=> [multisig] Improve verify, add localnet

aptos/cli/package-lock.json, aptos/cli/package.json, aptos/cli/src/cli.ts, aptos/cli/src/commands/aptos.ts, aptos/cli/tsconfig.json
This is a simple CLI utility, designed to abstract some simple atomic operations on the Pyth Target Chain Aptos contracts.
=> Initial `pyth aptos` CLI

third_party/pyth/multisig-wh-message-builder/src/index.ts, third_party/pyth/multisig-wh-message-builder/src/wormhole.ts
This PR adds a check to stop `create` if the payload is already part of an existing proposal.
=> Check duplicates

cosmwasm/contracts/pyth/src/contract.rs, cosmwasm/contracts/pyth/src/error.rs, third_party/pyth/p2w-relay/src/index.ts, third_party/pyth/p2w-relay/src/relay/terra.ts
Add fee payment logic to update price feeds. I also added a mock wormhole contract so we can test the contract operations on the raw binary messages (which we needed for the fee test)
=> [cosmos] Pay fee + mock wormhole for testing

solana/pyth2wormhole/client/src/main.rs
This gives us a metric to learn more about attestation tx processing times. The buckets are exponential in range: 16, 32, 64, 128ms [...]  65.536 seconds.
=> [wormhole-attester] Add tx processing metric

third_party/pyth/multisig-wh-message-builder/src/index.ts
Adds a command that creates a proposal to transfer the upgrade authority of a program to the multisig.
=> [Multisig] add transfer auth to multisig

third_party/pyth/multisig-wh-message-builder/src/index.ts
Reverts pyth-network/pyth-crosschain#439
=> Revert "[Multisig] add transfer auth to multisig"

cosmwasm/contracts/pyth/src/contract.rs, cosmwasm/contracts/pyth/src/governance.rs, cosmwasm/contracts/pyth/src/msg.rs, third_party/pyth/p2w-relay/package-lock.json, third_party/pyth/p2w-relay/src/relay/terra.ts
Add queries for reading the update fee and the valid time period. Use this query in the terra test.
=> Add query methods to cosmwasm contract

xc-admin/packages/xc-admin-common/src/propose.ts
Squads proposal instructions start at index 1. LOL
=> [xc-admin] fix instructions indexes

xc-admin/package-lock.json, xc-admin/packages/xc-admin-cli/package.json, xc-admin/packages/xc-admin-cli/src/index.ts, xc-admin/packages/xc-admin-cli/tsconfig.json
This package should replace the current CLI.
=> [xc-admin] Start cli and add accept transfer for upgrade authorities

target-chains/cosmwasm/README.md, target-chains/cosmwasm/tools/package-lock.json, target-chains/cosmwasm/tools/package.json, target-chains/cosmwasm/tools/src/deploy-pyth-bridge.ts, target-chains/cosmwasm/tools/src/deploy.ts, target-chains/cosmwasm/tools/src/deployer/config.ts, target-chains/cosmwasm/tools/src/deployer/index.ts, target-chains/cosmwasm/tools/src/deployer/injective.ts, target-chains/cosmwasm/tools/src/deployer/osmosis.ts, target-chains/cosmwasm/tools/src/deployer/terra.ts, target-chains/cosmwasm/tools/src/network.ts, target-chains/cosmwasm/tools/src/pyth_config.ts
This PR includes
- add config - for localterra
- add feature - update contract admin 
- add feature - get contract info 
- refactor the yargs command structure
- update the README
=> [cosmwasm] Deploy tool: Add new commands (update contract admin + get contract info)

xc-admin/package-lock.json, xc-admin/packages/xc-admin-common/package.json, xc-admin/packages/xc-admin-common/src/__tests__/PythMultisigInstruction.test.ts, xc-admin/packages/xc-admin-common/src/__tests__/WormholeMultisigInstruction.test.ts, xc-admin/packages/xc-admin-common/src/multisig_transaction/PythMultisigInstruction.ts, xc-admin/packages/xc-admin-common/src/multisig_transaction/index.ts, xc-admin/packages/xc-admin-common/src/wormhole.ts
Add PythMultisigInstruction and tests.
=> [xc admin] Pyth parser

governance/xc-admin/package-lock.json, governance/xc-admin/packages/crank-executor/package.json
We didn't import xc-admin-common
=> Fix package json for the crank 

price-service/package-lock.json, price-service/package.json, price-service/src/__tests__/rest.test.ts, price-service/src/index.ts, price-service/src/listen.ts, price-service/src/rest.ts
Wormhole new sdk does not use wasm and is cleaner. It makes our code one step closer to no wasm too.
=> [price-service] Update wormhole sdk package

target-chains/cosmwasm/Cargo.lock, target-chains/cosmwasm/contracts/pyth/Cargo.toml, target-chains/cosmwasm/contracts/pyth/src/contract.rs, target-chains/cosmwasm/contracts/pyth/src/lib.rs, target-chains/cosmwasm/contracts/pyth/src/msg.rs, target-chains/cosmwasm/contracts/pyth/src/state.rs
- removed dependency pyth-sdk-cw
- add dependency pyth-sdk
- update contract logic to use latest price feed information and structs
=> [cosmwasm] update contract

governance/xc-governance-sdk-js/src/instructions.ts
This sdk is used to generate governance instructions.
=> [xc-governance-sdk] Add cosmwasm upgrade ix

SECURITY.md
updating to reflect new bounty
=> updating security.md

package-lock.json
=> [refactor] Remove package-lock.json in the root

package-lock.json
My npm made this change when I called `npm install`
=> [node] Update package lock

target_chains/ethereum/truffle-config.js
hdwallet package was updated in the PR bringing lerna to this repo. In the new package the constructor arguments have changed. This PR updates that and adds a helper function to make the config more clear.
=> [ethereum] Update truffle config

.github/workflows/xc-admin-image-push.yaml
Workflow will be triggered when we release `xc-admin-v`
=> Add workflow for xc-admin releases

price_service/server/package.json
This new release contains @jayantk PR to exclude old VAAs.
=> [price-service] Bump version to 2.3.4

package-lock.json
I don't know why i missed this package lock file.
=> [lerna] Update the lock after price server upgrade

target_chains/cosmwasm/build.sh
build.sh is using third_party folder to use p2w-sdk 
it should use wormhole_attester
=> [cosmwasm] fix build.sh script

governance/xc_admin/packages/xc_admin_frontend/components/common/CopyPubkey.tsx, governance/xc_admin/packages/xc_admin_frontend/components/tabs/Proposals.tsx, governance/xc_admin/packages/xc_admin_frontend/hooks/usePyth.ts
- fix urlsIndex not being reset to 0 when changing cluster
- fix proposals accept/reject buttons not centered when on mobile view
- add verified tag to individual proposals
=> [xc-admin] add verified/unverified tags for individual proposals

target_chains/cosmwasm/examples/cw-contract/Cargo.lock, target_chains/cosmwasm/examples/cw-contract/Cargo.toml, target_chains/cosmwasm/examples/cw-contract/src/contract.rs, target_chains/cosmwasm/examples/cw-contract/src/msg.rs, target_chains/cosmwasm/examples/cw-contract/src/state.rs, target_chains/cosmwasm/pyth-sdk-cw/src/lib.rs
=> [cosmwasm] Update example contract

governance/xc_admin/packages/crank_executor/src/index.ts
Executor crank needs to create product account when it sees an addProduct instruction.
=> [xc-admin] crank executor add product

governance/xc_admin/packages/xc_admin_frontend/components/tabs/General.tsx, governance/xc_admin/packages/xc_admin_frontend/hooks/usePyth.ts
=> [xc-admin-frontend] Some cleanup

governance/xc_admin/packages/xc_admin_frontend/components/tabs/General.tsx
Before this PR, the modal doesn't show symbol for new price feeds.
Let me know if you think of a better way to do it.
=> Display symbol for new price feeds

target_chains/ethereum/sdk/js/src/examples/EvmRelay.ts
We have a discord question about how to use getPrice. Add it to the example code so it's clear.
=> [sdk] add getPrice call to example

package-lock.json, target_chains/ethereum/contracts/.gitignore, target_chains/ethereum/contracts/Deploying.md, target_chains/ethereum/contracts/hardhat.config.ts, target_chains/ethereum/contracts/networks/324.json, target_chains/ethereum/contracts/package.json, target_chains/ethereum/contracts/scripts/receiverSubmitGuardianSetUpgrades.js, target_chains/ethereum/contracts/truffle-config.js, target_chains/ethereum/sdk/js/package.json, target_chains/ethereum/sdk/js/src/index.ts
I needed to update the zkSync packages to get the deployment working and also added some packages for zksync verify. 
p.s: This PR also adds verify url for shimmer testnet
=> [eth] Add zksync mainnet

target_chains/cosmwasm/pyth-sdk-cw/README.md
so people can find the methods for pricing lp tokens and such
=> Add links to common SDK documentation

governance/xc_admin/packages/xc_admin_frontend/hooks/useMultisig.ts
Import same logic from `usePyth`
=> [xc-admin] Reset urlIndex for useMultisig

.github/workflows/publish-js.yml
=> [sdk] Fix CI workflow

.github/workflows/release-pyth-cosmwasm-contract.yml
This PR implements the release pipeline for cosmwasm contracts.
=> [cosmwasm] Release Contract

.github/workflows/release-pyth-cosmwasm-contract.yml
This pr uses the build tool and release a separate contract for injective.
=> [cosmwasm] contracts release

governance/xc_admin/packages/xc_admin_cli/README.md, governance/xc_admin/packages/xc_admin_common/package.json, governance/xc_admin/packages/xc_admin_common/src/cluster.ts, governance/xc_admin/packages/xc_admin_common/src/wormhole.ts, governance/xc_admin/packages/xc_admin_frontend/components/ClusterSwitch.tsx, governance/xc_admin/packages/xc_admin_frontend/components/tabs/Proposals.tsx, governance/xc_admin/packages/xc_admin_frontend/hooks/useMultisig.ts, governance/xc_admin/packages/xc_admin_frontend/utils/pythClusterApiUrl.ts, package-lock.json
Adding the new instance of pyth for cross-chain prices from pythtest
=> [xc-admin] Add pythtest-crosschain

target_chains/cosmwasm/tools/package-lock.json, target_chains/cosmwasm/tools/package.json, target_chains/cosmwasm/tools/src/chains-manager/chain-executor.ts, target_chains/cosmwasm/tools/src/chains-manager/chain-querier.ts, target_chains/cosmwasm/tools/src/chains-manager/cosmwasm.ts, target_chains/cosmwasm/tools/src/chains-manager/injective.ts, target_chains/cosmwasm/tools/src/pyth-wrapper.ts
Work still in progress. In order to keep this PR small. Other things will be done in further PRs
This PR adds the generic code to the repo.
=> [cosmwasm] Refactor deployer

governance/xc_admin/packages/xc_admin_cli/src/index.ts, governance/xc_admin/packages/xc_admin_common/package.json, governance/xc_admin/packages/xc_admin_frontend/components/tabs/General.tsx, package-lock.json
Bump Pyth client so that initPrice gets renamed to setExponent
=> Rename init price

governance/xc_admin/packages/xc_admin_cli/src/index.ts, governance/xc_admin/packages/xc_admin_common/src/__tests__/UpgradeContract.test.ts, governance/xc_admin/packages/xc_admin_common/src/governance_payload/UpgradeContract.ts, governance/xc_admin/packages/xc_admin_common/src/governance_payload/index.ts
Add support in xc_admin to generate cosmos upgrade payloads.
=> [xc-admin] Add ser/de for Cosmos Upgrades

.github/workflows/release-pyth-cosmwasm-contract.yml, target_chains/cosmwasm/Cargo.lock, target_chains/cosmwasm/contracts/pyth/Cargo.toml, target_chains/cosmwasm/sdk/rust/Cargo.toml, target_chains/cosmwasm/tools/src/build-contract.ts
- update pyth sdk cw version
- update contract's version
- add osmosis to release pipeline
- add osmosis to build contract script
=> [cosmwasm] osmosis release

accumulator_updater/programs/accumulator_updater/src/instructions/put_all.rs, accumulator_updater/programs/accumulator_updater/src/state/accumulator_input.rs, accumulator_updater/programs/accumulator_updater/src/state/whitelist.rs, accumulator_updater/programs/mock-cpi-caller/src/instructions/add_price.rs, accumulator_updater/programs/mock-cpi-caller/src/instructions/mod.rs, accumulator_updater/programs/mock-cpi-caller/src/instructions/update_price.rs, accumulator_updater/tests/accumulator_updater.ts
Update whitelist verification mechanism to use a signed PDA from the CPI caller
=> accumulator-updater 8/x] - whitelist verification pda auth

target_chains/ethereum/examples/oracle_swap/README.md, target_chains/ethereum/examples/oracle_swap/app/package-lock.json
I tried to use the oracle AMM and want to add some docs that would've been useful to me.
=> [docs] improve oracle amm

package-lock.json, target_chains/cosmwasm/tools/package.json, target_chains/ethereum/contracts/foundry.toml, target_chains/ethereum/contracts/truffle-config.js, target_chains/sui/contracts/sources/pyth.move, tilt_devnet/docker_images/Dockerfile.cosmwasm, tilt_devnet/k8s/terra-devnet.yaml
This PR fixes the tilt issues and makes it green again!
The most important change is reducing the optimization runs of the Eth contract because it had reached the limit. After we complete the migration to the accumulator we can remove the batch vaa code to save up some space.
=> [tilt] Fix issues

pythnet/pythnet_sdk/Cargo.toml, pythnet/pythnet_sdk/src/lib.rs
fix programIds & addresses for pythnet, fix solana-client & solana-sdk dev-dependencies
=> [pythnet-sdk]: fix addresses & programIds in pythnet-sdk

pythnet/message_buffer/Anchor.toml, pythnet/message_buffer/package.json, pythnet/message_buffer/programs/mock-cpi-caller/src/lib.rs, pythnet/message_buffer/scripts/setup_message_buffer.ts, pythnet/message_buffer/tsconfig.json
add init-buffer script thats used by integration repo
=> [message-buffer 16/x] - integration repo scripts

governance/xc_admin/packages/xc_admin_common/src/propose.ts
Test increasing commitment requirements to fix simulation failures.
=> [xc-admin] Fix simulation issues

.github/workflows/remote-executor.yml, governance/remote_executor/Cargo.toml, governance/remote_executor/programs/remote-executor/Cargo.toml
=> [remote-executor] Move overflow check

governance/remote_executor/cli/src/main.rs
Addresses : 
TOB-PYTH-14
TOB-PYTH-15
=> [remote-executor] Remove rent hack

target_chains/ethereum/examples/oracle_swap/README.md, target_chains/ethereum/examples/oracle_swap/app/src/OrderEntry.tsx
fixing some issues found by a community member
=> Fix oracle swap example and add docs

pythnet/pythnet_sdk/src/wire.rs
The equality logic was flipped by mistake
=> [pythnet-sdk] Bugfix for magic value check and additional serde test

governance/xc_admin/packages/xc_admin_cli/src/index.ts, governance/xc_admin/packages/xc_admin_common/src/propose.ts
Adding this because I got frustrated of writing it manually everytime.
=> [Xc admin cli] add and remove members

.github/workflows/xc-admin-frontend-image-push.yaml, governance/xc_admin/packages/xc_admin_frontend/Dockerfile
also add the build step (but not the publish step) to run during CI.
=> Fix docker build for xc_admin_frontend

hermes/Cargo.lock, hermes/Cargo.toml, hermes/src/api.rs
One of the beta testers reported this. I verified that it works using [this](https://github.com/njgibbon/nicks-cors-test/tree/main) simple test.
Also format the Cargo.toml to match its initial style
=> [hermes] fix cors bug

hermes/src/api.rs, hermes/src/api/rest.rs, hermes/src/store.rs
This PR adds a very simple health probe that returns false if it hasn't updated its state for more than 30 seconds. I have hard-coded the value for now. I will make the hard-coded values more configurable in another PR.
=> [hermes] Add health probe

price_pusher/package.json, price_pusher/src/sui/command.ts, price_pusher/src/sui/sui.ts
I changed to Map and didn't test the change, and i forgot to change this line 🤦
=> [price_pusher] Fix bug from last PR

pythnet/pythnet_sdk/src/wire.rs, pythnet/pythnet_sdk/src/wire/de.rs
This PR works around a WASM bug caused by accidental floating point behaviour triggered by Serde when deserializing an enum variant. The relevant comment can be found in the `de.rs` file but the comment is copied here for PR visibility:
```
// When serializing/deserializing, serde passes a variant_index into the handlers. We
// currently write these as u8's and have already parsed' them during deserialize_enum
// before we reach this point.
//
// Normally, when deserializing enum tags from a wire format that does not match the
// expected size, we would use a u*.into_deserializer() to feed the already parsed
// result into the visit_u64 visitor method during `__Field` deserialize.
//
// The problem with this however is during `visit_u64`, there is a possibility the
// enum variant is not …
```
=> Avoid EnumAccess triggering `visit_u64` in Serde Visitor.

target_chains/sui/contracts/sources/merkle_tree.move
- implement and test a Merkle tree data structure in Move using [Sui Move stdlib](https://github.com/MystenLabs/sui/blob/main/crates/sui-framework/packages/move-stdlib/sources/vector.move) and [Sui Wormhole lib](https://github.com/wormhole-foundation/wormhole/tree/main/sui/wormhole/sources)
- `constructProofs` for constructing a Merkle tree
- `isProofValid` for checking for inclusion in the Merkle tree
```
[pyth-crosschain/target_chains/sui/contracts]$ sui move test
```
Sui version: `sui 0.33.0-f65b02ccc`
=> [sui 10/x] - merkle tree

target_chains/sui/contracts/sources/batch_price_attestation.move, target_chains/sui/contracts/sources/data_source.move, target_chains/sui/contracts/sources/governance/governance_instruction.move, target_chains/sui/contracts/sources/i64.move, target_chains/sui/contracts/sources/price.move, target_chains/sui/contracts/sources/price_feed.move, target_chains/sui/contracts/sources/price_identifier.move, target_chains/sui/contracts/sources/price_info.move, target_chains/sui/contracts/sources/price_status.move
- simplify code with the help of Move linter (made by Pontem) from PyCharm IntelliJ marketplace
=> [sui 14/x] - PyCharm Move linter

target_chains/ethereum/contracts/networks/338.json
This file was accidentally removed in a PR I merged recently. This commit just restores it.
=> Restore accidentally removed file

governance/remote_executor/Anchor.toml
Just making it easier for someone to use this repo by enabling `anchor test` to run the tests
=> [remote-executor] Small quality of life improvement

governance/xc_admin/packages/xc_admin_common/src/governance_payload/BufferLayoutExt.ts
Inspired by https://github.com/solana-labs/buffer-layout/blob/master/src/Layout.ts
=> Fix Uint64BE encoding/decoding on browsers

governance/xc_admin/packages/xc_admin_frontend/components/InstructionViews/AccountUtils.tsx, governance/xc_admin/packages/xc_admin_frontend/components/InstructionViews/WormholeInstructionView.tsx, governance/xc_admin/packages/xc_admin_frontend/components/InstructionViews/utils.ts, governance/xc_admin/packages/xc_admin_frontend/components/tabs/General.tsx, governance/xc_admin/packages/xc_admin_frontend/components/tabs/Proposals.tsx, governance/xc_admin/packages/xc_admin_frontend/contexts/MultisigContext.tsx, governance/xc_admin/packages/xc_admin_frontend/contexts/PythContext.tsx, governance/xc_admin/packages/xc_admin_frontend/hooks/useMultisig.ts, governance/xc_admin/packages/xc_admin_frontend/pages/index.tsx, governance/xc_admin/packages/xc_admin_frontend/styles/globals.css
Small refactors and move the proposal instructions fetching inside the proposal component to avoid excessive rpc usage when the page is loaded
=> Xc admin frontend refactor

governance/xc_admin/packages/xc_admin_frontend/components/tabs/Proposals.tsx
Also add some missing dependencies and formatting fixes
=> [xc-admin-frontend] Reset currentProposalPubkey when it is removed from the url

hermes/Cargo.lock, hermes/Cargo.toml, hermes/src/api/rest.rs, hermes/src/api/types.rs, hermes/src/doc_examples.rs, hermes/src/main.rs
I went through everything and updated the final values that were missing. I also found a way to extract out replicated example values to a single file so that they aren't hardcoded in a bunch of places.
=> [hermes] Finish up docs

contract_manager/scripts/check_proposal.ts, contract_manager/src/chains.ts, contract_manager/src/contracts/evm.ts, contract_manager/src/contracts/wormhole.ts, contract_manager/src/shell.ts, target_chains/ethereum/contracts/Deploying.md, target_chains/ethereum/contracts/deploy/zkSyncDeploy.ts, target_chains/ethereum/contracts/scripts/batchDeploy.ts, target_chains/ethereum/contracts/scripts/batchDeployReceivers.ts
Scripts for deploying the wormhole-receiver to all chains and some small improvements on contract manager side
=> [evm] Wormhole receiver deploy all

hermes/Cargo.lock, hermes/Cargo.toml
Bump hermes version to include logging in our next release.
=> ci(hermes): bump hermes version

hermes/Cargo.toml
Just a minor cleanup of Cargo.toml to provide an easier to read file with smaller diffs in future.
=> chore(hermes): visual clean up of Cargo.toml

governance/xc_admin/packages/xc_admin_common/src/deterministic_oracle_accounts.ts
Update xc-admin to create new Pythnet accounts with the new size
=> Price account v2 for remote clusters

hermes/Cargo.lock, hermes/Cargo.toml, hermes/shell.nix, hermes/src/main.rs
- Add EnvFilter to respect RUST_LOG
- Disable ANSI if stderr is not a terminal
=> fix(hermes): improve tracing logs

governance/xc_admin/packages/xc_admin_common/src/__tests__/SystemProgramInstruction.test.ts, governance/xc_admin/packages/xc_admin_common/src/multisig_transaction/SystemProgramInstruction.ts, governance/xc_admin/packages/xc_admin_common/src/multisig_transaction/index.ts, governance/xc_admin/packages/xc_admin_frontend/components/InstructionViews/WormholeInstructionView.tsx, governance/xc_admin/packages/xc_admin_frontend/components/tabs/Proposals.tsx, governance/xc_admin/packages/xc_admin_frontend/utils/lamportsToSol.ts
This will be useful for proposals concerning PGAS transfers like this current one : 
https://xc-admin-frontend-git-xc-admin-add-system-instructions-pyth-web.vercel.app/?tab=proposals&proposal=9Xz8Ea8saZTKeRHnY1Evd235SqBtHokLeArRmE9A686A
=> Add system instruction

target_chains/sui/contracts/sources/merkle_tree.move
Analysis was done with [sui replay tool](https://github.com/MystenLabs/sui/pull/12680):
```
env MOVE_VM_PROFILE=1  ./sui-tool replay --rpc https://fullnode.mainnet.sui.io:443 tx -t DAKY6wVqkM1jybpCwa8HPL9XrNpEEVJF6cvJHeA7JbCo
env MOVE_VM_PROFILE=1  ./sui-tool replay --rpc https://fullnode.mainnet.sui.io:443 tx -t 5Kw1SvhAAaST5CVHByC5BtZwnCbj7fP6EFgqsahJ5ZQf
```
These are both transactions updating an identical set of feeds (3 feeds) on mainnet contracts:
Before optimization:
After optimization:
There is a 6x improvement visible although some of it might be related to sui gas bucketing. After this optimization, the cost of updating a single batch should (0.0062) is similar to updating 3 individual feeds (0.0069).
=> Optimize merkle tree computations gas usage by minimizing vector data movements

price_pusher/package.json, price_pusher/src/sui/command.ts, price_pusher/src/sui/sui.ts
Make sure the sui pusher will not break upon package upgrade
=> [price-pusher] Sui pusher forward compatibility

hermes/Cargo.lock, hermes/Cargo.toml, hermes/src/api.rs, hermes/src/api/ws.rs, hermes/src/config/rpc.rs
- Add max message size for incoming messages
- Add sent message rate limit and ip whitelisting
=> patch(hermes): improve ws reliability

governance/xc_admin/packages/xc_admin_cli/src/index.ts, governance/xc_admin/packages/xc_admin_common/src/__tests__/BpfUpgradableLoaderInstruction.test.ts, governance/xc_admin/packages/xc_admin_common/src/multisig_transaction/BpfUpgradableLoaderMultisigInstruction.ts, governance/xc_admin/packages/xc_admin_common/src/multisig_transaction/index.ts, governance/xc_admin/packages/xc_admin_frontend/components/InstructionViews/WormholeInstructionView.tsx, governance/xc_admin/packages/xc_admin_frontend/components/tabs/Proposals.tsx
Add bpf-loader instructions with : 
- upgrade
- close
- set authority
=> [xc-admin] add bpf loader

contract_manager/store/chains/EvmChains.yaml, contract_manager/store/contracts/EvmContracts.yaml, governance/xc_admin/packages/xc_admin_common/src/chains.ts, target_chains/ethereum/contracts/networks/534352.json, target_chains/ethereum/contracts/networks/88882.json
=> chore(evm): deploy to new networks

README.md, contract_manager/scripts/update_pricefeed.ts, price_pusher/README.md, price_pusher/config.aptos.testnet.sample.json, price_pusher/config.evm.testnet.sample.json, price_pusher/config.injective.testnet.sample.json, price_pusher/config.sui.mainnet.sample.json, price_pusher/config.sui.testnet.sample.json, price_service/client/js/README.md, price_service/client/js/package.json, price_service/server/README.md, target_chains/aptos/examples/mint_nft/app/src/App.tsx, target_chains/aptos/sdk/js/README.md, target_chains/aptos/sdk/js/package.json, target_chains/ethereum/examples/oracle_swap/app/src/App.tsx, target_chains/ethereum/examples/oracle_swap/app/src/OrderEntry.tsx, target_chains/ethereum/sdk/js/README.md, target_chains/ethereum/sdk/js/package.json, target_chains/sui/sdk/js/README.md, target_chains/sui/sdk/js/package.json
Also bumps the versions so the latest version of published packages contain the new readme.
=> chore: remove price service mentions in the repo

pyth-rng/Cargo.lock, pyth-rng/Cargo.toml, pyth-rng/src/api.rs, pyth-rng/src/api/live.rs, pyth-rng/src/api/metrics.rs, pyth-rng/src/api/ready.rs, pyth-rng/src/api/revelation.rs, pyth-rng/src/command/generate.rs, pyth-rng/src/command/get_request.rs, pyth-rng/src/command/register_provider.rs, pyth-rng/src/command/request_randomness.rs, pyth-rng/src/command/run.rs, pyth-rng/src/config.rs, pyth-rng/src/ethereum.rs, pyth-rng/src/main.rs, pyth-rng/src/state.rs
A handful of easy small improvements here:
* replace println! with tracing
* add liveness / readiness endpoints
* add prometheus metrics skeleton (not actually tracking anything useful right now)
* use anyhow::Result
=> [pyth-rng] A few small improvements

package.json, target_chains/ethereum/entropy_sdk/solidity/README.md, target_chains/ethereum/examples/coin_flip/README.md, target_chains/ethereum/examples/coin_flip/app/.gitignore, target_chains/ethereum/examples/coin_flip/app/package.json, target_chains/ethereum/examples/coin_flip/app/src/CoinFlipAbi.json, target_chains/ethereum/examples/coin_flip/app/src/flip_coin.ts, target_chains/ethereum/examples/coin_flip/app/tsconfig.json, target_chains/ethereum/examples/coin_flip/contract/scripts/deploy.sh, target_chains/ethereum/examples/coin_flip/contract/src/CoinFlip.sol
I'm putting finishing touches on the user docs and examples so we can share entropy with some users.
=> [entropy] Typescript code for coin flip example + docs

fortuna/Cargo.lock, target_chains/ethereum/entropy_sdk/solidity/README.md
Added a couple things to the readme that I forgot earlier.
=> [entropy] Minor readme edits

price_pusher/README.md, price_pusher/package.json, price_pusher/src/price-config.ts
I'm waiting for fireblocks so I'm picking up this easy task in the meanwhile.
=> [scheduler] Default to early updates

governance/xc_admin/packages/xc_admin_common/src/cluster.ts, governance/xc_admin/packages/xc_admin_frontend/components/PermissionDepermissionKey.tsx, governance/xc_admin/packages/xc_admin_frontend/components/tabs/General.tsx
Enable 64 publishers for pythtest networks
=> [xc-admin] Ship 64 pubs

target_chains/near/README.md, target_chains/near/example/src/lib.rs
Improves the example to show how to use multiple price feed values.
=> docs(near): improve example

governance/xc_admin/packages/xc_admin_cli/src/index.ts, governance/xc_admin/packages/xc_admin_common/src/multisig_transaction/SolanaStakingMultisigInstruction.ts, governance/xc_admin/packages/xc_admin_common/src/multisig_transaction/index.ts
It only supports deactivate for now
=> Add staking instructions to xc-admin

governance/multisig_wh_message_builder/src/index.ts, governance/xc_admin/packages/crank_pythnet_relayer/src/index.ts, governance/xc_admin/packages/xc_admin_common/src/wormhole.ts
They are deprecating the old guardians rpcs
=> Update wormhole endpoint for cranks

target_chains/ethereum/contracts/contracts/executor/Executor.sol, target_chains/ethereum/contracts/contracts/executor/ExecutorErrors.sol, target_chains/ethereum/contracts/forge-test/Executor.t.sol
Fixes:
2. Lack of contract existence check on low-level call
=> [entropy] audit - 2. lack of contract existence check

.github/workflows/release-pyth-cosmwasm-contract.yml, target_chains/cosmwasm/deploy-scripts/package.json
This CI was broken because :
- Now the code to build is in `deploy-scripts` and not `tools`
- `deploy-scripts` didn't specify `yargs` as a dep.
=> [cosmwasm] Fix release ci

target_chains/solana/README.md, target_chains/solana/cli/src/main.rs, target_chains/solana/programs/pyth-solana-receiver/src/error.rs, target_chains/solana/programs/pyth-solana-receiver/src/lib.rs, target_chains/solana/programs/pyth-solana-receiver/src/sdk.rs, target_chains/solana/programs/pyth-solana-receiver/tests/common/mod.rs, target_chains/solana/programs/pyth-solana-receiver/tests/test_post_price_update_from_vaa.rs, target_chains/solana/programs/pyth-solana-receiver/tests/test_post_updates.rs, target_chains/solana/programs/pyth-solana-receiver/tests/test_post_updates_atomic.rs
post_updates -> post_update
post_updates_atomic -> post_update_atomic
=> [solana] Rename to singular

governance/xc_admin/packages/xc_admin_common/src/cluster.ts
Let me know if you want Pythnet too
=> [xc-admin] pythtest -> 64 pubs

express_relay/sdk/js/src/index.ts
update JS SDK signature to simpler signature format
=> simplify signature fix

target_chains/ethereum/entropy_sdk/solidity/README.md, target_chains/ethereum/entropy_sdk/solidity/package.json
=> [entropy] Remove warning in SDK docs

target_chains/solana/Cargo.lock, target_chains/solana/pyth_solana_receiver_state/Cargo.toml, target_chains/solana/pyth_solana_receiver_state/src/error.rs, target_chains/solana/pyth_solana_receiver_state/src/lib.rs, target_chains/solana/pyth_solana_receiver_state/src/price_update.rs
Add some functions that people can use in their smart contract to consumer `PriceUpdateV1` accounts.
I need to add some more unit tests.
=> feat(solana) : rust sdk

target_chains/solana/Cargo.lock, target_chains/solana/Cargo.toml, target_chains/solana/programs/pyth-solana-receiver/src/error.rs, target_chains/solana/programs/pyth-solana-receiver/src/lib.rs, target_chains/solana/programs/pyth-solana-receiver/tests/test_governance.rs
- pin `wormhole-core-bridge-solana`
- Disallow `minimum_signatures` == 0
- Add some warnings to post_update_atomic
- Add some comments
- Merge constraints
=> fix: audit feedback 1

price_pusher/README.md, target_chains/README.md, target_chains/ethereum/contracts/VERIFY.md, target_chains/sui/cli/README.md
=> fix: typos

package.json, target_chains/solana/sdk/js/pyth_solana_receiver/package.json
We need some features from 1.5.0
=> fix: constrain @pythnetwork/price-service-sdk in @pythnetwork/pyth-solana-receiver

target_chains/solana/program_simulator/src/lib.rs, target_chains/solana/programs/pyth-solana-receiver/src/lib.rs, target_chains/solana/programs/pyth-solana-receiver/tests/test_post_price_update_from_vaa.rs, target_chains/solana/programs/pyth-solana-receiver/tests/test_post_updates.rs, target_chains/solana/programs/pyth-solana-receiver/tests/test_post_updates_atomic.rs, target_chains/solana/pyth_solana_receiver_sdk/src/price_update.rs
Adds the slot where a price update got posted
=> feat: add posted slot

pythnet/pythnet_sdk/Cargo.toml, target_chains/solana/pyth_solana_receiver_sdk/Cargo.toml
I need this to publish the crates
=> chore: add licenses before publishing

target_chains/solana/sdk/js/pyth_solana_receiver/package.json, target_chains/solana/sdk/js/pyth_solana_receiver/src/idl/pyth_solana_receiver.ts
New release after the program upgrade
=> chore: bump js sdk

governance/xc_admin/packages/xc_admin_frontend/hooks/useMultisig.ts, governance/xc_admin/packages/xc_admin_frontend/hooks/usePyth.ts, governance/xc_admin/packages/xc_admin_frontend/utils/pythClusterApiUrl.ts
So we can configure them for the new infra.
=> chore: env variables for rpcs

target_chains/ethereum/examples/oracle_swap/README.md, target_chains/ethereum/examples/oracle_swap/contract/package-lock.json, target_chains/ethereum/examples/oracle_swap/contract/package.json, target_chains/ethereum/examples/oracle_swap/contract/remappings.txt, target_chains/ethereum/examples/oracle_swap/contract/src/OracleSwap.sol, target_chains/ethereum/examples/oracle_swap/contract/test/OracleSwap.t.sol
This PR includes:
- Bumping the `forge-std` version.
- Bumping `solidity-sdk` to `v3.0.0`
=> Update price evm Oracle Example

package.json, price_pusher/config.solana.testnet.sample.json, price_pusher/package.json, price_pusher/src/index.ts, price_pusher/src/solana/command.ts, price_pusher/src/solana/solana.ts, target_chains/solana/programs/pyth-push-oracle/src/lib.rs, target_chains/solana/pyth_solana_receiver_sdk/src/lib.rs, target_chains/solana/sdk/js/pyth_solana_receiver/package.json, target_chains/solana/sdk/js/pyth_solana_receiver/src/PythSolanaReceiver.ts, target_chains/solana/sdk/js/pyth_solana_receiver/src/address.ts, target_chains/solana/sdk/js/pyth_solana_receiver/src/idl/pyth_push_oracle.ts
It implements a price pusher for Solana. It works already but I'm sure the transaction sending logic will need to be finetuned more.
=> feat(price_pusher): solana price pusher

price_pusher/src/solana/solana.ts
Devnet pusher ran out of SOL super fast because I wasn't closing the accounts
=> feat(pusher): cleanup vaa accounts

governance/xc_admin/packages/proposer_server/src/index.ts, governance/xc_admin/packages/xc_admin_common/src/propose.ts, governance/xc_admin/packages/xc_admin_frontend/components/tabs/Proposals.tsx, governance/xc_admin/packages/xc_admin_frontend/package.json, target_chains/solana/sdk/js/solana_utils/package.json, target_chains/solana/sdk/js/solana_utils/src/transaction.ts
I wrote new retry/send logic for the transactions.
It's not perfect but the goal is to unblock xc-admin asap
=> perf: improve tx land rate

target_chains/solana/sdk/js/solana_utils/package.json, target_chains/solana/sdk/js/solana_utils/src/__tests__/TransactionSize.test.ts, target_chains/solana/sdk/js/solana_utils/src/transaction.ts
I need to this to implement priority fees in the staking website
=> feat(solana_utils): support account lookup table

price_pusher/package.json, price_pusher/src/solana/solana.ts, target_chains/solana/sdk/js/pyth_solana_receiver/src/PythSolanaReceiver.ts, target_chains/solana/sdk/js/pyth_solana_receiver/src/compute_budget.ts, target_chains/solana/sdk/js/pyth_solana_receiver/src/vaa.ts, target_chains/solana/sdk/js/solana_utils/src/transaction.ts
I want to try deploying it to mainnet even if right now it barely lands
=> feat(price_pusher): use retry send transaction logic in pusher

hermes/Cargo.lock, hermes/Cargo.toml, hermes/src/api.rs, hermes/src/api/rest.rs, hermes/src/api/sse.rs, hermes/src/main.rs
add SSE endpoint that uses the v2 schema
=> feat(hermes): add sse endpoint

governance/xc_admin/packages/crank_pythnet_relayer/src/index.ts
This is useful so the cranks don't get stuck in the price feed council if there are duplicate changes (ex: adding a publisher that's already permissioned, deleting a pub that's already been deleted, creating a price feed twice).
=> feat(crank_pythnet_relayer) : add parameter to skip failed remote instructions

hermes/Cargo.lock, hermes/Cargo.toml, hermes/src/api.rs, hermes/src/api/rest.rs, hermes/src/api/rest/index.rs, hermes/src/api/rest/v2/latest_price_updates.rs, hermes/src/api/rest/v2/mod.rs, hermes/src/api/rest/v2/sse.rs, hermes/src/api/rest/v2/timestamp_price_updates.rs, hermes/src/api/sse.rs
- **add allow_unordered query param**
- **add benchmarks_only query param**
- **update docs**
=> feat(hermes): add additional sse features

target_chains/solana/Cargo.lock, target_chains/solana/cli/src/main.rs, target_chains/solana/programs/pyth-solana-receiver/Cargo.toml, target_chains/solana/programs/pyth-solana-receiver/src/sdk.rs, target_chains/solana/programs/pyth-solana-receiver/tests/test_post_updates.rs, target_chains/solana/sdk/js/pyth_solana_receiver/src/PythSolanaReceiver.ts, target_chains/solana/sdk/js/pyth_solana_receiver/src/address.ts
To avoid treasury account becoming hot
=> feat: encourage using random treasury id

express_relay/sdk/js/src/index.ts, express_relay/sdk/python/express_relay/client.py
This PR aims to match the `ExecutionParams` type in SDKs and `OpportunityAdapter`
=> refactor(express-relay): Update execution params hash data

governance/xc_admin/packages/xc_admin_cli/src/index.ts, governance/xc_admin/packages/xc_admin_common/src/multisig_transaction/SolanaStakingMultisigInstruction.ts
I want to add this to be able to delegated Pythnet PGAS stake to new validators.
=> feat: enable remote stake delegation

apps/fortuna/Cargo.lock, apps/fortuna/Cargo.toml, apps/fortuna/config.sample.yaml, apps/fortuna/src/command/run.rs, apps/fortuna/src/command/setup_provider.rs, contract_manager/store/chains/EvmChains.yaml
- More logging on failure of deserialization
- Log chain id if the provider registration is failing
- Fix sample config
- Fix dysfunctional rpc address from blast
=> fix(fortuna): Fortuna improvements

target_chains/starknet/contracts/src/hash.cairo, target_chains/starknet/contracts/src/merkle_tree.cairo, target_chains/starknet/contracts/src/pyth.cairo, target_chains/starknet/contracts/src/wormhole.cairo, target_chains/starknet/contracts/tests/wormhole.cairo
=> refactor(target_chains/starknet): remove Result from wormhole

target_chains/starknet/contracts/deploy/local_deploy, target_chains/starknet/contracts/src/wormhole.cairo, target_chains/starknet/contracts/tests/wormhole.cairo
Based on https://github.com/wormhole-foundation/wormhole/blob/main/ethereum/contracts/Governance.sol#L190.
=> feat(target_chains/starknet): wormhole governance VAA verification

target_chains/starknet/contracts/src/byte_array.cairo, target_chains/starknet/contracts/src/util.cairo, target_chains/starknet/contracts/tests/pyth.cairo, target_chains/starknet/contracts/tests/wormhole.cairo
=> refactor(target_chains/starknet): generalize array_try_into

.github/workflows/ci-starknet-tools.yml, target_chains/starknet/tools/test_vaas/Cargo.lock, target_chains/starknet/tools/test_vaas/Cargo.toml, target_chains/starknet/tools/test_vaas/src/bin/generate_keypair.rs, target_chains/starknet/tools/test_vaas/src/bin/generate_wormhole_vaas.rs, target_chains/starknet/tools/test_vaas/src/lib.rs
This is the code that I used to generate VAAs for tests with expected failures. We'll probably add more VAAs later to test all cases.
=> chore(target_chains/starknet): generate wormhole VAAs for tests

SECURITY.md
* 2022 - Ottersec - sui contracts
* 2023 - Zellic - evm contracts
* 2023 - Zellic - cosmwasm/aptos/sui contracts
* 2023 - ToB - message buffer/remote executor contracts and CLI and xc_frontend
* 2024 - ToB - entrophy contracts and fortuna web service
Refs: pyth-network/audit-reports#14
=> Add more security audits

target_chains/starknet/contracts/src/wormhole.cairo, target_chains/starknet/contracts/src/wormhole/errors.cairo, target_chains/starknet/contracts/src/wormhole/interface.cairo, target_chains/starknet/contracts/src/wormhole/parse_vm.cairo
There are no actual code changes, just restructuring, similar to what I've done in the pyth module.
=> refactor(target_chains/starknet): split and refactor wormhole module

express_relay/sdk/js/package-lock.json, express_relay/sdk/js/package.json, express_relay/sdk/js/src/examples/simpleSearcher.ts, express_relay/sdk/js/src/serverTypes.d.ts, express_relay/sdk/python/express_relay/express_relay_types.py, express_relay/sdk/python/express_relay/searcher/examples/simple_searcher.py, express_relay/sdk/python/pyproject.toml
This PR aims to update the bid status to be compatible with auction server. 
Update on bid status is as follows:
- Remove simulation_failed
- Add won
=> feat(express-relay): Update bid status

apps/fortuna/Cargo.lock, apps/fortuna/Cargo.toml, apps/fortuna/src/config.rs, apps/fortuna/src/keeper.rs
500000 was getting parsed as 5242880
=> fix(fortuna): Use u64 since U256 was not deserialized correctly from config

funding.json
We need this file on top of the repo for OP Grant.
=> chore: add funding.json for op grant

contract_manager/scripts/sync_wormhole_guardian_set.ts, contract_manager/src/contracts/sui.ts, contract_manager/src/store.ts, contract_manager/store/chains/SuiChains.yaml, contract_manager/store/contracts/SuiPriceFeedContracts.yaml, contract_manager/store/contracts/SuiWormholeContracts.yaml, governance/xc_admin/packages/xc_admin_common/src/chains.ts, target_chains/sui/contracts/Move.movement_devnet_m2.toml
Modifications to contract manager to manage deploying Sui on Movement.
=> feat(contract_manager): add Movement deployment

target_chains/fuel/contracts/Cargo.lock, target_chains/fuel/contracts/Cargo.toml, target_chains/fuel/contracts/Forc.lock, target_chains/fuel/contracts/fuel-toolchain.toml, target_chains/fuel/contracts/pyth-contract/Forc.toml, target_chains/fuel/contracts/pyth-contract/src/data_structures/accumulator_update.sw, target_chains/fuel/contracts/pyth-contract/src/data_structures/batch_attestation_update.sw, target_chains/fuel/contracts/pyth-contract/src/data_structures/price.sw, target_chains/fuel/contracts/pyth-contract/src/data_structures/update_type.sw, target_chains/fuel/contracts/pyth-contract/src/data_structures/wormhole_light.sw, target_chains/fuel/contracts/pyth-contract/src/events.sw, target_chains/fuel/contracts/pyth-contract/src/main.sw, target_chains/fuel/contracts/pyth-interface/Forc.toml, target_chains/fuel/contracts/pyth-interface/src/data_structures/data_source.sw, target_chains/fuel/contracts/pyth-interface/src/data_structures/governance_instruction.sw, target_chains/fuel/contracts/pyth-interface/src/data_structures/governance_payload.sw, target_chains/fuel/contracts/pyth-interface/src/data_structures/price.sw, target_chains/fuel/contracts/pyth-interface/src/data_structures/wormhole_light.sw, target_chains/fuel/contracts/src/pyth_utils.rs, target_chains/fuel/contracts/tests/utils/setup.rs
changes:
- len -> len()
- have to explicitly add `pub` before struct fields to declare it as public fields
- function changes
=> fix(target_chains/fuel): upgrade to fuel testnet from beta-5

.github/workflows/ci-starknet-contract-release.yml, .github/workflows/ci-starknet-contract.yml, target_chains/starknet/contracts/src/pyth.cairo, target_chains/starknet/contracts/src/pyth/interface.cairo
I've also added CI checks to make sure versions stay in sync and match the tag names.
=> feat(target_chains/starknet): add version method

contract_manager/src/governance.ts
I'm hitting errors using the mainnet-beta endpoint when trying to deploy the entropy contract. This change makes the RPCs configurable in the functions so I can pass in a different RPC in the script. 
The right thing to do here is probably to load the solana rpc urls from configuration files in the chains directory, but doesn't seem worth it to do that now.
=> [contract_manager] Make solana rpcs configurable

target_chains/starknet/contracts/deploy/local_deploy, target_chains/starknet/contracts/src/pyth.cairo, target_chains/starknet/contracts/src/pyth/errors.cairo, target_chains/starknet/contracts/src/pyth/interface.cairo, target_chains/starknet/contracts/tests/pyth.cairo
The user just needs to set allowance for either of the tokens before pushing the update.
=> feat(target_chains/starknet): support two fee tokens

governance/xc_admin/packages/xc_admin_common/src/__tests__/GovernancePayload.test.ts, governance/xc_admin/packages/xc_admin_common/src/governance_payload/PythGovernanceAction.ts, governance/xc_admin/packages/xc_admin_common/src/governance_payload/SetFee.ts, governance/xc_admin/packages/xc_admin_common/src/governance_payload/index.ts
It's needed for Starknet because there are two fee tokens. We add it as a separate action because extending SetFee action would be incompatible with existing contracts.
=> feat(governance): add SetFeeInToken directive

target_chains/starknet/contracts/src/pyth.cairo, target_chains/starknet/contracts/src/pyth/errors.cairo, target_chains/starknet/contracts/src/pyth/interface.cairo, target_chains/starknet/contracts/tests/pyth.cairo, target_chains/starknet/contracts/tests/wormhole.cairo
=> refactor(target_chains/starknet): cleanup and GetDataSources trait

target_chains/starknet/contracts/src/byte_buffer.cairo, target_chains/starknet/contracts/src/hash.cairo, target_chains/starknet/contracts/src/merkle_tree.cairo, target_chains/starknet/contracts/src/pyth.cairo, target_chains/starknet/contracts/src/pyth/errors.cairo, target_chains/starknet/contracts/src/pyth/governance.cairo, target_chains/starknet/contracts/src/pyth/interface.cairo, target_chains/starknet/contracts/src/pyth/price_update.cairo, target_chains/starknet/contracts/src/reader.cairo, target_chains/starknet/contracts/src/util.cairo, target_chains/starknet/contracts/src/wormhole.cairo, target_chains/starknet/contracts/src/wormhole/errors.cairo, target_chains/starknet/contracts/src/wormhole/governance.cairo, target_chains/starknet/contracts/src/wormhole/interface.cairo, target_chains/starknet/contracts/tests/pyth.cairo
I'm being liberal with Copy and Default impls because they are needed when using the type in a map or storage.
=> feat(target_chains/starknet): add all possible derives

contract_manager/scripts/list_wormhole_contracts.ts
We have a couple of these for other contract types, and this was useful for berachain debugging so let's merge it.
=> [contract_manager] Add a script to list wormhole contracts

apps/fortuna/Cargo.lock, apps/fortuna/Cargo.toml, apps/fortuna/src/command/setup_provider.rs
Run setup tasks in parallel for each chain
Short circuit if chain length does not match
=> feat(fortuna): Speedup setup provider

governance/xc_admin/packages/crank_pythnet_relayer/package.json, governance/xc_admin/packages/proposer_server/package.json, pnpm-lock.yaml
=> fix(typescript): add missing typescript deps

pnpm-lock.yaml, target_chains/starknet/sdk/js/package.json, target_chains/starknet/sdk/js/src/examples/usage.ts
I've put the example's dependencies in `devDependencies` and I've put the example itself in `src/examples`. Not sure if it's the correct way to do it.
=> feat(target_chains/starknet): add SDK usage example

.github/workflows/publish-js.yml
Follows instructions on [this](https://github.com/pnpm/pnpm/issues/3141) issues to resolve pnpm publish issue with tokens.
=> fix(js): update publish-js workflow to work for pnpm

express_relay/sdk/js/package.json, express_relay/sdk/js/src/index.ts, express_relay/sdk/js/src/types.ts, express_relay/sdk/python/express_relay/client.py, express_relay/sdk/python/pyproject.toml
This PR aims to restore opportunity bid
=> fix(express-relay): Restore opportunity bid

LICENSE
=> fix(license) Update license to PDA

governance/xc_admin/packages/xc_admin_frontend/next-seo.config.js
In #1781 I accidentally used the wrong base path for the OG image
=> fix(xc_admin_frontend): fix OG image url

pythnet/stake_caps_parameters/Cargo.lock, pythnet/stake_caps_parameters/Cargo.toml, pythnet/stake_caps_parameters/cli/Cargo.toml, pythnet/stake_caps_parameters/cli/src/cli.rs, pythnet/stake_caps_parameters/cli/src/main.rs, pythnet/stake_caps_parameters/programs/stake_caps_parameters/tests/test_stake_caps_parameters.rs
A CLI that I used to test the program
=> feat: simple cli for setting the stake cap parameters

.github/workflows/ci-pre-commit.yml, .pre-commit-config.yaml, pythnet/pythnet_sdk/Cargo.toml, pythnet/pythnet_sdk/src/accumulators/merkle.rs, pythnet/pythnet_sdk/src/test_utils/mod.rs, target_chains/cosmwasm/Cargo.lock, target_chains/cosmwasm/contracts/pyth/src/contract.rs, target_chains/near/receiver/tests/workspaces.rs, target_chains/solana/Cargo.lock, target_chains/solana/programs/pyth-push-oracle/tests/test_update_price_feed.rs, target_chains/solana/programs/pyth-solana-receiver/tests/test_post_price_update_from_vaa.rs, target_chains/solana/programs/pyth-solana-receiver/tests/test_post_updates.rs, target_chains/solana/programs/pyth-solana-receiver/tests/test_post_updates_atomic.rs
Add some stuff to pythnet_sdk that I need
=> feat: publisher-caps-program

governance/xc_admin/packages/crank_pythnet_relayer/src/index.ts, governance/xc_admin/packages/xc_admin_cli/src/index.ts, governance/xc_admin/packages/xc_admin_common/src/deterministic_stake_accounts.ts, governance/xc_admin/packages/xc_admin_common/src/index.ts, governance/xc_admin/packages/xc_admin_common/src/multisig_transaction/SolanaStakingMultisigInstruction.ts
Adding some logic to create proposals that create new stake accounts from the PGAS treasury.
=> feat: support initializing stake accounts

pnpm-lock.yaml, target_chains/solana/sdk/js/pyth_solana_receiver/examples/post_price_update.ts, target_chains/solana/sdk/js/pyth_solana_receiver/examples/post_price_update_instructions.ts, target_chains/solana/sdk/js/pyth_solana_receiver/examples/update_price_feed.ts, target_chains/solana/sdk/js/pyth_solana_receiver/package.json
Update deps so the examples can be run with:
`pnpm exec ts-node examples/<example filename>.ts`
=> fix(pyth_solana_receiver): examples

target_chains/ton/contracts/package.json
seems like lerna is trying to publish this package so making it private
=> fix: make @pythnetwork/pyth-ton private

apps/price_pusher/package.json, apps/price_pusher/src/evm/evm.ts
This PR addresses the issues in the new alpha version that were reported by the users. It now handles more errors and also supports networks with legacy transactions.
=> fix(apps/price_pusher): address issues with alpha version

express_relay/sdk/js/README.md, express_relay/sdk/js/package.json, express_relay/sdk/js/src/const.ts, express_relay/sdk/js/src/examples/dummyTypes.d.ts, express_relay/sdk/js/src/examples/idl/idlDummy.json, express_relay/sdk/js/src/examples/simpleSearcherSvm.ts, express_relay/sdk/js/src/expressRelayTypes.d.ts, express_relay/sdk/js/src/idl/idlExpressRelay.json, express_relay/sdk/js/src/index.ts, express_relay/sdk/js/src/svmPda.ts
This PR updates the TS SDK to account for a few changes to the interfaces of the express relay and dummy programs.
=> fix: update ts sdk to incorporate changes to programs

governance/pyth_staking_sdk/src/pyth-staking-client.ts
This works for 0 reward, not sure if the endianness is correct because of it.
=> fix(staking): claimable rewards

apps/staking/src/components/Guide/index.tsx, apps/staking/src/components/Header/index.tsx, apps/staking/src/components/NoWalletHome/index.tsx, apps/staking/src/components/OracleIntegrityStaking/index.tsx, apps/staking/src/components/ProgramSection/index.tsx
- Fix some awkward spacing
- Fix scroll to top of tabs on initial page load
- Add some transitions
- Fix jumpy guides modal on tab change
=> fix(staking): fix some minor stylistic issues

apps/staking/src/components/AccountSummary/index.tsx, apps/staking/src/components/Button/index.tsx, apps/staking/src/components/CopyButton/index.tsx, apps/staking/src/components/Governance/index.tsx, apps/staking/src/components/ModalDialog/index.tsx, apps/staking/src/components/OracleIntegrityStaking/index.tsx, apps/staking/src/components/ProgramSection/index.tsx, apps/staking/tailwind.config.ts
As of this PR everything works nicely on mobile, with the exception of the publishers table (and the self stake publisher info for MDPs, which uses the same component); I'll do improvements to the publisher table in a separate PR.
=> feat(staking): improve mobile experience

contract_manager/store/chains/EvmChains.yaml, contract_manager/store/contracts/EvmPriceFeedContracts.yaml, contract_manager/store/tokens/Tokens.yaml, target_chains/ethereum/sdk/js/package.json, target_chains/ethereum/sdk/js/src/index.ts
Changed MAT -> POL for fetch_fee script
Removed flow_previewnet from contract manager
=> fix(contract_manager/tokens) MAT -> POL

governance/pyth_staking_sdk/src/pyth-staking-client.ts
Merge positions is called for OIS in claim rewards, but it's never called in the context of Pyth Governance, I want to do it when you try to stake more tokens.
=> feat: optimize governance positions

target_chains/solana/programs/pyth-price-store/src/processor/initialize_publisher.rs, target_chains/solana/programs/pyth-price-store/src/processor/submit_prices.rs, target_chains/solana/programs/pyth-price-store/src/validate.rs
Fixes a potential issue with a possibility of multiple config accounts or publisher config accounts.
=> fix(target_chains/solana): use find_program_address on initialize

apps/staking/src/components/OracleIntegrityStaking/index.tsx
Also return to first page when changing page size
=> fix(staking): fix last page getting dropped

governance/xc_admin/packages/xc_admin_cli/src/index.ts
The JS Set is not smart to support custom equality operator and for object it only considers the equal objects the same.
Activate and approve instructions are also changed because the sqds/mesh sdk uses an old Anchor version that uses a deprecated getRecentBlockHash RPC method. This method is removed in Agave v2 and devnet is fully on Agave v2 now.
=> fix(governance/xc_admin_cli): remove duplicates in pub buffer init

target_chains/fuel/sdk/js/src/types/PythContract.ts
fix error here: https://github.com/pyth-network/pyth-crosschain/actions/runs/11321658983/job/31481046601#step:7:10
=> fix(target_chains/fuel): fix ci release

apps/api-reference/package.json, apps/staking/package.json, governance/xc_admin/packages/xc_admin_frontend/package.json, packages/component-library/.gitignore, packages/component-library/package.json, packages/component-library/turbo.json, packages/component-library/vercel.json
- Don't try to pull env vars from Vercel in any CI
- Run storybook with start:dev
- Fix storybook vercel build command
=> fix(turbo): turbo repo fixes

apps/price_pusher/package.json, apps/price_pusher/src/solana/solana.ts
The healthcheck is failing sometimes, leading to downtime, let's increase and add some logs to understand better.
=> fix: increase threshold value

.pre-commit-config.yaml
Revert fortuna CI fmt toolchain to nightly to fix CI in main
=> fix(fortuna): undo change to fmt ci toolchain

target_chains/solana/sdk/js/pyth_solana_receiver/README.md, target_chains/solana/sdk/js/pyth_solana_receiver/examples/post_price_update.ts, target_chains/solana/sdk/js/pyth_solana_receiver/examples/post_price_update_from_benchmarks.ts, target_chains/solana/sdk/js/pyth_solana_receiver/examples/post_price_update_instructions.ts, target_chains/solana/sdk/js/pyth_solana_receiver/examples/update_price_feed.ts, target_chains/solana/sdk/js/pyth_solana_receiver/src/PythSolanaReceiver.ts
This PR incorporates some best practices in the solana examples to achieve better tx landing rate.
It will solve some issues like:
> TransactionExpiredTimeoutError: Transaction was not confirmed in 30.00 seconds. It is unknown if it succeeded or failed. Check signature 5jedawNwhv5AuHzA4q97xko7W9FyifQvUDP61xS5rKBJ3iSxvTMKA5XqzY5ng82yAUawsaQgEjWjSi3fL3T9k8es using the Solana Explorer or CLI tools.
=> chore: improve landing rate in examples

apps/insights/src/app/price-feeds/[slug]/error.ts, apps/insights/src/components/Error/index.module.scss, apps/insights/src/components/Error/index.tsx, apps/insights/src/components/NoResults/index.module.scss, apps/insights/src/components/NoResults/index.tsx, apps/insights/src/components/NotFound/index.module.scss, apps/insights/src/components/NotFound/index.tsx, apps/insights/src/components/Overview/index.module.scss, apps/insights/src/components/PriceFeed/chart.module.scss, apps/insights/src/components/PriceFeed/chart.tsx, apps/insights/src/components/PriceFeed/layout.module.scss, apps/insights/src/components/PriceFeed/price-components-card.tsx, apps/insights/src/components/PriceFeed/price-components.tsx, apps/insights/src/components/PriceFeed/reference-data.tsx, apps/insights/src/components/PriceFeeds/index.module.scss, apps/insights/src/components/PriceFeeds/price-feeds-card.tsx, apps/insights/src/components/Publishers/index.module.scss, apps/insights/src/components/Publishers/index.tsx, apps/insights/src/components/Publishers/publishers-card.tsx, apps/insights/src/components/Ranking/index.module.scss, apps/insights/src/components/Ranking/index.tsx, apps/insights/src/components/Root/index.module.scss, apps/insights/src/use-query-param-filter-pagination.ts, packages/component-library/src/Table/index.module.scss, packages/component-library/src/Table/index.tsx, packages/component-library/src/theme.scss
- Add column sorting to tables
- Add empty states to searchable tables
- Improve error & not found pages
- Fix jumpy page transition animations
=> feat(insights): many insights hub improvements

governance/xc_admin/packages/xc_admin_common/src/deterministic_oracle_accounts.ts
I wanted to slice until index 32 but I was slicing from index 32 resulting in empty strings.
=> fix: seed computation

apps/staking/src/app/api/v1/cmc/supply/route.ts
CMC team asked for this. Let's make it default to the old behavior.
=> chore: add cmc decimal representation

.github/workflows/ci-remote-executor.yml
I just copied this https://github.com/pyth-network/pyth-crosschain/pull/2302
=> fix: remote executor ci

.github/workflows/ci-pre-commit.yml
Two issues here. First of all, we were checking out their repository, a second time after caching which deleted a bunch of the restored directories. Second, we weren't caching the build for some of the apps.
=> Chore: speed up pre-commit CI workflow 

.github/pull_request_template.md
Fixes a formatting failure that's causing pre-commit to fail
Prettier doesn't like the format of this file.
=> fix: fix failing pre-commit

contract_manager/store/contracts/EvmEntropyContracts.yaml
=> chore(entropy) Add Story protocol

target_chains/sui/cli/src/pyth_deploy.ts
I had incorrect imports in the sui client after applying some fixes that resulted in cli erroring on runtime.
=> fix(target_chains/sui/cli): use proper imports

apps/fortuna/Cargo.lock, apps/fortuna/Cargo.toml, apps/fortuna/src/eth_utils/utils.rs, apps/fortuna/src/keeper/process_event.rs
=> fix: update fortuna version to 7.4.5 and enhance transaction submission logging

governance/xc_admin/packages/xc_admin_cli/src/index.ts
=> chore: add proposal url to deactivate

.github/workflows/ci-pre-commit.yml
=> chore(ci): Fix runs_on for precommit again

apps/entropy-debugger/src/store/entropy-deployments.ts, contract_manager/store/chains/EvmChains.yaml, contract_manager/store/contracts/EvmEntropyContracts.yaml, contract_manager/store/contracts/EvmPriceFeedContracts.yaml, contract_manager/store/contracts/EvmWormholeContracts.yaml, governance/xc_admin/packages/xc_admin_common/src/chains.ts, target_chains/ethereum/sdk/js/README.md, target_chains/ethereum/sdk/js/src/index.ts
=> fix(contract-manager) Rename sonic test

.github/workflows/ci-near-contract.yml
See #2498 .
CI is failing
The GHA run is the test!
=> fix: fix near contract CI job

apps/price_pusher/grafana-dashboard.sample.json
=> chore(apps/price_pusher): update grafana dashboard sample

contract_manager/store/chains/EvmChains.yaml, contract_manager/store/contracts/EvmPriceFeedContracts.yaml, contract_manager/store/contracts/EvmWormholeContracts.yaml, governance/xc_admin/packages/xc_admin_common/src/chains.ts
=> chore(pricefeed) Deploy Megaeth

apps/entropy-debugger/src/store/entropy-deployments.ts
=> chore(entropy-debugger)-add-hyperevm

contract_manager/store/contracts/EvmEntropyContracts.yaml
=> chore(entropy) Add soneium

apps/staking/src/middleware.ts
=> Add logging to debug nonfunctional IP allowlist

.github/workflows/publish-rust-lazer-protocol.yml, .github/workflows/publish-rust-lazer-publisher-sdk.yml
Add workflow dispatch for manual trigger.
Typo lead to invalid workflow execution. Tag already released.
=> fix: Add Dispatch for Lazer Publisher SDK Action

lazer/Cargo.lock, lazer/contracts/solana/programs/pyth-lazer-solana-contract/Cargo.toml
Bump version
To allow consumers to use the new contract API.
=> chore(lazer): bump lazer contract version

apps/staking/src/components/OracleIntegrityStaking/index.tsx
Hide empty pools which you aren't staked to in staking
We should not allow people to stake to empty pools
=> feat(staking): hide empty pools

.github/workflows/publish-rust-lazer-publisher-sdk.yml
Workflow couldn't find the script. I am pretty sure I just need to add "./"
Workflow fails
N/A
=> fix(lazer-publisher-sdk): Fix script not found

target_chains/ethereum/contracts/contracts/pulse/Scheduler.sol
Update balances before keeper payment
Avoid reentrancy
=> fix(pulse): update balance before keeper payment

apps/fortuna/Cargo.lock, apps/fortuna/Cargo.toml, apps/fortuna/src/api/revelation.rs
=> fix(fortuna): fix openapi schema

target_chains/ethereum/contracts/contracts/pulse/Scheduler.sol, target_chains/ethereum/contracts/contracts/pulse/SchedulerUpgradeable.sol, target_chains/ethereum/contracts/forge-test/PulseScheduler.t.sol, target_chains/ethereum/contracts/forge-test/PulseSchedulerGasBenchmark.t.sol, target_chains/ethereum/contracts/forge-test/PulseSchedulerGovernance.t.sol
Disable implementation contract initializers
https://docs.openzeppelin.com/upgrades-plugins/writing-upgradeable#initializing_the_implementation_contract
=> fix(pulse): disable impl contract initializer

apps/hermes/client/js/README.md
=> fix(hermes-docs)-fix Readme file

target_chains/ethereum/contracts/contracts/entropy/EntropyUpgradable.sol
I'm making this 2.0 to agree with all of our comms around this. I'm skipping version 1 but whatever.
=> chore(entropy): Bump entropy version

governance/pyth_staking_sdk/package.json
=> fix(staking-sdk): relax staking-sdk node engine requirement

apps/api-reference/src/evm-networks.ts
=> fix(api-reference) Story testnet address

contract_manager/src/node/utils/store.ts, contract_manager/store/chains/EvmChains.json, contract_manager/store/contracts/EvmEntropyContracts.json
=> fix(contract_manager): cleanup entropy contracts

governance/xc_admin/packages/xc_admin_cli/src/index.ts
Print skipped vote accounts (that are already destaked)
It improves UX of the user using the CLI.
=> feat: print skipped vote account

.github/workflows/ci-stylus-check-wasm.yml
This PR aims to fix the CI check for stylus wasm
=> Fix ci stylus wasm check

contract_manager/store/chains/EvmChains.json, contract_manager/store/contracts/EvmEntropyContracts.json
=> chore(entropy) Deploy Hype Testnet

apps/pyth-lazer-agent/Cargo.lock, apps/pyth-lazer-agent/Dockerfile, apps/pyth-lazer-agent/src/relayer_session.rs
- logging adjustments in relayer session
- cargo update
- add ca-certificates to Dockerfile for relayer ws session
=> fix(pyth-lazer-agent): logging tweaks, cargo update, Dockerfile fix

target_chains/ethereum/sdk/solidity/package.json
=> chore(evm-sdk)-bump-version

apps/insights/src/components/PriceFeed/chart.tsx
Fix issue with insights hub chart resetting repeatedly
=> fix(insights): fix insights hub chart re-initializing repeatedly

.github/workflows/ci-lazer-rust.yml
https://github.com/arduino/setup-protoc/issues/63
=> fix: lazer ci

Cargo.lock, lazer/contracts/solana/Cargo.lock, lazer/contracts/solana/programs/pyth-lazer-solana-contract/Cargo.toml, lazer/publisher_sdk/rust/Cargo.toml, lazer/sdk/rust/client/Cargo.toml, lazer/sdk/rust/protocol/Cargo.toml, lazer/sdk/rust/protocol/src/jrpc.rs
Add an extra string details to the ParseError in the JRPC schema
Give consumers more context
=> feat(pyth-lazer) Add more context to ParseError in JRPC protocol

packages/known-publishers/src/icons/monochrome/blocksize.svg
Update Blocksize icon
Blocksize is updating their brand and has requested that we update their icon
=> chore: update blocksize icon

governance/pyth_staking_sdk/package.json
=> chore: allow node 24 in staking sdk

target_chains/stylus/Cargo.lock, target_chains/stylus/Cargo.toml, target_chains/stylus/contracts/wormhole/src/lib.rs, target_chains/stylus/contracts/wormhole/tests/integration_test.rs
Updated to the most recent version of the Stylus testing framework, cleaning up ccode.
Keeping things updated for cross-compatability with pyth receiver.
=> fix(stylus) - update wormhole motsu testing + versions

Cargo.lock, lazer/publisher_sdk/rust/Cargo.toml
=> chore(lazer): bump version

Cargo.lock, lazer/contracts/solana/programs/pyth-lazer-solana-contract/Cargo.toml, lazer/publisher_sdk/rust/Cargo.toml, lazer/sdk/rust/client/Cargo.toml, lazer/sdk/rust/protocol/Cargo.toml
=> chore(lazer): bump pyth-lazer-protocol to 0.9.1

governance/remote_executor/programs/remote-executor/Cargo.toml, governance/remote_executor/programs/remote-executor/src/state/governance_payload.rs, governance/remote_executor/programs/remote-executor/src/state/posted_vaa.rs, governance/xc_admin/packages/xc_admin_common/src/chains.ts
Add fogo testnet to remote executor.
=> feat(remote-executor): add fogo testnet

Cargo.lock, apps/pyth-lazer-agent/Cargo.toml
=> chore(pyth-lazer-agent) Bump the agent to 0.3.1

Cargo.lock, apps/fortuna/Cargo.toml
=> chore(bump) Bump Fortuna version

Cargo.lock, lazer/contracts/solana/programs/pyth-lazer-solana-contract/Cargo.toml, lazer/publisher_sdk/rust/Cargo.toml, lazer/sdk/rust/client/Cargo.toml
Upgrade all dependencies on `pyth-lazer-protocol`  across projects. Also release a new version of `pyth-lazer-client`.
Releasing changes
=> chore(pyth-lazer-client) Upgrade lazer protocol dependency

Cargo.lock, lazer/publisher_sdk/rust/Cargo.toml
=> chore: bump pyth-lazer-publisher-sdk to 0.4.0

contract_manager/store/contracts/FuelPriceFeedContracts.json
updating testnet contract addresses across repo for the fuel contract after version upgrade and redeployment.
=> refactor(fuel): updating testnet contract addresses across repo

apps/insights/src/hooks/use-price-formatter.ts
Increased the max number of decimals so now it shows 5 instead of 4
=> fix(insights): increase max decimals

Cargo.lock, apps/fortuna/Cargo.toml, apps/fortuna/src/history.rs
=> fix(fortuna): callback_failed check against int

lazer/sdk/rust/protocol/src/price/tests.rs
Reverts pyth-network/pyth-crosschain#2943
=> Revert "feat: add more test to pyth lazer protocol"

packages/component-library/src/SingleToggleGroup/index.module.scss, packages/component-library/src/SingleToggleGroup/index.tsx
=> fix: sass lint

apps/api-reference/package.json, pnpm-lock.yaml, pnpm-workspace.yaml
=> chore(api-reference) Update Viem

contract_manager/store/chains/EvmChains.json, contract_manager/store/contracts/EvmPriceFeedContracts.json, contract_manager/store/contracts/EvmWormholeContracts.json, governance/xc_admin/packages/xc_admin_common/src/chains.ts
=> chore(pricefeeds) Deploy Fluent

apps/insights/src/server/pyth.ts
=> fix(insights): fix error on loading GDP publishers

apps/insights/src/components/Publisher/layout.tsx
this was causing issues because the `useCallback` was in a server component
=> fix: remove useCallback from server comp

apps/insights/src/components/Publisher/layout.tsx, apps/insights/src/components/Publisher/publisher-conformance-report.tsx
Still the same issue with useCallback inside server components from the hook, so I've split the component to a client comp.
=> feat: separate into client component

apps/insights/src/hooks/use-query-param-filter-pagination.ts
Bug with the total number of items from the hook.
=> fix: total number

contract_manager/store/chains/EvmChains.json, contract_manager/store/contracts/EvmPriceFeedContracts.json, contract_manager/store/contracts/EvmWormholeContracts.json, governance/xc_admin/packages/xc_admin_common/src/chains.ts
=> chore(pricefeeds) Deploy 0g

apps/entropy-explorer/src/components/Home/request-drawer.tsx
=> fix(entropy-explorer) Fix cast command

Cargo.lock, apps/fortuna/Cargo.toml
=> bump(fortuna) Version

apps/hip-3-pusher/Dockerfile, apps/hip-3-pusher/config/config.toml, apps/hip-3-pusher/pyproject.toml, apps/hip-3-pusher/uv.lock
=> feat(hip-3-pusher): build/docker fixes
